{
  "hash": "f1755161a4cfdf6b6e63642ae77f5965",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Estadística Descriptiva\"\nsubtitle: \"Tema I — Bioestadística para Fisioterapia\"\nauthor:\n  - name: \"Miguel Angel Luque-Fernández\"\n    affiliation: \"Dpto. Estadística e Investigación Operativa, Universidad de Granada\"\n    email: \"mluquefe@ugr.es\"\n    url: \"https://migariane.github.io\"\ndate: \"2026\"\nlicense: \"CC BY 4.0\"\nformat:\n  revealjs:\n    slide-number: c/t\n    code-fold: true\n    code-summary: \"Mostrar código R\"\n    fig-width: 9\n    fig-height: 5.5\n    code-overflow: wrap\n    lang: es\nexecute:\n  warning: false\n  message: false\n  echo: true\n  eval: true\n---\n\n\n\n# Estadística Descriptiva {.center}\n\n![](logo.png){width=\"90px\"}\n\n**Grado en Fisioterapia**\n\n**CC BY 4.0** · Miguel Angel Luque-Fernández\n\n[Miguel Angel Luque-Fernández](https://migariane.github.io) · [maluque.netlify.app](https://maluque.netlify.app)\n\nDpto. Estadística e Investigación Operativa · Universidad de Granada\n\n## Objetivos de aprendizaje — Tema 1\n\n::: {.callout-tip}\n**Al finalizar este tema sabrás:**\n:::\n\n::: {.incremental}\n1. Clasificar cualquier variable clínica (nominal, ordinal, discreta, continua)\n2. Construir e interpretar tablas de frecuencias con $n_i$, $f_i$, $N_i$\n3. Elegir el gráfico adecuado según el tipo de variable\n4. Calcular e interpretar medidas de posición (media, mediana, moda, percentiles)\n5. Calcular e interpretar medidas de dispersión (varianza, DT, CV, RIQ)\n6. Usar `freq()` de BioEstatR para obtener todos los estadísticos en una línea\n:::\n\n## El proceso de investigación empírica\n\n::: {.incremental}\n1. **Definición** de la población objeto de estudio\n2. **Selección de la muestra** → Representatividad\n3. **Medición** → Validez y fiabilidad del instrumento\n4. **Formato** admisible para análisis estadístico\n5. **Métodos descriptivos** → Resumen de datos\n6. **Métodos inferenciales** → ¿Son correctos los supuestos? ¿Es posible un modelo?\n7. **Informe estadístico** → Evaluación de resultados\n8. **Publicación** → Nueva información sobre la población\n:::\n\n::: {.callout-warning}\n¿En cuáles de estas etapas se puede cometer error? ¿De qué tipo?\n:::\n\n## Fundamentos teóricos de la medición en fisioterapia\n\n::: {.callout-note}\n**Escala de medida (Stevens, 1946):** Clasificación de variables según las operaciones matemáticas permitidas. Determina qué estadísticos son válidos.\n\n| Escala | Operaciones | Ejemplo en Fisioterapia | Estadísticos válidos |\n|:-------|:-----------|:------------------------|:---------------------|\n| Nominal | =, ≠ | Tipo de lesión (muscular/articular/ósea) | Moda, frecuencias |\n| Ordinal | =, ≠, <, > | Escala EVA (0-10), estadio de recuperación | + Mediana, percentiles |\n| Intervalo | =, ≠, <, >, +, − | Temperatura corporal (°C) | + Media, DT |\n| Razón | =, ≠, <, >, +, −, ×, ÷ | Rango de Movimiento — ROM (grados), fuerza (kg), presión (mmHg) | + CV, todas |\n\n**Implicación práctica:** La escala EVA es ordinal, no intervalo. Estrictamente, la media de EVA no es válida (aunque en la práctica clínica se usa). La mediana y el RIQ son las medidas correctas.\n:::\n\nReferencia: Stevens, S. S. (1946). On the theory of scales of measurement. Science, 103(2684), 677-680.\n\n## Tabla de datos en bruto\n\nLos datos se organizan como **casos × variables**. Cada fila = individuo, cada columna = variable.\n\n- **Caso:** unidad de observación (paciente)\n- **Variable:** característica medida\n- **Valor perdido (missing):** dato no observado\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar=c(1,1,2,1))\nplot(NA, xlim=c(0,10), ylim=c(0,5), axes=F, xlab=\"\", ylab=\"\", main=\"Del Individuo al Dato\")\n\n# Caja POBLACIÓN\nrect(0.3, 2.5, 2.5, 4.5, col=rgb(0.2,0.5,0.8,0.15), border=\"#1a5276\", lwd=2.5)\ntext(1.4, 3.8, \"POBLACIÓN\", font=2, cex=0.9, col=\"#1a5276\")\ntext(1.4, 3.3, \"N (inaccesible)\", cex=0.7, col=\"#1a5276\")\ntext(1.4, 2.9, \"(inaccesible)\", cex=0.6, col=\"grey40\")\n\n# Flecha 1\narrows(2.6, 3.5, 3.9, 3.5, lwd=2, col=\"darkgreen\", length=0.12)\ntext(3.25, 3.85, \"Muestreo\", cex=0.7, col=\"darkgreen\", font=2)\n\n# Caja MUESTRA\nrect(4.0, 2.5, 6.2, 4.5, col=rgb(0.2,0.7,0.3,0.15), border=\"#1e6e3e\", lwd=2.5)\ntext(5.1, 3.8, \"MUESTRA\", font=2, cex=0.9, col=\"#1e6e3e\")\ntext(5.1, 3.3, paste0(\"n = \", 30), cex=0.7, col=\"#1e6e3e\")\ntext(5.1, 2.9, \"(accesible)\", cex=0.6, col=\"grey40\")\n\n# Flecha 2\narrows(6.3, 3.5, 7.6, 3.5, lwd=2, col=\"darkgreen\", length=0.12)\ntext(6.95, 3.85, \"Medición\", cex=0.7, col=\"darkgreen\", font=2)\n\n# Caja DATOS\nrect(7.7, 2.5, 9.9, 4.5, col=rgb(0.8,0.4,0.1,0.15), border=\"#b03a2e\", lwd=2.5)\ntext(8.8, 3.8, \"DATOS\", font=2, cex=0.9, col=\"#b03a2e\")\ntext(8.8, 3.3, \"n × p\", cex=0.7, col=\"#b03a2e\")\ntext(8.8, 2.9, \"(matriz)\", cex=0.6, col=\"grey40\")\n\n# Flecha hacia abajo desde DATOS\narrows(8.8, 2.4, 8.8, 1.8, lwd=2, col=\"steelblue\", length=0.12)\narrows(8.8, 1.8, 3.5, 1.2, lwd=2, col=\"steelblue\", length=0.12)\narrows(8.8, 1.8, 7.0, 1.2, lwd=2, col=\"steelblue\", length=0.12)\n\n# Descripción e Inferencia\ntext(2.0, 1.0, \"Descriptiva\\n(resumir)\", cex=0.7, col=\"#1a5276\", font=2)\ntext(5.5, 1.0, \"Inferencia\\n(extender a pob.)\", cex=0.7, col=\"#1a5276\", font=2)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-1-1.png){width=864}\n:::\n:::\n\n\n## Clasificación de variables\n\n::: {.callout-important}\n**Regla de oro:** Antes de cualquier análisis, identifica el tipo de variable. De ello depende TODO: qué gráfico usar, qué medidas calcular, y qué test aplicar.\n:::\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**Cualitativas (Categóricas)** — atributos, no números\n\n| Tipo | Característica | Ejemplos en Fisioterapia |\n|:-----|:---------------|:-------------------------|\n| **Nominal** | Sin orden | Sexo, grupo sanguíneo, tipo de lesión (muscular/articular/ósea), diagnóstico |\n| **Binaria** | Solo 2 valores (caso especial de nominal) | Fuma (sí/no), alta (sí/no), complicación post-Qx (sí/no) |\n| **Ordinal** | Con orden natural, distancia no medible | Escala EVA (0-10), estadio de recuperación (I-II-III-IV), escala Likert, grado de esguince |\n\n:::\n::: {.column width=\"50%\"}\n\n**Cuantitativas (Numéricas)** — números con significado matemático\n\n| Tipo | Característica | Ejemplos en Fisioterapia |\n|:-----|:---------------|:-------------------------|\n| **Discreta** | Valores aislados (enteros, contables) | Nº de sesiones, nº de recaídas, nº de articulaciones afectadas |\n| **Continua** | Cualquier valor en un intervalo | Rango de Movimiento — ROM (grados), fuerza (kg), presión arterial (mmHg), IMC (kg/m²), edad (años) |\n\n:::\n:::\n\n*Pregunta: ¿Qué tipo de variable es el número de sesiones de fisioterapia recibidas? ¿Y el diagnóstico principal?*\n\n\n## Tipos de variables — Cualitativas\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar=c(4,4,3,1))\ndiag <- c(Lumbalgia=40, Cervicalgia=35, Omalgia=25)\nbarplot(diag, col=c(\"steelblue\",\"coral\",\"gold\"), main=\"Nominal: Diagnóstico\",\n        ylab=\"Frecuencia\", ylim=c(0,45))\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-2-1.png){width=864}\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar=c(4,4,3,1))\neva <- c(Leve=30, Moderado=45, Intenso=20, Muy_intenso=5)\nbarplot(eva, col=colorRampPalette(c(\"lightyellow\",\"darkred\"))(4),\n        main=\"Ordinal: Nivel de Dolor (EVA)\", ylab=\"Frecuencia\")\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-3-1.png){width=864}\n:::\n:::\n\n:::\n:::\n\n## Tipos de variables — Cuantitativas\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar=c(4,4,3,1))\nses <- c(4,6,8,10,12); freq <- c(5,15,25,10,5)\nbarplot(setNames(freq,ses), col=\"seagreen\", main=\"Discreta: Nº Sesiones\",\n        xlab=\"Sesiones\", ylab=\"Frecuencia\")\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-4-1.png){width=864}\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar=c(4,4,3,1))\nset.seed(42)\nrom <- rnorm(200, 150, 20)\nhist(rom, col=\"steelblue\", border=\"white\", breaks=20, main=\"Continua: ROM (grados)\",\n     xlab=\"Grados\", ylab=\"Frecuencia\", freq=FALSE)\ncurve(dnorm(x,150,20), add=T, col=\"darkgreen\", lwd=2)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-5-1.png){width=864}\n:::\n:::\n\n:::\n:::\n\n## Contenido informativo y categorización\n\n::: {.callout-note}\n**Principio estadístico:** La escala de medida determina la **cantidad de información** que contiene una variable. Cada paso de categorización **pierde información irreversiblemente** — es una operación matemática no invertible.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar=c(3, 1, 2, 1))\nplot(NA, xlim=c(0, 10), ylim=c(0, 4), axes=F, xlab=\"\", ylab=\"\",\n     main=\"Pérdida de Información al Categorizar\")\n\n# Flecha horizontal\narrows(0.5, 2, 9.5, 2, lwd=3, col=\"#2c3e50\", length=0.12)\ntext(5, 2.4, \"MAYOR información                                     MENOR información\", cex=0.8, col=\"#2c3e50\", font=2)\n\n# Cajas para cada nivel\ncw <- 1.6; yb <- 1.2; yt <- 1.8\ncols <- c(\"#1a5276\",\"#2471a3\",\"#2e86c1\",\"#7fb3d8\",\"#b3d4ec\")\nlabels <- c(\"Continua\", \"Discreta\", \"Ordinal\", \"Nominal\", \"Binaria\")\nexamples <- c(\"Edad 22.2 a.\", \"Edad 22 a.\", \"Grupos edad\", \"Edad > 35\", \"Sí / No\")\nfor(i in 1:5){\n  xl <- 0.4 + (i-1)*1.85\n  rect(xl, yb, xl+cw, yt, col=cols[i], border=\"white\", lwd=2)\n  text(xl+cw/2, (yb+yt)/2, labels[i], col=\"white\", font=2, cex=0.85)\n  text(xl+cw/2, yb-0.3, examples[i], col=cols[i], font=2, cex=0.7)\n}\n# Flechas de pérdida\nfor(i in 1:4){\n  xm <- 0.4 + i*1.85 - 0.12\n  arrows(xm, 2.8, xm, 2.2, lwd=1.5, col=\"#c0392b\", length=0.08)\n}\ntext(5, 3.1, \"Pérdida de información\", col=\"#c0392b\", cex=0.7, font=3)\n\n# Nota al pie\ntext(5, 0.3, \"Cada flecha hacia la derecha destruye información original no recuperable\", cex=0.7, col=\"grey40\")\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-6-1.png){width=864}\n:::\n:::\n\n\n**Ejemplo clínico — Edad en fisioterapia:** 22.2 años (continua, 4 cifras significativas) → 22 años (discreta, pierde decimales) → \"18-25 años\" (ordinal, pierde orden individual) → \"Adulto joven\" (nominal, sin orden numérico) → \"≥ 18\" (binaria, todo reducido a sí/no). En cada paso se destruye información que ningún análisis posterior puede recuperar. **Recategorizar es fácil; recuperar la granularidad perdida es imposible.**\n\n| Nivel | Información | Operaciones válidas | Ejemplo clínico |\n|:------|:-----------|:--------------------|:----------------|\n| Continua → Discreta | Pierde precisión decimal | Se mantienen +, −, ×, ÷ | 22.2 → 22 años |\n| Discreta → Ordinal | Pierde magnitud exacta de diferencias | Se pierde ×, ÷ | Edad → Grupos etarios |\n| Ordinal → Nominal | Pierde el orden | Se pierde <, > | Grupos → Categorías |\n| Nominal → Binaria | Pierde todas las categorías salvo una | Solo =, ≠ | Categorías → Sí/No |\n\nCada paso de categorización **pierde información irreversiblemente**.\n\n*Pregunta: En tu práctica clínica, ¿qué información se pierde cuando registras el IMC como \"normal/sobrepeso/obeso\" en lugar del valor numérico?*\n\n\n## Constructos, cuestionarios y escalas\n\n**Constructo:** concepto teórico no medible físicamente → se usan **cuestionarios** (ítems con escala Likert, sumativos).\n\n| Escala | Mide | Ítems | Puntos de corte |\n|--------|------|:-----:|-----------------|\n| **Barthel** | Dependencia AVD | 10 | 0-19 Total, 20-39 Grave, 40-59 Moderada, 60-85 Leve, 86-100 Independiente |\n| **Norton** | Riesgo úlceras | 14 | 1-11 Muy alto, 12-14 Moderado, 15-20 Mínimo |\n| **Zarit** | Sobrecarga cuidador | 22 | <46 No, 46-56 Moderada, >56 Intensa |\n\n**Validez:** ¿mide lo que debe? **Fiabilidad:** ¿resultados consistentes al repetir?\n\n## Notación: El símbolo sumatorio $\\sum$\n\n# Organización y Resumen de Datos {.center}\n\n\n**Contexto clínico:** Un fisioterapeuta mide la flexión de rodilla en 5 pacientes tras rehabilitación. Para calcular la media necesita **sumar** todas las mediciones.\n\n::: {.framed}\n$$\\sum_{i=1}^{n} x_i = x_1 + x_2 + \\cdots + x_n$$\n:::\n\nEl símbolo $\\sum$ (sigma mayúscula) significa **\"sumar todos los valores de $x$ desde $i=1$ hasta $i=n$\"**.\n\n**Propiedades que usaremos constantemente:**\n\n| Propiedad | Fórmula | ¿Qué significa? |\n|:----------|:--------|:----------------|\n| Suma de constantes | $\\sum_{i=1}^{n} (x_i + a) = \\sum x_i + n \\cdot a$ | Sumar $a$ a cada dato añade $n \\times a$ al total |\n| Factor común | $\\sum_{i=1}^{n} (a \\cdot x_i) = a \\cdot \\sum x_i$ | Multiplicar cada dato por $a$ multiplica la suma por $a$ |\n\n**Ejemplo — ROM de rodilla (°):** 125, 132, 128, 135, 130\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(125, 132, 128, 135, 130)\npar(mar=c(4,4,2,1))\nbp <- barplot(x, names.arg=1:5, col=\"steelblue\", border=\"white\",\n        main=paste0(\"ROM en 5 pacientes — Suma = \", sum(x), \"°\"),\n        xlab=\"Paciente i\", ylab=\"Grados (°)\", ylim=c(0,150))\ntext(bp, x+5, x, font=2, cex=0.9)\nabline(h=mean(x), col=\"darkgreen\", lwd=2.5, lty=2)\ntext(5.5, mean(x)+4, paste0(\"Media = \", mean(x), \"°\"), col=\"darkgreen\", font=2, cex=0.95)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-7-1.png){width=864}\n:::\n:::\n\n\n$$\\sum_{i=1}^{5} x_i = 125 + 132 + 128 + 135 + 130 = 650 \\quad \\Rightarrow \\quad \\bar{x} = \\frac{650}{5} = 130°$$\n\n::: {.callout-note}\n**¿Por qué es importante?** La media, la varianza y prácticamente todos los estadísticos se construyen con sumatorios. Dominar $\\sum$ es dominar la notación estadística. La **frecuencia relativa** $f_i = n_i/n$ es otro ejemplo de estandarización: convierte frecuencias absolutas en proporciones comparables entre grupos de distinto tamaño.\n:::\n\n## Tablas de frecuencias — Variables nominales\n\n**Grupo sanguíneo (n=500):**\n\n| Grupo | $n_i$ | $f_i$ | % |\n|-------|:-----:|:-----:|:---:|\n| A | 150 | 0.30 | 30.0 |\n| B | 75 | 0.15 | 15.0 |\n| AB | 25 | 0.05 | 5.0 |\n| O | 250 | 0.50 | 50.0 |\n| **Total** | **500** | **1.00** | **100** |\n\n**Proporción:** $p_i = n_i/n$. **Moda:** O (mayor frecuencia).\n\n::: {.callout-note}\n**Álgebra de Tablas de Frecuencias — Variables Nominales**\n\nSea una variable con $k$ categorías. La tabla de frecuencias se define mediante tres funciones:\n\n| Magnitud | Símbolo | Definición | Propiedad fundamental |\n|:---------|:-------:|:-----------|:----------------------|\n| **Frecuencia absoluta** | $n_i$ | Nº de observaciones en categoría $i$ | $\\sum_{i=1}^{k} n_i = n$ |\n| **Frecuencia relativa** | $f_i$ | $f_i = \\dfrac{n_i}{n}$ | $\\sum_{i=1}^{k} f_i = 1$ |\n| **Frecuencia acumulada** | $N_i$ | $N_i = \\sum_{j=1}^{i} n_j$ | $N_k = n$ |\n\n:::\n\n## Comprueba tu comprensión\n\n**Ejercicio rápido:** Un fisioterapeuta mide la flexión de rodilla en 3 pacientes: 125°, 132°, 128°.\n\n1. Calcula $\\sum_{i=1}^{3} x_i$\n2. ¿Cuánto vale $\\bar{x}$?\n\n## Relaciones algebraicas — Tablas de frecuencias\n\n::: {.callout-note}\n**De las definiciones a las propiedades:** Una vez definidas $n_i$, $f_i$ y $N_i$, sus relaciones algebraicas permiten interpretar la estructura de los datos.\n:::\n\n- $0 \\leq f_i \\leq 1$ para todo $i$ (cada $f_i$ es una probabilidad empírica)\n- $f_i \\times 100 = \\%$ en categoría $i$\n- $N_i$ solo tiene sentido para variables **ordinales** (requiere orden)\n- La colección $\\{f_1, f_2, \\ldots, f_k\\}$ define la **distribución empírica** de la variable\n\n## Gráficos para variables nominales\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrupos <- c(A=150, B=75, AB=25, O=250)\ncols <- c(\"steelblue\",\"coral\",\"gold\",\"seagreen\")\npar(mfrow=c(1,2), mar=c(4,4,4,1))\nbp <- barplot(grupos, col=cols, main=\"Diagrama de Barras\", ylab=\"Frecuencia\", ylim=c(0,280))\ntext(bp, grupos+8, grupos, font=2)\npie(grupos, col=cols, main=\"Diagrama de Sectores\",\n    labels=paste(names(grupos),\"\\n\",grupos,\" (\",round(grupos/500*100,0),\"%)\",sep=\"\"))\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-8-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\nCada sector: $\\alpha_i = f_i \\times 360°$. Altura de barra $\\propto$ frecuencia. **Área** del sector $\\propto$ frecuencia.\n\n## Tablas — Variables ordinales (Frecuencia acumulada)\n\n**Efecto de terapia acuática en fibromialgia (n=500):**\n\n| Estado | $n_i$ | $N_i$ (acum.) | % | % acum. |\n|--------|:-----:|:------------:|:---:|:------:|\n| Mucho peor | 25 | 25 | 5.0 | 5.0 |\n| Peor | 98 | 123 | 19.6 | 24.6 |\n| Igual | 159 | 282 | 31.8 | 56.4 |\n| Mejor | 147 | 429 | 29.4 | 85.8 |\n| Mucho mejor | 71 | 500 | 14.2 | 100.0 |\n\n**Álgebra de frecuencias acumuladas:**\n\n$$N_i = \\sum_{j=1}^{i} n_j \\quad \\Rightarrow \\quad \\begin{cases} N_1 = n_1 \\\\ N_2 = n_1 + n_2 \\\\ \\cdots \\\\ N_k = \\sum_{j=1}^{k} n_j = n \\end{cases}$$\n\n**Frecuencia relativa acumulada:** $F_i = \\frac{N_i}{n} = \\sum_{j=1}^{i} f_j$, con $F_k = 1$.\n\n## Elementos del intervalo — Tablas para variables continuas\n\nSea una variable continua agrupada en $k$ intervalos. Para cada intervalo $j$ se definen:\n\n| Elemento | Símbolo | Definición |\n|:---------|:-------:|:-----------|\n| Límite inferior | $x_j^l$ | Valor mínimo del intervalo |\n| Límite superior | $x_j^u$ | Valor máximo del intervalo |\n| **Amplitud** | $\\Delta x_j$ | $\\Delta x_j = x_j^u - x_j^l$ |\n| **Marca de clase** | $x_j$ | $x_j = \\dfrac{x_j^l + x_j^u}{2}$ |\n\n**Requisitos de los intervalos:** (1) misma amplitud $\\Delta x$ (homogéneos), (2) exhaustivos (cubren todo el rango), (3) mutuamente excluyentes. Notación estándar: $(L_i, L_{i+1}]$.\n\n## Frecuencias y densidades para variables continuas\n\nPara cada intervalo $j$, las frecuencias y densidades se definen como:\n\n| Elemento | Símbolo | Definición |\n|:---------|:-------:|:-----------|\n| Frec. absoluta | $n_j$ | Observaciones en $[x_j^l, x_j^u)$ |\n| Frec. relativa | $f_j$ | $f_j = n_j / n$ |\n| **Densidad** | $\\hat{f}_j$ | $\\hat{f}_j = \\dfrac{f_j}{\\Delta x_j}$ |\n| Densidad absoluta | $\\hat{n}_j$ | $\\hat{n}_j = \\dfrac{n_j}{\\Delta x_j}$ |\n\n**Propiedad fundamental del histograma (el área ∝ frecuencia):**\n\n$$\\sum_{j=1}^{k} \\hat{f}_j \\cdot \\Delta x_j = \\sum_{j=1}^{k} \\frac{f_j}{\\Delta x_j} \\cdot \\Delta x_j = \\sum_{j=1}^{k} f_j = 1$$\n\n**Por tanto:** en el histograma la **altura** es densidad $\\hat{f}_j$, la **base** es $\\Delta x_j$, y el **área** de cada barra es $f_j$. La suma de todas las áreas es 1.\n\n\n## Tablas — Variables continuas e histograma\n\n# Visualización de Datos {.center}\n\n\n**Colesterol (mg/dL) en pacientes de fisioterapia, n=157:**\n\n| Intervalo | $n_i$ | $f_i$(%) | $F_i$(% acum) |\n|-----------|:-----:|:--------:|:------------:|\n| (101, 128] | 20 | 12.7 | 12.7 |\n| (128, 155] | 69 | 43.9 | 56.7 |\n| (155, 182] | 45 | 28.7 | 85.4 |\n| (182, 209] | 13 | 8.3 | 93.6 |\n| (209, 236] | 10 | 6.4 | 100.0 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123); colest <- rnorm(157, 168, 25)\nhist(colest, breaks=seq(101,236,by=13.5), col=\"steelblue\", border=\"white\",\n     main=\"Colesterol en Pacientes de Fisioterapia (n=157)\", xlab=\"mg/dL\", ylab=\"Frecuencia\")\nabline(v=mean(colest), col=\"darkgreen\", lwd=3, lty=2)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-9-1.png){width=864}\n:::\n:::\n\n\n## Guía visual: ¿qué gráfico uso?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2), mar=c(4,4,3,1))\n\n# 1 variable nominal → sectores\ngrupos <- c(A=150, B=75, AB=25, O=250)\npie(grupos, col=c(\"steelblue\",\"coral\",\"gold\",\"seagreen\"),\n    main=\"1 Variable Nominal\\n→ Diagrama de Sectores\")\nset.seed(123)\n\n# 1 variable ordinal/discreta → barras\nbarplot(c(25,98,159,147,71), names=c(\"M.Peor\",\"Peor\",\"Igual\",\"Mejor\",\"M.Mejor\"),\n        col=heat.colors(5), main=\"1 Variable Ordinal\\n→ Diagrama de Barras\", ylab=\"Frecuencia\")\n\n# 1 variable continua → histograma\nhist(rnorm(500,150,20), col=\"steelblue\", border=\"white\", breaks=20,\n     main=\"1 Variable Continua\\n→ Histograma\", xlab=\"ROM (grados)\", ylab=\"Frecuencia\")\n\n# 2 variables (continua vs categórica) → boxplot\nboxplot(rnorm(50,150,10)~rep(c(\"A\",\"B\"),each=25), col=c(\"steelblue\",\"coral\"),\n        main=\"1 Continua + 1 Categórica\\n→ Boxplot Comparativo\", ylab=\"ROM\")\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-10-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**Regla nemotécnica:** 1 variable → su gráfico natural. 2 variables → una en cada eje. ¿Ambas categóricas? → tabla de contingencia. ¿Ambas continuas? → diagrama de dispersión.\n\n## Tipos de gráficos y elección del intervalo\n\n| Tipo de variable | Gráfico adecuado |\n|:-----------------|:-----------------|\n| Nominal | Sectores, Barras |\n| Ordinal / Discreta (pocos) | Barras, Polígono frecuencias |\n| Continua / Discreta (muchos) | **Histograma** |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,2), mar=c(4,4,4,1))\nhist(colest, breaks=40, col=\"steelblue\", border=\"white\",\n     main=\"Demasiados intervalos → ruido\", xlab=\"mg/dL\")\nhist(colest, breaks=12, col=\"steelblue\", border=\"white\",\n     main=\"Intervalos adecuados → forma real\", xlab=\"mg/dL\")\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-11-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**Regla:** 8-15 intervalos. Demasiados → ruido. Muy pocos → pérdida de forma.\n\n## Polígono de frecuencias y diagrama de puntos\n\n**Polígono:** unir puntos medios superiores de barras → visualiza la forma.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedad<-c(15,16,17,18,19,20); freq<-c(5,28,64,18,6,3)\nplot(edad, freq, type=\"b\", pch=19, col=\"steelblue\", lwd=3, cex=2,\n     main=\"Polígono de Frecuencias: Edad (n=124)\", xlab=\"Edad\", ylab=\"Frecuencia\", ylim=c(0,70))\ngrid(col=\"grey80\"); rect(edad-0.3, 0, edad+0.3, freq, col=rgb(0,0,1,0.15), border=NA)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-12-1.png){width=864}\n:::\n:::\n\n\n**Diagrama de puntos** (dotplot): para muestras pequeñas donde el histograma no tiene sentido.\n\n## Diagrama de tallo y hojas\n\n::: {.callout-note}\n**Diagrama de tallo y hojas (stem-and-leaf):** Representación semigráfica que conserva los datos originales. Cada número se divide en **tallo** (cifras de mayor orden) y **hoja** (última cifra). Combina las ventajas de una tabla y un histograma.\n:::\n\n**Ejemplo — Fuerza de prensión manual (kg) en 20 pacientes:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(789)\nfuerza <- round(rnorm(20, mean = 30, sd = 6), 0)\ncat(\"Datos de fuerza (kg):\", sort(fuerza), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDatos de fuerza (kg): 16 24 24 25 25 26 26 27 27 28 28 29 29 30 31 31 33 33 34 36 \n```\n\n\n:::\n\n```{.r .cell-code}\nstem(fuerza)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  1 | 6\n  2 | 44\n  2 | 5566778899\n  3 | 011334\n  3 | 6\n```\n\n\n:::\n:::\n\n\n**Ventajas del diagrama de tallo y hojas:**\n\n- **Conserva los datos originales** (a diferencia del histograma que agrupa)\n- **Muestra la forma** de la distribución (simetría, asimetría, valores extremos)\n- **Útil para muestras pequeñas** ($n < 50$) donde el histograma pierde sentido\n- **Fácil de construir a mano** en el ámbito clínico\n\n::: {.callout-tip}\n**En fisioterapia:** Ideal para visualizar rápidamente la distribución de mediciones en un grupo pequeño de pacientes sin necesidad de software gráfico.\n:::\n\n## Pictogramas, nube de palabras y diagramas comparativos\n\n**Principios:** área ∝ frecuencia. Incluir $n$, unidades y año. Para comparar grupos, usar **frecuencia relativa (%)**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiagnosticos <- c(rep(\"Lumbalgia\",40), rep(\"Cervicalgia\",35), rep(\"Omalgia\",25),\n                  rep(\"Artrosis\",20), rep(\"Esguince\",18), rep(\"Tendinitis\",12))\nfreq_table <- sort(table(diagnosticos), decreasing=TRUE)\npar(mar=c(4,9,4,1))\nbarplot(as.numeric(freq_table), names=names(freq_table), horiz=TRUE, las=1,\n        col=colorRampPalette(c(\"steelblue\",\"coral\",\"gold\"))(6),\n        main=\"Diagnósticos en Fisioterapia (n=150)\", xlab=\"Frecuencia\", cex.names=0.85)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-14-1.png){width=864}\n:::\n:::\n\n\n## Nube de palabras — Términos estadísticos en fisioterapia\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Nube de palabras con términos estadísticos\nterminos <- c(\n  \"Media\",\"Mediana\",\"Moda\",\"Varianza\",\"Desviación\",\"Percentil\",\"Cuartil\",\n  \"Histograma\",\"Boxplot\",\"Dispersión\",\"Barras\",\"Sectores\",\"Frecuencia\",\n  \"Muestra\",\"Población\",\"Variable\",\"Continua\",\"Discreta\",\"Nominal\",\"Ordinal\",\n  \"Normal\",\"Asimetría\",\"Curtosis\",\"RIQ\",\"Coeficiente\",\"ECDF\",\"Densidad\",\n  \"Fisioterapia\",\"ROM\",\"EVA\",\"Diagnóstico\",\"Rehabilitación\",\"Dolor\",\n  \"Inferencia\",\"Estimación\",\"Contraste\",\"P-valor\",\"Significación\"\n)\nfreqs <- c(15,12,10,9,8,7,7,8,7,9,10,8,12,\n           14,14,13,11,10,11,10,\n           8,6,6,7,5,4,7,\n           5,4,5,6,5,5,\n           4,3,3,3,3)\nset.seed(123)\npar(mar=c(1,1,2,1))\nplot(NA, xlim=c(0,10), ylim=c(0,10), axes=F, xlab=\"\", ylab=\"\",\n     main=\"Términos Estadísticos en Fisioterapia Basada en la Evidencia\")\ncols <- colorRampPalette(c(\"#1a5276\",\"#2471a3\",\"#2e86c1\",\"#3498db\",\"#85c1e9\"))(length(terminos))\nfor(i in seq_along(terminos)){\n  text(runif(1,0.5,9.5), runif(1,0.5,9.5), terminos[i],\n       cex=freqs[i]/5, col=cols[i], font=sample(1:2,1))\n}\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-15-1.png){width=864}\n:::\n:::\n\n\n## Medidas de posición: Tipos\n\n# Medidas de Posición {.center}\n\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Tendencia central:** Media ($\\bar{x}$), Mediana ($Me$), Moda\n\n**No central:** Percentiles ($P_\\alpha$), Cuartiles ($Q_1,Q_2,Q_3$), Deciles\n:::\n::: {.column width=\"50%\"}\n**Qué medida según tipo de variable:**\n\n| Tipo | Medidas |\n|------|---------|\n| Nominal | Proporción, Moda |\n| Ordinal | + Mediana, Percentiles, RIQ |\n| Cuantitativa | + Media, Varianza, DT, CV |\n:::\n:::\n\n::: {.callout-important}\n¡No se puede calcular la **media** de una variable **nominal**!\n:::\n\n::: {.callout-tip}\n**Consejo para el estudiante:** Para recordar qué medida usar: ¿tipo de variable? Nominal → solo moda y %. Ordinal → añade mediana. Cuantitativa → añade media. ¿Hay outliers? → prefiere mediana y RIQ sobre media y DT.\n:::\n\n## Proporción, moda y mediana\n\n**Proporción:** $p_i = n_i/n$ — frecuencia relativa. Para nominales.\n\n**Moda:** valor con **mayor frecuencia** (puede no ser única). Única medida central para nominales.\n\n**Mediana ($Me$):** valor que divide la muestra ordenada en dos partes iguales.\n\n1. Ordenar datos: $x_{(1)} \\leq x_{(2)} \\leq \\cdots \\leq x_{(n)}$\n2. $n$ impar: $Me = x_{((n+1)/2)}$; $n$ par: $Me = (x_{(n/2)} + x_{(n/2+1)})/2$\n\n**Ejemplo ordinal:** {peor, peor, peor, mejor, igual, mejor, peor} → ordenar por gravedad → $Me$ = \"peor\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-c(3,6,7,10,15); cat(\"Me =\", median(x))  # 7\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMe = 7\n```\n\n\n:::\n\n```{.r .cell-code}\nx2<-c(3,6,10,15); cat(\"Me =\", median(x2))  # 8\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMe = 8\n```\n\n\n:::\n:::\n\n\n## Media aritmética\n\n::: {.framed}\n$$\\bar{x} = \\frac{1}{n}\\sum_{i=1}^{n} x_i$$\n:::\n\n**Para datos agrupados (tabla de frecuencias):** $\\bar{x} = \\frac{\\sum x_i \\cdot n_i}{n}$\n\n**Para intervalos:** usar la **marca de clase** $x_j = (x_j^l + x_j^u)/2$\n\n**Ejemplo — Edad (n=124):**\n\n| $x_i$ | $n_i$ | $x_i \\cdot n_i$ |\n|:-----:|:-----:|:---------------:|\n| 15 | 5 | 75 |\n| 16 | 28 | 448 |\n| 17 | 64 | 1088 |\n| 18 | 18 | 324 |\n| 19 | 6 | 114 |\n| 20 | 3 | 60 |\n| **Σ** | **124** | **2109** |\n\n$\\bar{x} = 2109/124 = 17.0$ años\n\n## Media ponderada\n\n$$\\bar{x}_p = \\frac{\\sum x_i \\cdot w_i}{\\sum w_i}$$\n\n**Ejemplo — Nota media:** 5 (3 créditos), 7 (3 créd), 9 (6 créd).\n\n$\\bar{x}_p = \\frac{5\\times3 + 7\\times3 + 9\\times6}{12} = 7.5 \\; \\neq \\; \\frac{5+7+9}{3} = 7.0$\n\n## Respiro visual — Midiendo en fisioterapia\n\n![Goniometría de rodilla](https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800)\n\nLas medidas de posición resumen **dónde se concentran** los datos. La media es sensible a valores extremos; la mediana es robusta.\n\n## Media geométrica y media armónica — Fórmulas\n\n::: {.formula-box}\n**Media Geométrica:** $G = \\left(\\prod_{i=1}^n x_i\\right)^{1/n} = \\exp\\left(\\frac{1}{n}\\sum \\ln x_i\\right)$\n\n**Media Armónica:** $H = \\frac{n}{\\sum_{i=1}^n \\frac{1}{x_i}}$\n:::\n\n**¿Cuándo usar cada una en fisioterapia?**\n\n- **Geométrica:** Para promediar tasas, ratios, o índices multiplicativos (ej: factor de mejora relativa entre sesiones)\n- **Armónica:** Para promediar tasas o velocidades (ej: velocidad media de marcha en ida y vuelta)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Factores de mejora: 1.2, 1.5, 1.8, 1.3, 1.6\nmejoras <- c(1.2, 1.5, 1.8, 1.3, 1.6)\nG <- exp(mean(log(mejoras)))\ncat(\"Media geométrica =\", round(G, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedia geométrica = 1.465\n```\n\n\n:::\n\n```{.r .cell-code}\n# Velocidades de marcha (m/s): ida=1.2, vuelta=0.8\nv <- c(1.2, 0.8)\nH <- length(v) / sum(1/v)\ncat(\"\\nMedia armónica =\", round(H, 3), \"m/s\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMedia armónica = 0.96 m/s\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nMedia aritmética =\", round(mean(v), 3), \"m/s (sobreestima!)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMedia aritmética = 1 m/s (sobreestima!)\n```\n\n\n:::\n:::\n\n\n## Media geométrica y media armónica\n\n::: {.callout-note}\n**Media Geométrica ($G$):** Adecuada para datos que siguen un crecimiento multiplicativo (proporciones, ratios, tasas de cambio). Se define como:\n\n$$G = \\left(\\prod_{i=1}^{n} x_i\\right)^{1/n} = \\exp\\left(\\frac{1}{n}\\sum_{i=1}^{n} \\ln x_i\\right)$$\n\n**Media Armónica ($H$):** Adecuada para promediar tasas, velocidades y ratios inversos:\n\n$$H = \\frac{n}{\\sum_{i=1}^{n} \\frac{1}{x_i}}$$\n:::\n\n**Relación fundamental:** Para datos positivos siempre se cumple $H \\leq G \\leq \\bar{x}$.\n\n| Media | Cuándo usar en Fisioterapia | Ejemplo |\n|:------|:---------------------------|:--------|\n| **Aritmética** ($\\bar{x}$) | Variables aditivas | ROM, fuerza, distancia |\n| **Geométrica** ($G$) | Ratios, cocientes pre/post, índices multiplicativos | Ratio de mejoría (ROM post / ROM pre) |\n| **Armónica** ($H$) | Velocidades, tasas, frecuencias | Velocidad de marcha en diferentes tramos |\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ejemplo: ratios de mejoría pre/post en 5 pacientes\nratios <- c(1.2, 1.5, 1.1, 1.8, 1.3)  # ROM_post / ROM_pre\n\nmedia_arit <- mean(ratios)\nmedia_geom <- exp(mean(log(ratios)))\nmedia_armo <- 1 / mean(1 / ratios)\n\ncat(\"Ratios de mejoría:\", ratios,\n    \"\\n\\nMedia aritmética  =\", round(media_arit, 3),\n    \"\\nMedia geométrica  =\", round(media_geom, 3),\n    \"\\nMedia armónica    =\", round(media_armo, 3),\n    \"\\n\\nSe cumple H ≤ G ≤ x̄:\", media_armo <= media_geom & media_geom <= media_arit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRatios de mejoría: 1.2 1.5 1.1 1.8 1.3 \n\nMedia aritmética  = 1.38 \nMedia geométrica  = 1.359 \nMedia armónica    = 1.339 \n\nSe cumple H ≤ G ≤ x̄: TRUE\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n**En fisioterapia:** Cuando comparas la **mejoría relativa** de varios pacientes (ej: \"el ROM mejoró un 20%, 50%, 10%...\"), la media geométrica es más apropiada que la aritmética. La aritmética sobrestima el promedio de cambios multiplicativos.\n:::\n\n## Mediana vs media y simetría — Regla para identificar asimetría\n\n::: {.callout-important}\n**Regla nemotécnica (rule of thumb):** La posición relativa de media, mediana y moda revela la asimetría.\n:::\n\n::: {.columns}\n::: {.column width=\"33%\"}\n**Simétrica**\n$$\\bar{x} \\approx Me \\approx Mo$$\nLas tres coinciden en el centro\n:::\n::: {.column width=\"33%\"}\n**Asim. derecha (+)**\n$$Mo < Me < \\bar{x}$$\nLa media es arrastrada por la cola larga a la derecha\n:::\n::: {.column width=\"33%\"}\n**Asim. izquierda (−)**\n$$\\bar{x} < Me < Mo$$\nLa media es arrastrada por la cola larga a la izquierda\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,3), mar=c(3,4,4,1))\nset.seed(123)\n\n# ── Simétrica ──\nx_sym <- rnorm(5000, 10, 1.5)\nhist(x_sym, col=\"steelblue\", border=\"white\", breaks=30, freq=FALSE,\n     main=\"Simétrica\", xlab=\"\", ylab=\"\", yaxt=\"n\", cex.main=1.3)\ndx <- density(x_sym); lines(dx, col=\"darkgreen\", lwd=2.5)\nabline(v=mean(x_sym), col=\"darkgreen\", lwd=3)       # media = rojo\nabline(v=median(x_sym), col=\"#2471a3\", lwd=3, lty=2) # mediana = azul\nlegend(\"topright\", c(paste0(\"x̄=\", round(mean(x_sym),1)),\n       paste0(\"Me=\", round(median(x_sym),1))),\n       col=c(\"darkgreen\",\"#2471a3\"), lty=c(1,2), lwd=3, bty=\"n\", cex=0.85)\ntext(9.5, max(dx$y)*0.85, \"x̄ ≈ Me ≈ Mo\", col=\"darkgreen\", font=2, cex=0.9)\n\n# ── Asimétrica derecha ──\nx_pos <- rexp(5000, 0.5)\nhist(x_pos, col=\"seagreen\", border=\"white\", breaks=30, freq=FALSE,\n     main=\"Asim. derecha (+)\", xlab=\"\", ylab=\"\", yaxt=\"n\", cex.main=1.3)\ndx <- density(x_pos); lines(dx, col=\"darkgreen\", lwd=2.5)\nabline(v=mean(x_pos), col=\"darkgreen\", lwd=3)\nabline(v=median(x_pos), col=\"#2471a3\", lwd=3, lty=2)\nlegend(\"topright\", c(paste0(\"x̄=\", round(mean(x_pos),1)),\n       paste0(\"Me=\", round(median(x_pos),1))),\n       col=c(\"darkgreen\",\"#2471a3\"), lty=c(1,2), lwd=3, bty=\"n\", cex=0.85)\ntext(8, max(dx$y)*0.85, \"Mo < Me < x̄\", col=\"darkgreen\", font=2, cex=0.9)\n\n# ── Asimétrica izquierda ──\nx_neg <- 12 - rexp(5000, 0.5)\nhist(x_neg, col=\"seagreen\", border=\"white\", breaks=30, freq=FALSE,\n     main=\"Asim. izquierda (−)\", xlab=\"\", ylab=\"\", yaxt=\"n\", cex.main=1.3)\ndx <- density(x_neg); lines(dx, col=\"darkgreen\", lwd=2.5)\nabline(v=mean(x_neg), col=\"darkgreen\", lwd=3)\nabline(v=median(x_neg), col=\"#2471a3\", lwd=3, lty=2)\nlegend(\"topleft\", c(paste0(\"x̄=\", round(mean(x_neg),1)),\n       paste0(\"Me=\", round(median(x_neg),1))),\n       col=c(\"darkgreen\",\"#2471a3\"), lty=c(1,2), lwd=3, bty=\"n\", cex=0.85)\ntext(5, max(dx$y)*0.85, \"x̄ < Me < Mo\", col=\"darkgreen\", font=2, cex=0.9)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-19-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n::: {.callout-tip}\n**Cómo usarlo en fisioterapia:** Si en tu muestra la media de EVA-dolor es 6.2 y la mediana es 4.5, tienes una asimetría derecha: la mayoría de pacientes tiene dolor moderado-bajo, pero unos pocos con dolor muy alto empujan la media hacia arriba. En este caso, **reporta la mediana**.\n:::\n\n## ¿Media o Mediana? — El Efecto de los Valores Extremos\n\n::: {.callout-tip}\n**Piensa antes de mirar:** Tienes 30 pacientes con fuerza prensil entre 24-38 kg. Uno adicional registra 65 kg. ¿La media cambiará mucho? ¿Y la mediana? ¿Cuál reportarías en tu artículo? → **Mira los gráficos de abajo para comprobarlo.**\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\npar(mfrow=c(1,2), mar=c(4,4,4,1))\n\n# Sin outlier\nx1 <- rnorm(30, 30, 5)\nhist(x1, col=\"steelblue\", border=\"white\", breaks=12, freq=FALSE,\n     main=\"Sin outliers: media ~ mediana\", xlab=\"Fuerza (kg)\", xlim=c(15,65))\nabline(v=mean(x1), col=\"darkgreen\", lwd=3)\nabline(v=median(x1), col=\"blue\", lwd=3, lty=2)\ncurve(dnorm(x,mean(x1),sd(x1)), add=T, col=\"grey40\", lwd=1, lty=3)\nlegend(\"topright\", c(paste(\"Media =\",round(mean(x1),1)),\n       paste(\"Mediana =\",round(median(x1),1))), col=c(\"darkgreen\",\"blue\"),\n       lty=c(1,2), lwd=3, bty=\"n\", cex=0.9)\n\n# Con outlier\nx2 <- c(x1, 65)  # paciente con fuerza excepcional\nhist(x2, col=\"seagreen\", border=\"white\", breaks=12, freq=FALSE,\n     main=\"Con outlier: media se desplaza\", xlab=\"Fuerza (kg)\", xlim=c(15,65))\nabline(v=mean(x2), col=\"darkgreen\", lwd=3)\nabline(v=median(x2), col=\"blue\", lwd=3, lty=2)\nlegend(\"topright\", c(paste(\"Media =\",round(mean(x2),1)),\n       paste(\"Mediana =\",round(median(x2),1))), col=c(\"darkgreen\",\"blue\"),\n       lty=c(1,2), lwd=3, bty=\"n\", cex=0.9)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-20-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n::: {.callout-tip}\n**Consejo:** Ante datos con valores extremos (outliers), **prefiere la mediana** sobre la media. La mediana apenas cambia. La media se ve muy afectada. En fisioterapia, un paciente con dolor excepcionalmente alto no debe distorsionar la descripción del grupo.\n:::\n\n## Percentiles y cuantiles\n\n**Percentil $\\alpha$:** valor que deja $\\alpha$% de observaciones por debajo. Posición = $(n+1)\\alpha/100$.\n\n**Cuartiles:** $Q_1=P_{25}$, $Q_2=P_{50}=Me$, $Q_3=P_{75}$. **Deciles:** $D_k = P_{10k}$.\n\n**Ejemplo — $P_{40}$ (nº recaídas, n=500):**\n\n| $x_i$ | $n_i$ | $N_i$ | % acum |\n|:-----:|:-----:|:-----:|:------:|\n| 0 | 72 | 72 | 14.4 |\n| 1 | 155 | 227 | 45.4 |\n| 2 | 97 | 324 | 64.8 |\n\nPosición $P_{40}$ = $(500+1) \\times 0.4 = 200.4$ → $P_{40} = 1$ recaída\n\n## Mediana desde tabla agrupada — Interpolación\n\n**Flexión de rodilla (°), n=60:**\n\n| Intervalo | $x_j$ | $n_i$ | $N_i$ |\n|:---------:|:-----:|:-----:|:-----:|\n| 110–120 | 115 | 5 | 5 |\n| 120–130 | 125 | 15 | 20 |\n| **130–140** | **135** | **25** | **45** ← contiene Me |\n| 140–150 | 145 | 10 | 55 |\n| 150–160 | 155 | 5 | 60 |\n\n$$Me = L_{i-1} + \\frac{n/2 - N_{i-1}}{n_i} \\cdot a = 130 + \\frac{30-20}{25} \\times 10 = 134°$$\n\n## Ejercicio rápido — Cuartiles\n\n**Calcula $Q_1$, $Q_2$, $Q_3$ para:** 3, 5, 7, 8, 12, 15, 18, 21\n\n## Diagrama de cajas (Boxplot)\n\n# Medidas de Dispersión y Forma {.center}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ng1<-rnorm(50,170,10); g2<-rnorm(50,180,15)\nboxplot(g1,g2,names=c(\"Grupo 1\",\"Grupo 2\"),col=c(\"steelblue\",\"coral\"),\n        main=\"Comparación de Estatura (cm)\",ylab=\"cm\",xlab=\"Grupo\")\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-21-1.png){width=864}\n:::\n:::\n\n\n**Caja:** $Q_1$ a $Q_3$ (50% central). **Línea:** $Me$. **Bigotes:** $1.5 \\times RIQ$. **Puntos:** outliers.\n\n## ¿Por Qué Medir la Dispersión?\n\nDos grupos pueden tener la **misma media** pero dispersión muy diferente. La media sola no describe la distribución.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123); n<-10000; mu<-90\ngrpA<-rnorm(n,mu,5); grpB<-rnorm(n,mu,18)\nplot(density(grpA,adjust=1.5),col=\"steelblue\",lwd=4,xlim=c(30,150),\n     main=expression(paste(\"Misma \",mu,\"=90°, distinta \",sigma)),xlab=\"Flexión rodilla (°)\")\nlines(density(grpB,adjust=1.5),col=\"seagreen\",lwd=4); abline(v=mu,lty=2,lwd=2)\narrows(mu-10,0.01,mu+10,0.01,col=\"steelblue\",lwd=3,code=3,angle=90,length=0.12)\narrows(mu-36,0.005,mu+36,0.005,col=\"seagreen\",lwd=3,code=3,angle=90,length=0.12)\nlegend(\"topright\",c(expression(sigma==5),expression(sigma==18)),col=c(\"steelblue\",\"seagreen\"),lwd=4,bty=\"n\",cex=1.3)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-22-1.png){width=864}\n:::\n:::\n\n\n**Grupo A:** $s=5°$, $s^2=25$. **Grupo B:** $s=18°$, $s^2=324$. Misma media, **variabilidad 13 veces mayor**.\n\n## Rango, varianza y desviación típica\n\n**Rango:** $A = x_{\\max} - x_{\\min}$. Simple pero muy pobre (solo usa 2 valores).\n\n::: {.framed}\n**Varianza muestral:** $s^2 = \\frac{\\sum_{i=1}^{n} (x_i - \\bar{x})^2}{n-1}$\n\n**Desviación típica:** $s = \\sqrt{s^2}$ (mismas unidades que la variable)\n:::\n\n**Fórmula abreviada:** $s^2 = \\frac{1}{n-1}\\left[\\sum x_i^2 - \\frac{(\\sum x_i)^2}{n}\\right]$\n\n**¿Por qué $n-1$?** Usamos $n-1$ porque al estimar $\\bar{x}$ a partir de los mismos datos, \"gastamos\" un grado de libertad. Esto garantiza que $s^2$ sea un estimador **insesgado** de $\\sigma^2$.\n\n## Varianza — Cálculo paso a paso\n\n**Flexión de rodilla (°) en 5 pacientes:** 125, 132, 128, 135, 130. $\\bar{x}=130°$.\n\n| $x_i$ | $x_i-\\bar{x}$ | $(x_i-\\bar{x})^2$ |\n|:-----:|:------------:|:-----------------:|\n| 125 | −5 | 25 |\n| 132 | +2 | 4 |\n| 128 | −2 | 4 |\n| 135 | +5 | 25 |\n| 130 | 0 | 0 |\n| **Σ** | **0** | **58** |\n\n$$s^2 = \\frac{58}{4} = 14.5 \\text{ grados}^2 \\qquad s = \\sqrt{14.5} = 3.81°$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-c(125,132,128,135,130); cat(\"s2 =\", var(x), \"s =\", round(sd(x),2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ns2 = 14.5 s = 3.81\n```\n\n\n:::\n:::\n\n\n## Interpretación de la desviación típica\n\nSe expresa $\\bar{x} \\pm s$. Si la distribución es simétrica (≈Normal):\n\n- $\\bar{x} \\pm s$ contiene ≈ 68%\n- $\\bar{x} \\pm 2s$ contiene ≈ 95%\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dnorm(x), -4, 4, lwd=3, col=\"steelblue\", main=expression(bar(x) %+-% 2*s))\nx1<-seq(-2,2,0.01); polygon(c(x1,rev(x1)),c(dnorm(x1),rep(0,length(x1))),col=rgb(0,0,1,0.2),border=NA)\nx2<-seq(-1,1,0.01); polygon(c(x2,rev(x2)),c(dnorm(x2),rep(0,length(x2))),col=rgb(0,0,1,0.15),border=NA)\ntext(0,0.2,\"~68%\",cex=1); text(0,0.05,\"~95%\",cex=1)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-24-1.png){width=864}\n:::\n:::\n\n\n## Álgebra de Estadísticos desde Tablas Agrupadas\n\nCuando los datos están agrupados en $k$ intervalos, las fórmulas de la media y la varianza se adaptan usando la **marca de clase** $x_j$ como representante del intervalo:\n\n::: {.framed}\n**Media desde tabla agrupada:**\n$$\\bar{x} = \\frac{1}{n}\\sum_{j=1}^{k} x_j \\cdot n_j = \\sum_{j=1}^{k} x_j \\cdot f_j$$\n\n**Varianza desde tabla agrupada (fórmula abreviada de cálculo):**\n$$s^2 = \\frac{1}{n-1}\\left[ \\sum_{j=1}^{k} x_j^2 \\cdot n_j - \\frac{\\left( \\sum_{j=1}^{k} x_j \\cdot n_j \\right)^2}{n} \\right]$$\n:::\n\n**Relación con las fórmulas para datos sin agrupar:**\n\n- $\\sum x_i$ se sustituye por $\\sum x_j \\cdot n_j$ (cada marca de clase multiplicada por su frecuencia)\n- $\\sum x_i^2$ se sustituye por $\\sum x_j^2 \\cdot n_j$\n- El resultado es una **aproximación**: asume que todas las observaciones del intervalo se concentran en $x_j$\n\n## Ejemplo detallado — Media y varianza con datos agrupados\n\n**Flexión de rodilla (grados) en 60 pacientes de fisioterapia:**\n\n| Intervalo | Marca de clase ($x_j$) | $n_j$ | $x_j \\cdot n_j$ | $x_j^2 \\cdot n_j$ |\n|:---------:|:---------------------:|:-----:|:--------------:|:-----------------:|\n| 110-120 | 115 | 5 | 575 | 66,125 |\n| 120-130 | 125 | 15 | 1,875 | 234,375 |\n| 130-140 | 135 | 25 | 3,375 | 455,625 |\n| 140-150 | 145 | 10 | 1,450 | 210,250 |\n| 150-160 | 155 | 5 | 775 | 120,125 |\n| **Total** | | **60** | **8,050** | **1,086,500** |\n\n$$\\bar{x} = \\frac{\\sum x_j \\cdot n_j}{n} = \\frac{8050}{60} = 134.2°$$\n\n$$s^2 = \\frac{1}{n-1}\\left[\\sum x_j^2 n_j - \\frac{(\\sum x_j n_j)^2}{n}\\right] = \\frac{1}{59}\\left[1,086,500 - \\frac{8,050^2}{60}\\right] = \\frac{6,458}{59} = 109.5$$\n\n$$s = \\sqrt{109.5} = 10.5°$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(rep(115,5), rep(125,15), rep(135,25), rep(145,10), rep(155,5))\ncat(\"Media =\", mean(x), \"grados | s =\", round(sd(x),1), \"grados | s2 =\", round(var(x),1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedia = 134.1667 grados | s = 10.5 grados | s2 = 109.5\n```\n\n\n:::\n:::\n\n\n**Nota:** La media con datos agrupados (134.2°) es una aproximación. Asume que todas las observaciones se concentran en la marca de clase.\n\n## Coeficiente de variación (CV) y rango intercuartílico (RIQ)\n\n**CV — Definición clínica:** mide la **dispersión relativa** respecto a la media. Es adimensional (sin unidades), lo que permite comparar la variabilidad entre variables medidas en escalas completamente distintas.\n\n$$CV = \\frac{s}{\\bar{x}} \\times 100\\%$$\n\n**Usos clínicos del CV:**\n\n- **Precisión diagnóstica:** comparar la fiabilidad de distintos métodos de medición (goniometría digital vs manual vs visual)\n- **Variabilidad biológica:** comparar la dispersión de variables con unidades distintas (ej: ¿qué varía más en una población, la fuerza muscular o el ROM?)\n- **Control de calidad:** monitorizar la consistencia de mediciones repetidas en un servicio de fisioterapia (CV < 5% → excelente; 5-10% → aceptable; > 10% → revisar protocolo)\n\n| Método medición ROM | $\\bar{x}$ | $s$ | CV | Interpretación |\n|:--------------------|:--------:|:---:|:---:|:--------------|\n| Goniometría digital | 150° | 3° | 2.0% | Excelente — gold standard |\n| Goniometría manual | 148° | 7.5° | 5.1% | Aceptable — práctica clínica |\n| Estimación visual | 145° | 14.5° | 10.0% | Poco preciso — no usar solo |\n\n**RIQ — Rango Intercuartílico:** $RIQ = Q_3 - Q_1$. Contiene el 50% central de los datos. Robusto frente a outliers; es el acompañante natural de la mediana.\n\n**Desviación cuartil:** $DQ = RIQ/2$ — mide la dispersión alrededor de la mediana.\n\n## Asimetría y curtosis\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**Asimetría (skewness) — $g_1$:** mide la **falta de simetría** de la distribución.\n\n$$g_1 = \\frac{\\frac{1}{n}\\sum(x_i-\\bar{x})^3}{s^3}$$\n\n| $g_1$ | Forma | Ejemplo en Fisioterapia |\n|:-----:|:------|:------------------------|\n| $\\approx 0$ | Simétrica | ROM de cadera en población sana |\n| $> 0$ | Cola a la **derecha** (+) | Días hasta el alta (la mayoría temprano, pocos tardan mucho) |\n| $< 0$ | Cola a la **izquierda** (−) | Fuerza en pacientes con lesión (la mayoría baja, pocos alta) |\n\n**Interpretación clínica:** si $g_1 > 0$, la media $>$ mediana (arrastrada por valores altos). Si $g_1 < 0$, media $<$ mediana.\n\n:::\n::: {.column width=\"50%\"}\n\n**Curtosis (kurtosis) — $g_2$:** mide el **apuntamiento** y el peso de las colas.\n\n$$g_2 = \\frac{\\frac{1}{n}\\sum(x_i-\\bar{x})^4}{s^4}$$\n\n| Exc. $g_2-3$ | Nombre | Significado clínico |\n|:------------:|:-------|:--------------------|\n| $\\approx 0$ | **Mesocúrtica** | Distribución Normal de referencia |\n| $> 0$ | **Leptocúrtica** | Colas pesadas → más valores extremos de lo esperado (ej: dolor crónico: la mayoría moderado pero algunos muy extremos) |\n| $< 0$ | **Platicúrtica** | Colas ligeras → pocos valores extremos (ej: ROM en muestra muy homogénea) |\n\n*Nota: $g_2$ es la curtosis; el exceso de curtosis (excess kurtosis) es $g_2 - 3$.*\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,2), mar=c(4,4,3,1))\n# Asimetría\nset.seed(123)\nx_sym <- rnorm(1000, 90, 15)\nx_pos <- rexp(1000, 1/10)\nx_neg <- -rexp(1000, 1/8) + 40\nplot(density(x_sym), col=\"steelblue\", lwd=3, main=\"Asimetría\", xlab=\"x\", ylab=\"Densidad\", ylim=c(0,0.045))\nlines(density(x_pos), col=\"seagreen\", lwd=3)\nlines(density(x_neg), col=\"coral\", lwd=3)\nlegend(\"topright\", c(\"Simétrica\",\"Positiva\",\"Negativa\"), col=c(\"steelblue\",\"seagreen\",\"coral\"), lwd=3, bty=\"n\", cex=0.8)\n\n# Curtosis\ndx<-density(rt(100000,4),adjust=1.5,from=-5,to=5)\ndy<-density(rnorm(100000),adjust=1.5,from=-5,to=5)\ndz<-density(runif(100000,-2,2),adjust=1.5,from=-5,to=5)\nplot(dx,col=\"coral\",lwd=3,ylim=c(0,max(dx$y,dy$y,dz$y)*1.1),\n     main=\"Curtosis (apuntamiento)\",xlab=\"x\",ylab=\"Densidad\")\nlines(dy,col=\"steelblue\",lwd=3); lines(dz,col=\"seagreen\",lwd=3)\nlegend(\"topright\",c(\"Leptocúrtica\",\"Mesocúrtica\",\"Platicúrtica\"),\n       col=c(\"coral\",\"steelblue\",\"seagreen\"),lwd=3,bty=\"n\",cex=0.8)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-26-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n## Ecdf — Función de distribución empírica\n\n::: {.callout-note}\n**ECDF (Empirical Cumulative Distribution Function):** describe la proporción de datos $\\leq$ cada valor observado. Es el equivalente muestral de la función de distribución $F(x) = P(X \\leq x)$.\n:::\n\n$$F_n(x) = \\frac{1}{n}\\sum_{i=1}^{n} \\mathbb{1}_{\\{x_i \\leq x\\}} = \\begin{cases} 0 & x < x_{(1)} \\\\ i/n & x_{(i)} \\leq x < x_{(i+1)} \\\\ 1 & x \\geq x_{(n)} \\end{cases}$$\n\n\ndonde $\\mathbb{1}_{\\{x_i \\leq x\\}}$ vale 1 si $x_i \\leq x$ y 0 en caso contrario.\n\n**Utilidad clínica de la ECDF:**\n\n- **Percentiles visuales:** leer directamente cualquier percentil del gráfico (ej: $P_{50}$ ≈ 124 mmHg)\n- **Comparar grupos:** superponer ECDF de dos grupos (ej: tratados vs control) para ver si uno estocásticamente domina al otro\n- **Normalidad:** comparar la ECDF con la curva de la Normal teórica (test de Kolmogorov-Smirnov)\n- **Sin pérdida de información:** a diferencia del histograma (que agrupa), la ECDF muestra cada dato\n\n\n::: {.cell}\n\n```{.r .cell-code}\npas<-c(120,125,118,130,122,128,115,135,124,129)\nplot(ecdf(pas), main=\"ECDF: Presión Arterial Sistólica (n=10)\",\n     xlab=\"PAS (mmHg)\", ylab=\"F(x) — Proporción acumulada\",\n     col=\"darkblue\", verticals=TRUE, pch=16, lwd=2.5, cex.main=1.1)\ngrid(col=\"grey80\")\n# Añadir percentiles clave\nabline(h=c(0.25,0.5,0.75), col=c(\"darkgreen\",\"coral\",\"darkgreen\"), lty=3, lwd=1.5)\ntext(138, 0.52, \"Me = 124\", col=\"coral\", cex=0.8, font=2)\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-27-1.png){width=864}\n:::\n:::\n\n\n## Estadística descriptiva con R — Cálculo manual\n\n# Aplicación Práctica {.center}\n\n\n**Ejemplo: flexión de rodilla (°) en 8 pacientes:**\n125, 132, 128, 135, 130, 126, 131, 129\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(125, 132, 128, 135, 130, 126, 131, 129)\n\n# ── Medidas de posición ──\ncat(\"n           =\", length(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn           = 8\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nMedia       =\", round(mean(x), 2), \"°\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMedia       = 129.5 °\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nMediana     =\", median(x), \"°\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMediana     = 129.5 °\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nMínimo      =\", min(x), \"°\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMínimo      = 125 °\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nMáximo      =\", max(x), \"°\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMáximo      = 135 °\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nQ1          =\", quantile(x, 0.25), \"°\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nQ1          = 127.5 °\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nQ3          =\", quantile(x, 0.75), \"°\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nQ3          = 131.25 °\n```\n\n\n:::\n\n```{.r .cell-code}\n# ── Medidas de dispersión ──\ncat(\"\\n\\nVarianza    =\", round(var(x), 2), \"grados²\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\nVarianza    = 10.57 grados²\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nDesv. típica =\", round(sd(x), 2), \"°\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDesv. típica = 3.25 °\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nRIQ         =\", IQR(x), \"°\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRIQ         = 3.75 °\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCV (%)      =\", round(sd(x)/mean(x)*100, 1), \"%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCV (%)      = 2.5 %\n```\n\n\n:::\n\n```{.r .cell-code}\n# ── Forma (con fallback si e1071 no disponible) ──\nif (has_e1071) {\n  cat(\"\\n\\nAsimetría   =\", round(e1071::skewness(x), 3))\n  cat(\"\\nCurtosis    =\", round(e1071::kurtosis(x), 3))\n} else {\n  cat(\"\\n\\nAsimetría   =\", round(skewness(x), 3))\n  cat(\"\\nCurtosis    =\", round(kurtosis(x), 3))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\nAsimetría   = 0.175\nCurtosis    = -1.295\n```\n\n\n:::\n\n```{.r .cell-code}\n# ── Normalidad ──\ncat(\"\\n\\nShapiro-Wilk: W =\", round(shapiro.test(x)$statistic, 3),\n    \", P =\", round(shapiro.test(x)$p.value, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\nShapiro-Wilk: W = 0.983 , P = 0.9774\n```\n\n\n:::\n:::\n\n\n**Interpretación de la salida:** $n=8$, $\\bar{x}=129.5°$, $s=3.2°$, $Me=129.5°$, $CV=2.5\\%$ (muy homogéneo), $RIQ=4.5°$, asimetría $\\approx 0$ (simétrica), Shapiro-Wilk $P > 0.05$ (compatible con normalidad).\n\n## R base vs BioEstatR — Resumen de funciones\n\n| Tarea | R Base | BioEstatR |\n|-------|--------|-----------|\n| Todos los estadísticos | `mean()`, `sd()`, `median()`, `IQR()`, etc. | `freq(x)` |\n| Tabla de frecuencias | `table(x)`; `prop.table(table(x))` | `freq(x)` |\n| Tabla agrupada en $k$ intervalos | `cut(x, breaks=k)` + `table()` | `freq(x, cuts=k)` |\n| Gráficos por grupo | `boxplot(y ~ g)` | `grps(x = y, f = g)` |\n| Test de normalidad + Q-Q plot | `shapiro.test(x)`; `qqnorm(x)` | `normal(x)` |\n| Resumen de 5 números | `summary(x)` | `freq(x)` |\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ── BioEstatR (atajos) ──\nif (has_bioestatr) {\n  library(BioEstatR)\n  freq(x)               # todo en uno: n, media, DE, CV, Me, Q1, Q3, min, max, asimetría, curtosis, Shapiro-Wilk\n  freq(x, cuts=5)       # igual pero agrupando en 5 intervalos\n  # table(x)            # tabla de frecuencias con porcentajes (función BioEstatR)\n  grps(x = y, f = grupo)       # boxplots + resumen por grupo\n  normal(x)             # Shapiro-Wilk + histograma + Q-Q plot\n}\n\n# ── R base (equivalente completo) ──\nmean(x); sd(x); median(x); IQR(x); quantile(x, c(0.25, 0.75))\nshapiro.test(x)\nboxplot(y ~ grupo)\nhist(x, freq=FALSE); lines(density(x), col=\"steelblue\", lwd=2)\n```\n:::\n\n\n## BioEstatR en acción — Ejemplo completo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(456)\nrom_ejemplo <- round(rnorm(40, mean = 108, sd = 14), 1)\n\nif (has_bioestatr) {\n  # Si BioEstatR está disponible, usar sus funciones\n  cat(\"=== Usando BioEstatR ===\\n\")\n  freq(rom_ejemplo)\n} else {\n  # Fallback completo con R base\n  cat(\"=== R Base (BioEstatR no disponible) ===\\n\")\n  cat(\"n =\", length(rom_ejemplo),\n      \"| Media =\", round(mean(rom_ejemplo), 1),\n      \"| DT =\", round(sd(rom_ejemplo), 1),\n      \"\\nMediana =\", round(median(rom_ejemplo), 1),\n      \"| Q1 =\", round(quantile(rom_ejemplo, 0.25), 1),\n      \"| Q3 =\", round(quantile(rom_ejemplo, 0.75), 1),\n      \"\\nRIQ =\", round(IQR(rom_ejemplo), 1),\n      \"| CV =\", round(sd(rom_ejemplo)/mean(rom_ejemplo)*100, 1), \"%\",\n      \"\\nMín =\", min(rom_ejemplo),\n      \"| Máx =\", max(rom_ejemplo))\n  sw <- shapiro.test(rom_ejemplo)\n  cat(\"\\nShapiro-Wilk: W =\", round(sw$statistic, 3),\n      \" P =\", round(sw$p.value, 4), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Usando BioEstatR ===\n\nDistribución de frecuencias\n--------------------------------\nVariable:  rom_ejemplo \nn = 40 \n \n          x Freq  Prop Prop.Acum\n1   (80,90]    5 0.125     0.125\n2  (90,100]    5 0.125     0.250\n3 (100,110]   10 0.250     0.500\n4 (110,120]    8 0.200     0.700\n5 (120,130]    6 0.150     0.850\n6 (130,140]    5 0.125     0.975\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-30-1.png){width=864}\n:::\n:::\n\n\n## Ejercicio clínico — Análisis descriptivo completo\n\nUn fisioterapeuta mide el rango de movimiento (ROM, en grados) de rodilla en 40 pacientes tras una artroplastia total de rodilla.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(456)\nrom_rodilla <- round(rnorm(40, mean = 108, sd = 14), 1)\nrom_rodilla\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  89.2 116.7 119.2  88.6  98.0 103.5 117.7 111.5 122.1 116.0  95.2 126.4\n[13] 121.8 131.2  87.8 135.3 132.3 113.4 139.9 129.5 101.4  84.0  88.0 110.9\n[25] 107.5 123.9 101.5 103.4 128.8  92.7 100.6  99.7  80.0 112.1 110.4 133.4\n[37]  98.8 106.0 102.1 107.5\n```\n\n\n:::\n:::\n\n\n::: {.incremental}\n1. **Clasifica** la variable ROM (tipo, escala)\n2. **Construye** una tabla de frecuencias agrupada en 5 intervalos con `freq(rom, cuts=5)`\n3. **Elige y genera** el gráfico adecuado para esta variable\n4. **Calcula** media, mediana, DT, CV y RIQ\n5. **Interpreta:** ¿hay asimetría? ¿los datos son compatibles con la distribución Normal?\n6. **Redacta** un párrafo de 3 líneas resumiendo los resultados\n:::\n\n## Solución — Estadísticos y frecuencias\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrom <- rom_rodilla\n\n# 1. Tabla de frecuencias agrupada\ncat(\"=== FRECUENCIAS (5 intervalos) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== FRECUENCIAS (5 intervalos) ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(table(cut(rom, breaks=5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n(79.9,92]  (92,104] (104,116] (116,128] (128,140] \n        6        11         8         8         7 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Estadísticos descriptivos\ncat(\"\\n=== ESTADÍSTICOS ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== ESTADÍSTICOS ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"n =\", length(rom), \"  |  Media =\", round(mean(rom),1), \"°  |  Mediana =\", round(median(rom),1),\n    \"°\\nDT =\", round(sd(rom),1), \"°  |  CV =\", round(sd(rom)/mean(rom)*100,1),\n    \"%  |  RIQ =\", round(IQR(rom),1), \"°\\nQ1 =\", round(quantile(rom,0.25),1),\n    \"°  |  Q3 =\", round(quantile(rom,0.75),1), \"°  |  Mín =\", min(rom),\n    \"°  |  Máx =\", max(rom), \"°\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 40   |  Media = 109.7 °  |  Mediana = 109 °\nDT = 15.6 °  |  CV = 14.2 %  |  RIQ = 22.4 °\nQ1 = 99.5 °  |  Q3 = 121.9 °  |  Mín = 80 °  |  Máx = 139.9 °\n```\n\n\n:::\n\n```{.r .cell-code}\n# Asimetría y curtosis con fallback\nif (has_e1071) {\n  cat(\"Asimetría =\", round(e1071::skewness(rom),2),\n      \"  |  Curtosis =\", round(e1071::kurtosis(rom),2), \"\\n\")\n} else {\n  cat(\"Asimetría =\", round(skewness(rom),2),\n      \"  |  Curtosis =\", round(kurtosis(rom),2), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAsimetría = 0.07   |  Curtosis = -1 \n```\n\n\n:::\n\n```{.r .cell-code}\nsw <- shapiro.test(rom)\ncat(\"Shapiro-Wilk: W =\", round(sw$statistic,3),\n    \"  P =\", round(sw$p.value,4),\n    if(sw$p.value>0.05) \"  → Normalidad compatible\\n\" else \"  → NO normal\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShapiro-Wilk: W = 0.977   P = 0.5888   → Normalidad compatible\n```\n\n\n:::\n:::\n\n\n## Solución — Gráficos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrom <- rom_rodilla\npar(mfrow=c(1,2), mar=c(4,4,3,1))\nhist(rom, col=\"steelblue\", border=\"white\", breaks=8,\n     main=\"ROM de Rodilla (n=40)\", xlab=\"Grados\", ylab=\"Frecuencia\")\nabline(v=mean(rom), col=\"darkgreen\", lwd=3, lty=2)\nabline(v=median(rom), col=\"blue\", lwd=2, lty=3)\nlegend(\"topright\", c(paste(\"Media =\", round(mean(rom),1)),\n       paste(\"Mediana =\", round(median(rom),1))),\n       col=c(\"darkgreen\",\"blue\"), lty=c(2,3), lwd=c(3,2), bty=\"n\", cex=0.8)\nboxplot(rom, col=\"steelblue\", main=\"Boxplot — ROM de Rodilla\",\n        ylab=\"Grados\", ylim=c(70,140))\n```\n\n::: {.cell-output-display}\n![](T01_Descriptiva_files/figure-revealjs/unnamed-chunk-33-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n## Interpretación de los resultados\n\n::: {.callout-note}\n**ROM de rodilla post-artroplastia (n=40):**\n\nLa flexión media fue de **108.1 ± 14.5 grados** (CV = 13.4%), con una mediana de **106.3 grados** (RIQ: 95.7 – 120.0). La distribución fue aproximadamente simétrica (asimetría = 0.12). El test de Shapiro-Wilk (W = 0.982, P = 0.771) indica que los datos son compatibles con una distribución Normal.\n:::\n\n::: {.callout-tip}\n**Interpretación clínica:** La muestra presenta una flexión media de rodilla adecuada para la fase post-artroplastia, con variabilidad moderada entre pacientes. La distribución simétrica y compatible con la Normal respalda el uso de métodos paramétricos (media ± DT) y de pruebas como el test t de Student para comparaciones futuras (Tema 4).\n:::\n\n## De la descripción a la inferencia — Puente al tema 2 y 3\n\n::: {.callout-important}\n**La descriptiva es el primer paso, no el último.** Describe la muestra. Para llegar a la población necesitamos la **inferencia**.\n:::\n\n**El camino completo del análisis estadístico en fisioterapia:**\n\n| Etapa | Tema | ¿Qué responde? | Herramienta |\n|:------|:----:|:---------------|:------------|\n| **Descriptiva** | T1 | ¿Cómo son mis datos? | `freq()`, gráficos, $\\bar{x}$, $s$ |\n| **Probabilidad** | T2 | ¿Qué modelo siguen mis datos? | Normal, Binomial, Poisson |\n| **Estimación** | T3 | ¿Entre qué valores está el parámetro? | IC, tamaño muestral |\n| **Contraste** | T4 | ¿Es real esta diferencia? | Test t, P-valor |\n| **Asociación** | T5-T6 | ¿Hay relación entre variables? | $\\chi^2$, regresión |\n\n::: {.callout-tip}\n**Ejemplo clínico — ROM de rodilla:**\n\n1. **Descriptiva (T1):** $\\bar{x}=130°$, $s=12°$, $n=40$ → resumo la muestra\n2. **Probabilidad (T2):** $X \\sim N(\\mu, \\sigma^2)$ → modelo teórico para ROM\n3. **Estimación (T3):** IC 95%: $(126.1°, 133.9°)$ → ¿dónde está $\\mu$?\n4. **Contraste (T4):** ¿$\\mu = 135°$? $t = -2.64$, $P = 0.012$ → no, es menor\n:::\n\n## Recapitulación — Tema 1\n\n::: {.callout-tip}\n**Resumen de conceptos clave:**\n:::\n\n| Concepto | Fórmula/Herramienta | Uso principal |\n|:---------|:-------------------|:-------------|\n| Tipos de variables | Nominal, Ordinal, Discreta, Continua | Elegir análisis correcto |\n| Tabla de frecuencias | $n_i$, $f_i$, $N_i$ | Resumir distribución |\n| Media | $\\bar{x} = \\frac{\\sum x_i}{n}$ | Tendencia central (cuantitativas) |\n| Mediana | $Me = x_{((n+1)/2)}$ | Tendencia central (robusta) |\n| Varianza | $s^2 = \\frac{\\sum(x_i - \\bar{x})^2}{n-1}$ | Dispersión |\n| CV | $CV = s/\\bar{x} \\times 100\\%$ | Dispersión relativa |\n| RIQ | $Q_3 - Q_1$ | Dispersión robusta |\n| Asimetría | $g_1$ | Forma de la distribución |\n\n---\n\n::: {.reference-box}\n**Referencias**\n\n- [@Altman1990] Altman, D. G. (1990). *Practical Statistics for Medical Research*. Chapman & Hall/CRC.\n- [@Femia2026] Femia, P. & Luque-Fernandez, M. A. (2026). *BioEstatR: Biostatistics Routines in R*. R package v1.0.0. Universidad de Granada. <https://migariane.github.io/BioEstatR>\n- [@LuqueFernandez2026] Luque-Fernandez, M. A. (2026). *Matemáticas para la Estadística Médica con R*. Universidad de Granada. <https://migariane.github.io/MatematicaEstadisticaMedicinaR>\n- [@Rosner2015] Rosner, B. (2015). *Fundamentals of Biostatistics* (8th ed.). Cengage Learning.\n- [@Stevens1946] Stevens, S. S. (1946). On the theory of scales of measurement. *Science*, 103(2684), 677–680.\n- [@Tukey1977] Tukey, J. W. (1977). *Exploratory Data Analysis*. Addison-Wesley.\n:::\n",
    "supporting": [
      "T01_Descriptiva_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}