{
  "hash": "c0db84687016952ff7c1a0f57dd56a2f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análisis de Datos Cualitativos\"\nsubtitle: \"Tema V — Test Chi-Cuadrado, Tablas 2×2 y McNemar\"\nauthor:\n  - name: \"Miguel Angel Luque-Fernández\"\n    affiliation: \"Dpto. Estadística e Investigación Operativa, Universidad de Granada\"\n    email: \"mluquefe@ugr.es\"\n    url: \"https://migariane.github.io\"\ndate: \"2026\"\nlicense: \"CC BY 4.0\"\nformat:\n  revealjs:\n    slide-number: c/t\n    code-fold: true\n    code-summary: \"Mostrar código R\"\n    code-copy: true\n    code-overflow: wrap\n    fig-align: center\n    fig-width: 9\n    fig-height: 5.2\n    lang: es\nexecute:\n  warning: false\n  message: false\n  echo: true\n  eval: true\n---\n\n# Análisis de Datos Cualitativos {.center}\n\n![](logo.png){width=\"90px\"}\n\n**Grado en Fisioterapia**\n\n**CC BY 4.0** · Miguel Angel Luque-Fernández\n\n[Miguel Angel Luque-Fernández](https://migariane.github.io) · [maluque.netlify.app](https://maluque.netlify.app)\n\nDpto. Estadística e Investigación Operativa · Universidad de Granada\n\n\n\n::: {.connection}\n**Del contraste a la asociación:** En el Tema 4 aprendiste a contrastar hipótesis sobre medias y proporciones. Ahora ampliamos ese marco a tablas de contingencia: ¿hay asociación entre dos variables cualitativas? El test χ² y las medidas de asociación (OR, RR, NNT) son las herramientas que necesitas.\n:::\n\n## Objetivos de aprendizaje — Tema 5\n\n::: {.callout-tip}\n**Al finalizar este tema sabrás:**\n:::\n\n::: {.incremental}\n1. Distinguir test de homogeneidad (2+ muestras) de independencia (1 muestra)\n2. Calcular frecuencias esperadas y el estadístico $\\chi^2$\n3. Identificar el tipo de estudio (transversal, prospectivo, retrospectivo)\n4. Calcular e interpretar OR, RR y DR con sus IC\n5. Aplicar el test de McNemar para datos pareados\n6. Usar `tabla2x2()` y `testmcnemar()` de BioEstatR\n:::\n\n\n## Motivación clínica — ¿para qué sirve el test $\\chi^2$?\n\n**Caso clínico:** Un ensayo compara terapia manual vs. ejercicio terapéutico para dolor lumbar.\n\n| | Recupera | No recupera | Total |\n|---|---|---|---|\n| **Terapia manual** | 42 | 18 | 60 |\n| **Ejercicio** | 30 | 30 | 60 |\n| **Total** | 72 | 48 | 120 |\n\n::: {.incremental}\n- Terapia manual: 70% de recuperación vs. Ejercicio: 50%\n- ¿Es esta diferencia **real** o fruto del **azar**?\n- El test $\\chi^2$ responde esta pregunta con un **P-valor**\n- Este tema te da las herramientas para decidir si una asociación entre variables cualitativas es estadísticamente significativa\n:::\n\n\n## Introducción al test $\\chi^2$\n\n::: {.incremental}\n\n- Debido a **Karl Pearson** (1900), es uno de los test más clásicos de la Estadística\n- Se aplica al análisis de **variables cualitativas** mediante recuentos (VA discretas)\n- El problema principal: comprobar si las proporciones observadas difieren **significativamente** de las esperadas bajo una determinada hipótesis\n\n**Dos aplicaciones del test $\\chi^2$:**\n\n1. **Ajuste a distribuciones** — ej: ajuste a proporciones mendelianas (no lo estudiamos aquí)\n2. **Análisis de tablas de contingencia** ← Nos centramos aquí\n   - Test de **homogeneidad** entre varias muestras (2 o más)\n   - Test de **independencia** entre dos variables cualitativas (1 sola muestra)\n\n:::\n\n::: {.callout-tip}\nEn la práctica, homogeneidad e independencia se resuelven con la **misma fórmula** ($E_{ij} = F_i \\times C_j / T$), aunque conceptualmente son problemas diferentes.\n:::\n\n## Tablas de contingencia — Notación y terminología\n\nUna **tabla de contingencia** ($r \\times c$) cruza la información de dos variables cualitativas.\n\n**Ejemplo 1 — Homogeneidad (4×3):** 4 tratamientos × Estado del paciente (n=560)\n\n| Tratamiento | Peor | Igual | Mejor | **Total fila** ($F_i$) |\n|:----------:|:----:|:-----:|:-----:|:----------------------:|\n| 1 | 7 | 28 | 115 | 150 |\n| 2 | 15 | 20 | 85 | 120 |\n| 3 | 10 | 30 | 90 | 130 |\n| 4 | 5 | 40 | 115 | 160 |\n| **Total col.** ($C_j$) | 37 | 118 | 405 | **T = 560** |\n\n- **2 características:** tratamiento (4 categorías) × estado (3 categorías) → tabla $4 \\times 3$\n- **4 muestras independientes** (una por tratamiento) → Test de **homogeneidad**\n\n## Tablas de contingencia — Independencia\n\n**Ejemplo 2 — Independencia (3×3):** Localización del tumor × Naturaleza (n=141)\n\n| Localización | Benigno | Maligno | Otros | **Total** |\n|:-----------:|:-------:|:-------:|:-----:|:---------:|\n| Lóbulo frontal | 23 | 9 | 6 | 38 |\n| Lóbulo temporal | 21 | 4 | 3 | 28 |\n| Otras áreas | 34 | 24 | 17 | 75 |\n| **Total** | 78 | 37 | 26 | **141** |\n\n- **2 características:** localización (3) × naturaleza (3) → tabla $3 \\times 3$\n- **1 sola muestra** de 141 pacientes → Test de **independencia**\n\n::: {.callout-tip}\n**¿Cómo distinguirlos?** El número de muestras lo indica: 1 muestra → independencia; 2+ muestras → homogeneidad.\n:::\n\n## Homogeneidad vs. independencia — Comparación lado a lado\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**Homogeneidad**\n\n- **2 o más muestras** independientes\n- Pregunta: ¿Son iguales las **proporciones** entre los grupos?\n- $H_0$: $p_{1j} = p_{2j} = \\cdots = p_{rj}$ para cada $j$\n- Ejemplo: 4 tratamientos, ¿mismo % de mejoría?\n\n:::\n::: {.column width=\"50%\"}\n\n**Independencia**\n\n- **1 sola muestra** de $T$ individuos\n- Pregunta: ¿Están **asociadas** las dos variables?\n- $H_0$: Las variables son independientes\n- Ejemplo: 141 pacientes, ¿naturaleza del tumor asociada a localización?\n\n:::\n:::\n\n**Ambos tests comparten la misma mecánica de cálculo:**\n\n$$E_{ij} = \\frac{F_i \\times C_j}{T} \\qquad \\chi^2_{\\text{exp}} = \\sum_{i=1}^{r} \\sum_{j=1}^{c} \\frac{(O_{ij} - E_{ij})^2}{E_{ij}} \\qquad \\text{gl} = (r-1)(c-1)$$\n\nLa diferencia está en la **interpretación** de $H_0$, no en la fórmula.\n\n## Misma tabla, dos interpretaciones — Ejemplo clínico\n\n**Caso:** Un fisioterapeuta estudia 200 pacientes con dolor lumbar, clasificados por tipo de tratamiento (manual vs. ejercicio) y resultado (mejoría sí/no).\n\n| | Mejoría Sí | Mejoría No | Total |\n|---|---|---|---|\n| **Terapia Manual** | 70 | 30 | 100 |\n| **Ejercicio** | 50 | 50 | 100 |\n| **Total** | 120 | 80 | 200 |\n\n**Interpretación A — Homogeneidad (2 muestras independientes):**\n- $H_0$: La proporción de mejoría es igual en ambos tratamientos\n- 70% mejoría en manual vs. 50% en ejercicio → ¿son homogéneos?\n- $\\chi^2 = 8.33$, $P = 0.004$ → **No son homogéneos** (las proporciones difieren)\n\n**Interpretación B — Independencia (1 muestra de 200):**\n- $H_0$: El tipo de tratamiento y el resultado son independientes\n- ¿Está asociado el tipo de tratamiento con la mejoría?\n- $\\chi^2 = 8.33$, $P = 0.004$ → **No son independientes** (existe asociación)\n\n::: {.callout-tip}\n**Mismo cálculo, distinta pregunta:** La fórmula $\\chi^2$ es idéntica. Lo que cambia es el diseño del estudio (¿1 muestra o 2?) y la redacción de $H_0$. En la práctica clínica, la interpretación como **homogeneidad** suele ser más natural cuando comparas tratamientos.\n:::\n\n## Notación general para tablas $r \\times c$ — Estructura\n\nCruzamos dos variables cualitativas $A$ (filas, $r$ categorías) y $B$ (columnas, $c$ categorías):\n\n| | $B_1$ | $B_2$ | $\\cdots$ | $B_c$ | **Totales** |\n|---|:---:|:---:|:---:|:---:|:---:|\n| $A_1$ | $O_{11}$ | $O_{12}$ | $\\cdots$ | $O_{1c}$ | $F_1$ |\n| $A_2$ | $O_{21}$ | $O_{22}$ | $\\cdots$ | $O_{2c}$ | $F_2$ |\n| $\\vdots$ | $\\vdots$ | $\\vdots$ | $\\ddots$ | $\\vdots$ | $\\vdots$ |\n| $A_r$ | $O_{r1}$ | $O_{r2}$ | $\\cdots$ | $O_{rc}$ | $F_r$ |\n| **Totales** | $C_1$ | $C_2$ | $\\cdots$ | $C_c$ | **$T$** |\n\n- $O_{ij}$: frecuencia **observada** en fila $i$, columna $j$\n- $F_i$: total de fila $i$ (suma de esa fila)\n- $C_j$: total de columna $j$ (suma de esa columna)\n- $T$: total global\n\n(La notación de sumatorios y los porcentajes se detallan a continuación.)\n\n## Notación general — Sumatorios y porcentajes\n\n**Sumatorios (notación compacta):**\n\n- $F_i = \\sum_{j=1}^{c} O_{ij}$: total de fila $i$\n- $C_j = \\sum_{i=1}^{r} O_{ij}$: total de columna $j$\n- $T = \\sum_{i=1}^{r} F_i = \\sum_{j=1}^{c} C_j$: total global\n\n**Tres tipos de tablas de porcentajes:** por filas, por columnas, y totales.\n\n## Ejemplo de tabla $2 \\times 2$ — Notación y porcentajes\n\n**Estudio:** Asociación entre hábito de fumar de la madre y bajo peso del recién nacido (n=400)\n\n| | Fuma Sí | Fuma No | Total |\n|---|---|---|---|\n| **Peso Bajo** | 20 | 26 | 46 |\n| **Peso Normal** | 60 | 294 | 354 |\n| **Total** | 80 | 320 | 400 |\n\n**Porcentajes por columnas:** del total de madres fumadoras 25% tienen niño con bajo peso vs 8% de no fumadoras\n\n**Porcentajes por filas:** del total de niños con bajo peso, el 43.5% son hijos de madres fumadoras\n\n**Porcentajes totales:** el 5% del total son madres fumadoras con niño de bajo peso\n\n## Tipos de estudio epidemiológico en tablas $2 \\times 2$\n\nLa misma tabla $2 \\times 2$ puede proceder de **tres tipos de muestreo**:\n\n::: {.columns}\n::: {.column width=\"33%\"}\n\n**Transversal**\n- 1 muestra de $T$ individuos\n- Se clasifican por enfermedad y FR\n\n:::\n::: {.column width=\"33%\"}\n\n**Prospectivo (Cohortes)**\n- 2 muestras: $C_1$ expuestos y $C_2$ no expuestos\n- Se observa enfermedad\n\n:::\n::: {.column width=\"33%\"}\n\n**Retrospectivo (Casos-Control)**\n- 2 muestras: $F_1$ enfermos y $F_2$ no enfermos\n- Se observa exposición\n\n:::\n:::\n\n| | FR Sí | FR No | Total |\n|---|---|---|---|\n| **Enfermos** | $O_{11}$ | $O_{12}$ | $F_1$ |\n| **No Enfermos** | $O_{21}$ | $O_{22}$ | $F_2$ |\n| **Total** | $C_1$ | $C_2$ | $T$ |\n\n::: {.callout-warning}\nEl **tipo de estudio** determina qué **medidas de asociación** se pueden estimar y qué **corrección $c$** se debe usar en el $\\chi^2$.\n:::\n\n## Test de homogeneidad — Tablas $r \\times c$ (no $2 \\times 2$)\n\n**Ejemplo — 4 tratamientos:**\n\n| Tratamiento | Peor | Igual | Mejor | Total |\n|:----------:|:----:|:-----:|:-----:|:-----:|\n| 1 | 7 | 28 | 115 | 150 |\n| 2 | 15 | 20 | 85 | 120 |\n| 3 | 10 | 30 | 90 | 130 |\n| 4 | 5 | 40 | 115 | 160 |\n| **Total** | 37 | 118 | 405 | 560 |\n\n**Hipótesis:**\n\n$H_0$: Los 4 tratamientos son **homogéneos** (igual proporción en cada categoría de resultado)\n\n$H_1$: Al menos un tratamiento es **diferente** a los demás\n\n**¿Qué supone $H_0$?** $p_{11}=p_{21}=p_{31}=p_{41}$ (mismo % que empeoran), $p_{12}=p_{22}=p_{32}=p_{42}$ (mismo % que quedan igual), y $p_{13}=p_{23}=p_{33}=p_{43}$ (mismo % que mejoran).\n\n## Frecuencias esperadas bajo $H_0$\n\nSi $H_0$ es cierta, las frecuencias esperadas se calculan como:\n\n$$E_{ij} = \\frac{F_i \\times C_j}{T}$$\n\n::: {.incremental}\n\n**Cálculo para el ejemplo:** $E_{11} = \\frac{150 \\times 37}{560} = 9.91$, $\\quad E_{12} = \\frac{150 \\times 118}{560} = 31.61$\n\n| Tratamiento | Peor ($E_{i1}$) | Igual ($E_{i2}$) | Mejor ($E_{i3}$) |\n|:----------:|:---------------:|:----------------:|:----------------:|\n| 1 | 9.91 | 31.61 | 108.48 |\n| 2 | 7.93 | 25.28 | 86.79 |\n| 3 | 8.59 | 27.39 | 94.02 |\n| 4 | 10.57 | 33.72 | 115.71 |\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrat <- matrix(c(7,28,115,15,20,85,10,30,90,5,40,115), nrow=4, byrow=TRUE)\nround(chisq.test(trat)$expected, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      [,1]  [,2]   [,3]\n[1,]  9.91 31.61 108.48\n[2,]  7.93 25.29  86.79\n[3,]  8.59 27.39  94.02\n[4,] 10.57 33.71 115.71\n```\n\n\n:::\n:::\n\n\n## Visualización del test $\\chi^2$ — Observado vs esperado\n\n**4 tratamientos de fisioterapia × Estado del paciente:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nO <- matrix(c(7,28,115, 15,20,85, 10,30,90, 5,40,115), nrow=4, byrow=TRUE)\nE <- matrix(c(9.91,31.61,108.48, 7.93,25.28,86.79, 8.59,27.39,94.02, 10.57,33.72,115.71), nrow=4, byrow=TRUE)\n\npar(mfrow=c(2,2), mar=c(4,4,3,1))\nfor(i in 1:4){\n  barplot(rbind(O[i,], E[i,]), beside=TRUE, names=c(\"Peor\",\"Igual\",\"Mejor\"),\n          col=c(\"steelblue\",\"coral\"), main=paste(\"Tratamiento\",i),\n          ylab=\"Frecuencia\", ylim=c(0,120), legend=c(\"Observado\",\"Esperado\"))\n}\n```\n\n::: {.cell-output-display}\n![](T05_ChiCuadrado_files/figure-revealjs/unnamed-chunk-2-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**El $\\chi^2$ mide la discrepancia entre barras azules (observado) y rojas (esperado bajo $H_0$).**\n\n## Condiciones de validez del test $\\chi^2$\n\n::: {.callout-important}\n\n**Dos condiciones que deben cumplirse simultáneamente:**\n\n1. **Ninguna** frecuencia esperada $E_{ij}$ puede ser inferior a **1**\n2. **No más del 20%** de las $E_{ij}$ pueden ser inferiores o iguales a **5**\n\n:::\n\n**En el ejemplo (4 tratamientos, 12 celdas):** todas las $E_{ij} > 5$ ✓ → el método es válido.\n\nSe admitirían como máximo $12 \\times 0.20 = 2.4 \\rightarrow 2$ valores con $1 < E_{ij} \\leq 5$. Con 3 ya no sería válido.\n\n## Estadístico de contraste y grados de libertad\n\n$$\\chi^2_{\\text{exp}} = \\sum_{i=1}^{r} \\sum_{j=1}^{c} \\frac{(O_{ij} - E_{ij})^2}{E_{ij}}$$\n\n::: {.incremental}\n\n**Grados de libertad:** $\\text{gl} = (r-1) \\times (c-1)$\n\n**En el ejemplo (4×3):** gl = $(4-1)(3-1) = 6$\n\n$$\\chi^2_{\\text{exp}} = \\frac{(7-9.91)^2}{9.91} + \\frac{(28-31.61)^2}{31.61} + \\cdots + \\frac{(115-115.71)^2}{115.71} = 13.87$$\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi <- chisq.test(trat)\ncat(\"χ²exp =\", round(chi$statistic,2), \"| gl =\", chi$parameter,\n    \"| P =\", round(chi$p.value,4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nχ²exp = 13.87 | gl = 6 | P = 0.0311\n```\n\n\n:::\n:::\n\n\n**Resultado:** $P < 0.05$ → **Rechazamos $H_0$.** Los 4 tratamientos no son homogéneos.\n\n## Distribución $\\chi^2$ — Visualización del contraste\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngl <- 6\nchi_exp <- 13.87\nchi_crit <- qchisq(0.95, gl)\np_val <- round(1 - pchisq(chi_exp, gl), 4)\n\ncurve(dchisq(x, gl), 0, 22, lwd = 3, col = \"steelblue\",\n      main = \"Distribucion Chi-cuadrado con gl = 6\",\n      xlab = \"Chi-cuadrado\", ylab = \"Densidad\")\nabline(v = chi_crit, col = \"darkgreen\", lwd = 2.5, lty = 2)\nabline(v = chi_exp, col = \"coral\", lwd = 3)\n# Region de rechazo\nxr <- seq(chi_crit, 22, 0.01)\nyr <- dchisq(xr, gl)\npolygon(c(xr, rev(xr)), c(yr, rep(0, length(yr))),\n        col = rgb(0.9, 0.3, 0.2, 0.3), border = NA)\n# Etiquetas\ntext(chi_crit + 1.5, dchisq(chi_crit, gl) + 0.01,\n     \"Chi-crit = 12.59\", col = \"darkgreen\", font = 2)\ntext(chi_exp, dchisq(chi_exp, gl) + 0.015,\n     paste0(\"Chi2 = \", chi_exp, \"\\nP = \", p_val), col = \"coral\", font = 2)\nlegend(\"topright\", c(\"Region de rechazo (alfa = 0.05)\", \"Valor critico\", \"Chi2 observado\"),\n       fill = c(rgb(0.9, 0.3, 0.2, 0.3), NA, NA),\n       border = c(NA, \"darkgreen\", \"coral\"),\n       lty = c(NA, 2, 1), lwd = c(NA, 2.5, 3),\n       col = c(NA, \"darkgreen\", \"coral\"), bty = \"n\", cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](T05_ChiCuadrado_files/figure-revealjs/unnamed-chunk-4-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-tip}\n**¿Cómo leer este gráfico?** La curva es la distribución $\\chi^2_6$ bajo $H_0$. El área roja es la región de rechazo ($\\alpha = 0.05$). Nuestro $\\chi^2 = 13.87$ (línea roja) cae **dentro** de la región de rechazo → $P < 0.05$ → diferencias significativas entre tratamientos.\n:::\n\n## Análisis de las causas de significación\n\nEl test $\\chi^2$ es un **test ómnibus**: detecta diferencias pero **no dice dónde** están.\n\n**Tres métodos para identificar las causas:**\n\n1. **Tabla de porcentajes** → fácil, pero subjetivo\n2. **Residuos estandarizados** → objetivo e intuitivo\n3. **Partición de tablas** (reducción a $2 \\times 2$) → potente pero laborioso\n\n\n## Tabla de porcentajes por filas\n\n¿Qué tratamiento(s) es/son distinto(s)? Observemos los porcentajes:\n\n| Tratamiento | Peor | Igual | Mejor | Total |\n|:----------:|:----:|:-----:|:-----:|:-----:|\n| 1 | 4.7% | 18.7% | 76.7% | 100% |\n| 2 | **12.5%** | 16.7% | 70.8% | 100% |\n| 3 | 7.7% | 23.1% | 69.2% | 100% |\n| 4 | **3.1%** | 25.0% | 71.9% | 100% |\n| **Total** | 6.6% | 21.1% | 72.3% | 100% |\n\n**Observaciones:**\n- Mayor discrepancia en % de \"Peor\": Tto 2 (12.5%, el que más empeora) vs Tto 4 (3.1%, el que menos)\n- Los % de \"Mejor\" son similares (~70% en todos los tratamientos)\n- Los % de \"Igual\" sugieren dos grupos: Ttos 1-2 vs Ttos 3-4\n\n::: {.callout-warning}\nEl análisis de porcentajes es una **primera aproximación subjetiva**. El estudio definitivo se hace con residuos estandarizados.\n:::\n\n::: {.callout-tip}\n**Pregunta para reflexionar:** ¿Qué tratamiento recomendarías descartar basándote solo en estos porcentajes? ¿Es suficiente esta evidencia para tomar una decisión clinica?\n:::\n\n## Residuos estandarizados\n\n$$R_{ij} = \\frac{O_{ij} - E_{ij}}{\\sqrt{E_{ij}}}$$\n\n- $|R_{ij}| > 1.96$ → celda con contribución **significativa** ($\\alpha = 0.05$)\n- $|R_{ij}| > 2.58$ → celda con contribución **muy significativa** ($\\alpha = 0.01$)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi <- chisq.test(trat)\nround(chi$stdres, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      [,1]  [,2]  [,3]\n[1,] -1.12 -0.84  1.39\n[2,]  2.93 -1.33 -0.41\n[3,]  0.57  0.64 -0.90\n[4,] -2.10  1.44 -0.15\n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualización: heatmap de residuos\npar(mfrow=c(1,1), mar=c(5,5,4,2))\nsr <- chi$stdres\n# Invertir filas para que coincida con el orden visual\nimage(1:ncol(sr), 1:nrow(sr), t(sr[nrow(sr):1,]),\n      col=colorRampPalette(c(\"darkgreen\",\"white\",\"coral\"))(100),\n      main=\"Residuos Estandarizados\", xlab=\"\", ylab=\"\", xaxt=\"n\", yaxt=\"n\")\naxis(1, at=1:ncol(sr), labels=colnames(sr), las=2, cex.axis=0.8)\naxis(2, at=nrow(sr):1, labels=rownames(sr), las=2, cex.axis=0.8)\nfor(i in 1:nrow(sr))\n  for(j in 1:ncol(sr))\n    text(j, nrow(sr)-i+1, round(sr[i,j],1), \n         col=ifelse(abs(sr[i,j])>2,\"white\",\"black\"), font=2, cex=0.85)\n```\n\n::: {.cell-output-display}\n![](T05_ChiCuadrado_files/figure-revealjs/unnamed-chunk-5-1.png){width=864}\n:::\n:::\n\n\n## Test de independencia — Tablas $r \\times c$\n\n**Ejemplo:** ¿Está asociada la naturaleza del tumor con su localización? (n=141)\n\n| Localización | Benigno | Maligno | Otros | Total |\n|:-----------:|:-------:|:-------:|:-----:|:-----:|\n| Lóbulo frontal | 23 | 9 | 6 | 38 |\n| Lóbulo temporal | 21 | 4 | 3 | 28 |\n| Otras áreas | 34 | 24 | 17 | 75 |\n| **Total** | 78 | 37 | 26 | 141 |\n\n**$H_0$:** Naturaleza y localización son **independientes**\n\n**$H_1$:** Naturaleza y localización están **asociadas**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntumor <- matrix(c(23,9,6,21,4,3,34,24,17), nrow=3, byrow=TRUE)\nchi2 <- chisq.test(tumor)\ncat(\"χ²exp =\", round(chi2$statistic,2), \"| gl =\", chi2$parameter,\n    \"| P =\", round(chi2$p.value,4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nχ²exp = 7.84 | gl = 4 | P = 0.0975\n```\n\n\n:::\n\n```{.r .cell-code}\n# χ²exp = 7.64, gl = 4, P = 0.106 → No significativo (pero hay indicios)\n```\n:::\n\n\n## Importancia del caso $2 \\times 2$\n\n::: {.callout-important}\n\nLas tablas $2 \\times 2$ requieren un **tratamiento especial**:\n\n1. **NO es aplicable** la fórmula general del $\\chi^2$\n2. Permiten obtener **medidas de asociación** entre las variables\n3. Surgen cuando ambas variables son **dicotómicas** (binarias)\n4. Permiten resolver problemas de gran interés en el ámbito biosanitario\n\n:::\n\n**Formato estándar** (enfermedad en filas, factor de riesgo en columnas):\n\n| | FR Expuesto | FR No Expuesto | Total |\n|---|---|---|---|\n| **Enfermedad Presente** | $O_{11}$ | $O_{12}$ | $F_1$ |\n| **Enfermedad Ausente** | $O_{21}$ | $O_{22}$ | $F_2$ |\n| **Total** | $C_1$ | $C_2$ | $T$ |\n\n- **Primera fila:** modalidad de mayor interés (enfermos)\n- **Primera columna:** modalidad que induce a tener la enfermedad\n\n## Ejemplo $2 \\times 2$ — Madre fumadora y peso\n\n**Estudio transversal (n=400 nacimientos):**\n\n| | Fuma Sí | Fuma No | Total |\n|---|---|---|---|\n| **Peso Bajo** | 20 | 26 | 46 |\n| **Peso Normal** | 60 | 294 | 354 |\n| **Total** | 80 | 320 | 400 |\n\n**¿Qué categoría es el factor de riesgo?** Con porcentajes por columnas:\n\n- 25% de fumadoras tienen niño con bajo peso\n- 8% de no fumadoras tienen niño con bajo peso\n\nComo 25% > 8%, **fumar = Sí** es la modalidad de riesgo.\n\n## Estadístico $\\chi^2$ para tablas $2 \\times 2$\n\n::: {.callout-warning}\n\n**¡NO es válida la expresión general!** Para tablas $2 \\times 2$ se usa:\n\n$$\\chi^2_{\\text{exp}} = \\frac{\\left(|O_{11}O_{22} - O_{12}O_{21}| - c\\right)^2 \\cdot T}{F_1 \\cdot F_2 \\cdot C_1 \\cdot C_2}$$\n\ndonde:\n- $|O_{11}O_{22} - O_{12}O_{21}|$: **producto cruzado** (en valor absoluto)\n- $c$: **corrección de continuidad** — depende del tipo de estudio\n- $F_1, F_2, C_1, C_2$: totales marginales de filas y columnas\n:::\n\n(La corrección $c$ y las condiciones de validez se detallan a continuación.)\n\n## Condiciones de validez para el caso $2 \\times 2$\n\n**Frecuencia mínima esperada:** $E = \\min(F_1,F_2) \\cdot \\min(C_1,C_2) / T$\n\n| Tipo de estudio | $E$ mínimo | $E$ si $T<500$ | Corrección $c$ |\n|:---------------|:----------:|:-------------:|:--------------:|\n| **Transversal** | $E \\geq 4.9$ | $E \\geq 7.7$ | $c = 0.5$ |\n| **Prospectivo** | $E \\geq 6.2$ | $E \\geq 3.9$ | $c = 1$ si $C_1\\neq C_2$, $c=2$ si $C_1=C_2$ |\n| **Retrospectivo** | Misma que prospectivo | | $c = 1$ si $F_1\\neq F_2$, $c=2$ si $F_1=F_2$ |\n\n::: {.callout-tip}\n**¿Por qué varía $c$? — Intuición:** Imagina que el test $\\chi^2$ funciona como una lupa. En estudios **transversales** (una muestra, sin márgenes fijos), la lupa tiene más aumento → basta una corrección pequeña ($c=0.5$). En estudios **prospectivos/retrospectivos** (dos muestras, márgenes fijos por diseño), la lupa tiene menos aumento → necesitas una corrección mayor ($c=1$ o $c=2$) para no \"ver\" asociaciones que son solo ruido.\n:::\n\n**gl = 1** siempre en tablas $2 \\times 2$.\n\n## Ejemplo $2 \\times 2$ — Cálculo completo\n\n**Estudio transversal:** $E = \\frac{46 \\times 80}{400} = 9.2 \\geq 4.9$ ✓. $T=400 < 500$: $E=9.2 \\geq 7.7$ ✓\n\n$$\\chi^2_{\\text{exp}} = \\frac{(|20 \\times 294 - 26 \\times 60| - 0.5)^2 \\times 400}{46 \\times 354 \\times 80 \\times 320}$$\n\n$$= \\frac{(5880 - 1560 - 0.5)^2 \\times 400}{46 \\times 354 \\times 80 \\times 320} = \\frac{(4319.5)^2 \\times 400}{417,177,600} = 17.90$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla <- matrix(c(20,26,60,294), nrow=2)\nchi <- chisq.test(tabla, correct=TRUE)\ncat(\"χ²exp =\", round(chi$statistic,2), \"| P =\", format(chi$p.value, digits=4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nχ²exp = 16.29 | P = 5.442e-05\n```\n\n\n:::\n:::\n\n\n**gl = 1, $P < 0.001$** → **Rechazamos $H_0$.** Existe asociación significativa entre fumar y bajo peso.\n\n## Interpretación de medidas de asociación — Guía visual\n\n**Fumar y bajo peso (n=400):**\n\n| | Fuma Sí | Fuma No | Total |\n|---|---|---|---|\n| **Peso Bajo** | 20 | 26 | 46 |\n| **Peso Normal** | 60 | 294 | 354 |\n| **Total** | 80 | 320 | 400 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,3), mar=c(4,4,3,1))\n# DR\np1<-20/80; p2<-26/320\nbarplot(c(p1,p2)*100, names=c(\"Fumadoras\",\"No fumadoras\"), col=c(\"coral\",\"steelblue\"),\n        main=paste0(\"DR = \",round(p1-p2,3),\"\\n(\",round((p1-p2)*100,1),\" pp de diferencia)\"),\n        ylab=\"% Bajo Peso\", ylim=c(0,30))\n# RR = 3.08\nbarplot(c(p1,p2)*100, names=c(\"Fumadoras\",\"No fumadoras\"), col=c(\"coral\",\"steelblue\"),\n        main=paste0(\"RR = p1/p2 = \",round(p1/p2,2),\"\\n(3x mas riesgo)\"),\n        ylab=\"% Bajo Peso\", ylim=c(0,30))\n# OR = 3.77\nbarplot(c(p1,p2)*100, names=c(\"Fumadoras\",\"No fumadoras\"), col=c(\"coral\",\"steelblue\"),\n        main=paste0(\"OR = \",round((20*294)/(26*60),2),\"\\n(odds 3.77x mayor)\"),\n        ylab=\"% Bajo Peso\", ylim=c(0,30))\n```\n\n::: {.cell-output-display}\n![](T05_ChiCuadrado_files/figure-revealjs/unnamed-chunk-8-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n::: {.callout-important}\n**Para el estudiante:** DR se interpreta en **escala aditiva** (diferencia de %). RR y OR en **escala multiplicativa** (cuántas veces más). DR = 0 y RR/OR = 1 significan ausencia de asociación.\n:::\n\n## Medidas de asociación en tablas $2 \\times 2$\n\nEl valor P **no indica la intensidad** de la asociación, solo la evidencia muestral contra $H_0$.\n\n::: {.incremental}\n\n**1. Riesgo Absoluto (Diferencia de Berkson):**\n$$d = p_1 - p_2 = \\frac{O_{11}}{C_1} - \\frac{O_{12}}{C_2}$$\n$d = 0$ independencia; $d > 0$ asociación positiva; $d < 0$ asociación negativa\n\n**2. Riesgo Relativo:**\n$$R = \\frac{p_1}{p_2} = \\frac{O_{11}/C_1}{O_{12}/C_2}$$\n$R = 1$ independencia; $R > 1$ factor de riesgo; $R < 1$ factor protector\n\n**3. Razón del Producto Cruzado (Odds Ratio):**\n$$O = \\frac{O_{11} \\times O_{22}}{O_{12} \\times O_{21}}$$\n$O = 1$ independencia; $O > 1$ asociación positiva; $O < 1$ asociación negativa\n\n:::\n\n## Medidas de asociación — Cálculo en el ejemplo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nO11<-20; O12<-26; O21<-60; O22<-294; C1<-80; C2<-320\nd  <- O11/C1 - O12/C2\nR  <- (O11/C1) / (O12/C2)\nO  <- (O11*O22)/(O12*O21)\ncat(\"Riesgo Absoluto d =\", round(d,3),\n    \"\\nRiesgo Relativo R =\", round(R,3),\n    \"\\nOdds Ratio      O =\", round(O,3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRiesgo Absoluto d = 0.169 \nRiesgo Relativo R = 3.077 \nOdds Ratio      O = 3.769\n```\n\n\n:::\n:::\n\n\n**Interpretación:**\n- **$d = 0.169$:** La probabilidad de bajo peso es 16.9 puntos porcentuales mayor en madres fumadoras\n- **$R = 3.08$:** La probabilidad de bajo peso es 3.08 veces mayor (¡el triple!) si la madre fuma\n- **$O = 3.77$:** La odds de bajo peso es 3.77 veces mayor en madres fumadoras\n\n::: {.callout-tip}\n**Pregunta para reflexionar:** ¿Por qué el OR (3.77) es mayor que el RR (3.08)? Pista: observa las fórmulas — ¿qué ocurre cuando la prevalencia del desenlace no es baja?\n:::\n\n## Visualización de las medidas de asociación\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Forest plot de las medidas de asociación con IC 95%\nmedidas <- c(\"DR (Riesgo Absoluto)\", \"RR (Riesgo Relativo)\", \"OR (Odds Ratio)\")\nestimador <- c(0.169, 3.08, 3.77)\nic_inf <- c(0.067, 1.85, 1.95)\nic_sup <- c(0.271, 5.13, 7.30)\nvalor_nulo <- c(0, 1, 1)\ncolores <- c(\"#2980b9\", \"#27ae60\", \"coral\")\n\npar(mar = c(5, 10, 3, 2))\nplot(estimador, 3:1, pch = 19, cex = 2, col = colores,\n     xlim = c(-0.3, 8), ylim = c(0.5, 3.5), yaxt = \"n\",\n     xlab = \"Estimador (escala logarítmica para RR/OR)\", ylab = \"\",\n     main = \"Medidas de Asociación con IC 95%\\n(Tabaquismo → Bajo Peso al Nacer)\",\n     log = \"\")\naxis(2, at = 3:1, labels = medidas, las = 1, cex.axis = 0.9)\n# Intervalos de confianza\nfor(i in 1:3) {\n  lines(c(ic_inf[i], ic_sup[i]), c(3-i+1, 3-i+1), lwd = 3, col = colores[i])\n  points(ic_inf[i], 3-i+1, pch = \"|\", cex = 1.2, col = colores[i])\n  points(ic_sup[i], 3-i+1, pch = \"|\", cex = 1.2, col = colores[i])\n}\n# Líneas de valor nulo\nabline(v = 0, lty = 3, col = \"grey50\", lwd = 2)\ntext(0.9, 3.2, \"Valor nulo\\n(DR=0)\", col = \"grey50\", cex = 0.7)\nabline(v = 1, lty = 3, col = \"grey50\", lwd = 2)\ntext(1.6, 1.7, \"Valor nulo\\n(RR/OR=1)\", col = \"grey50\", cex = 0.7)\n```\n\n::: {.cell-output-display}\n![](T05_ChiCuadrado_files/figure-revealjs/unnamed-chunk-10-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-tip}\n**Regla visual:** Si el IC de DR **no cruza el 0**, la asociación es significativa. Si el IC de RR/OR **no cruza el 1**, la asociación es significativa. En este ejemplo, los tres IC evitan sus respectivos valores nulos → asociación significativa.\n:::\n\n## ¿Qué Medida Usar Según el Tipo de Estudio?\n\n| Medida | Transversal | Prospectivo | Retrospectivo |\n|:-------|:----------:|:----------:|:------------:|\n| $d$ (Riesgo Absoluto) | ✓ | ✓ | ✗ |\n| $R$ (Riesgo Relativo) | ✓ | ✓ | Aprox. si $P(E) < 10\\%$ |\n| $O$ (Odds Ratio) | ✓ | ✓ | ✓ |\n\n**El Odds Ratio es la medida de asociación por excelencia en epidemiología:**\n- Válido en **cualquier** tipo de estudio\n- Forma parte de modelos más complejos (regresión logística)\n- **Cuidado:** no interpretar $O$ como si fuera $R$. Solo se aproximan cuando $P(E) < 10\\%$\n\n::: {.callout-note}\n**¿Por qué el OR es la medida más usada en epidemiología?**\n\n1. **Invarianza:** el OR no cambia si intercambiamos filas por columnas (simetría).\n2. **Validez retrospectiva:** en estudios caso-control, el OR es estimable cuando el RR no lo es.\n3. **Conexión con modelos multivariantes:** en regresión logística, $\\exp(\\beta) = OR$.\n:::\n\n*Referencia: Rothman, K. J., Greenland, S., & Lash, T. L. (2008). Modern Epidemiology (3rd ed.). LWW.*\n\n---\n\n## McNemar — Planteamiento del problema\n\n**Ejemplo clínico:** Eficacia de dos terapias para dolor crónico en fibromialgia. n=166 mujeres reciben ambas terapias en orden aleatorizado:\n\n- Terapia A: analgésica\n- Terapia B: terapia física\n\n| | Terapia B: Sí | Terapia B: No |\n|---|---|---|\n| **Terapia A: Sí** | 38 | **15** |\n| **Terapia A: No** | **31** | 82 |\n\n**Interpretación:**\n- 38 responden a ambas (concordantes positivas)\n- 82 no responden a ninguna (concordantes negativas)\n- 15 responden a A pero no a B (discordantes)\n- 31 responden a B pero no a A (discordantes)\n\n::: {.callout-important}\nLas celdas concordantes (38 y 82) **no aportan información diferencial**. El test se basa exclusivamente en las celdas **discordantes** (15 y 31).\n:::\n\n## McNemar — Hipótesis y estadístico\n\n**$H_0$:** Las dos terapias son igualmente eficaces $\\quad \\Leftrightarrow \\quad p_{12} = p_{21}$\n\n**$H_1$:** Las dos terapias **no** son igualmente eficaces\n\n**Condición de validez:** $n_{12} + n_{21} > 10$. En el ejemplo: $15 + 31 = 46 > 10$ ✓\n\n**Estadístico de contraste** (aproximación normal):\n\n$$z_{\\text{exp}} = \\frac{|n_{12} - n_{21}| - 0.5}{\\sqrt{n_{12} + n_{21}}}$$\n\n$$z_{\\text{exp}} = \\frac{|15 - 31| - 0.5}{\\sqrt{15 + 31}} = \\frac{15.5}{6.78} = 2.21$$\n\n**$P = 2 \\times P(Z > 2.21) \\approx 0.027$** → **Rechazamos $H_0$** (las terapias no son iguales)\n\n::: {.callout-tip}\n**Pregunta para reflexionar:** ¿Qué significa $P = 0.027$ en términos clínicos? Si tuvieras que explicárselo a un paciente, ¿cómo lo harías?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn12<-15; n21<-31\nz_exp <- (abs(n12-n21)-0.5)/sqrt(n12+n21)\nP <- 2*(1-pnorm(z_exp))\ncat(\"zexp =\", round(z_exp,3), \"| P =\", round(P,4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nzexp = 2.285 | P = 0.0223\n```\n\n\n:::\n:::\n\n\n## McNemar — Estimación del efecto diferencial\n\n**Proporciones de respuesta:**\n\n$\\hat{p}_A = \\frac{38+15}{166} = 0.319$ (31.9% responden a terapia A)\n\n$\\hat{p}_B = \\frac{38+31}{166} = 0.416$ (41.6% responden a terapia B)\n\n**Diferencia estimada:** $\\hat{p}_A - \\hat{p}_B = -0.095$ (−9.5 puntos porcentuales)\n\n**IC 95% para la diferencia (Agresti-Min):**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn<-166; n12<-15; n21<-31; z_a<-qnorm(0.975)\nd <- (n12-n21)/n\nse <- sqrt((n12+n21) - (n12-n21)^2/n) / n\nIC <- c(d - z_a*se, d + z_a*se)\ncat(\"Diferencia =\", round(d,4), \"| IC95% = (\", round(IC[1],4), \",\", round(IC[2],4), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDiferencia = -0.0964 | IC95% = ( -0.1751 , -0.0177 )\n```\n\n\n:::\n:::\n\n\n**Conclusión:** La terapia B tiene **mayor respuesta** que la A (diferencia −9.5%, IC 95%: −17.4% a −1.7%). Como el IC **no contiene al 0**, la diferencia es significativa ($P = 0.027$).\n\n---\n\n## Protocolo para tablas $r \\times c$ (más de $2 \\times 2$)\n\n::: {.incremental}\n\n1. **Identificar** el tipo de test: 1 muestra → independencia; 2+ → homogeneidad\n2. **Formular** $H_0$ y $H_1$ (homogeneidad o independencia siempre en $H_0$)\n3. Si es $2 \\times 2$ → ir al protocolo específico\n4. **Calcular** frecuencias esperadas: $E_{ij} = F_i \\times C_j / T$\n5. **Comprobar validez:** ninguna $E_{ij} < 1$, no más del 20% con $E_{ij} \\leq 5$\n6. **Calcular** $\\chi^2_{\\text{exp}} = \\sum (O_{ij}-E_{ij})^2/E_{ij}$, gl = $(r-1)(c-1)$\n7. **Obtener P** e interpretar\n8. Si es significativo: analizar causas (porcentajes, residuos)\n\n:::\n\n## Protocolo específico para tablas $2 \\times 2$\n\n::: {.incremental}\n\n1. **Representar** la tabla en formato estándar (enfermedad × FR)\n2. **Identificar** el tipo de estudio: transversal (1 muestra), prospectivo o retrospectivo (2 muestras)\n3. **NO usar** la fórmula general de $\\chi^2$. Usar la fórmula con corrección $c$ adecuada\n4. **Comprobar validez** según el tipo de estudio ($E$ mínimo y corrección $c$)\n5. **Calcular** $\\chi^2_{\\text{exp}}$ y obtener P\n6. Si es significativo: **obtener medidas de asociación** ($d$, $R$, $O$) con IC 95%\n7. Si no es significativo: el IC proporciona idea de la fiabilidad de aceptar $H_0$\n\n:::\n\n## Tipos de estudio — Singularidades y limitaciones\n\n| Característica | **Transversal** | **Prospectivo (Cohortes)** | **Retrospectivo (Casos-Control)** |\n|:--------------|:---------------|:--------------------------|:---------------------------------|\n| **Muestras** | 1 (población) | 2 (expuestos / no expuestos) | 2 (enfermos / no enfermos) |\n| **¿Estima prevalencia?** | ✓ Sí | ✗ No | ✗ No |\n| **¿Estima incidencia?** | ✗ No | ✓ Sí | ✗ No |\n| **¿DR?** | ✓ Sí | ✓ Sí | ✗ No |\n| **¿RR?** | ✓ Sí | ✓ Sí | Aprox. si $P(E) < 10\\%$ |\n| **¿OR?** | ✓ Sí | ✓ Sí | ✓ Sí |\n| **Coste/tiempo** | Bajo | Alto (requiere seguimiento) | Medio |\n| **Causalidad** | No (asociación) | Sí (temporalidad) | No |\n\n::: {.callout-important}\n**Regla:** Antes de analizar una tabla $2 \\times 2$, identificar el tipo de estudio. De ello depende qué medidas se pueden estimar y qué corrección $c$ usar en el $\\chi^2$.\n:::\n\n\n## Interpretación de medidas de asociación — Rangos y valores nulos\n\n| Medida | Símbolo | Fórmula | Rango | Valor nulo | Significado |\n|:-------|:------:|:--------|:-----:|:----------:|:------------|\n| **Diferencia de Riesgos** | DR | $p_1 - p_2$ | $[-1, +1]$ | **0** | $p_1 = p_2$ |\n| **Riesgo Relativo** | RR | $p_1 / p_2$ | $[0, \\infty)$ | **1** | $p_1 = p_2$ |\n| **Odds Ratio** | OR | $\\frac{O_{11}O_{22}}{O_{12}O_{21}}$ | $[0, \\infty)$ | **1** | Igualdad de odds |\n\n**Interpretación según el valor:**\n\n| Valor | DR (escala aditiva) | RR / OR (escala multiplicativa) |\n|:------|:-------------------|:-------------------------------|\n| **Nulo** | DR = 0 | RR = 1, OR = 1 |\n| <span style=\"color:#b2182b\">**Factor de riesgo**</span> | DR > 0 | RR > 1, OR > 1 |\n| <span style=\"color:#2166ac\">**Factor protector**</span> | DR < 0 | 0 < RR < 1, 0 < OR < 1 |\n\n## ¿Cuándo el IC Indica No Significación?\n\n::: {.callout-important}\n**Regla fundamental para interpretar IC de medidas de asociación:**\n\n| Medida | Escala | Valor nulo | **No significativo** | **Significativo** |\n|:-------|:------|:----------:|:--------------------|:------------------|\n| **DR** | Aditiva | **0** | IC contiene al 0 | IC no contiene al 0 |\n| **RR** | Multiplicativa | **1** | IC contiene al 1 | IC no contiene al 1 |\n| **OR** | Multiplicativa | **1** | IC contiene al 1 | IC no contiene al 1 |\n:::\n\n**Ejemplos con datos clínicos de fisioterapia:**\n\n| Medida | Estimación | IC 95% | ¿Significativo? | Interpretación |\n|:-------|:----------:|:-------|:---------------:|---------------|\n| DR (ejercicio vs control) | +0.15 | (+0.03, +0.27) | **Sí** (0 no está en IC) | Ejercicio aumenta mejoría 15pp |\n| RR (ejercicio vs control) | 1.50 | (0.85, 2.65) | **No** (1 está en IC) | Sin evidencia suficiente |\n| OR (fumar vs no fumar) | 3.77 | (1.95, 7.30) | **Sí** (1 no está en IC) | Asociación significativa |\n| DR (terapia A vs B) | 0.05 | (−0.18, +0.08) | **No** (0 está en IC) | Sin diferencia significativa |\n\n::: {.callout-tip}\n**Para estudiantes:** Escala aditiva (DR) → pensar en **0**. Escala multiplicativa (RR/OR) → pensar en **1**. Si el IC contiene ese número → no significativo. Si no lo contiene → significativo.\n:::\n\n---\n\n## Extensiones y consideraciones avanzadas\n\n::: {.callout-note}\n**Más allá del $\\chi^2$ básico:** en esta sección exploramos alternativas para muestras pequeñas (Fisher), medidas de impacto clínico (NNT) y la importancia de la estratificación (Paradoja de Simpson).\n:::\n\n## Test exacto de Fisher — Alternativa para muestras pequeñas\n\n::: {.callout-warning}\n**Cuándo usar Fisher en vez de χ²:** Si alguna frecuencia esperada es < 5 (o < 1), el test χ² no es válido. Usar el test exacto de Fisher [@fisher1922].\n:::\n\n**Ejemplo clínico:** Estudio piloto (n=20) de eficacia de terapia manual para cefalea tensional.\n\n| | Mejoría | No mejoría |\n|---|:---:|:---:|\n| **Terapia manual** | 8 | 2 |\n| **Control** | 3 | 7 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatriz <- matrix(c(8, 2, 3, 7), nrow=2, byrow=TRUE)\nrownames(matriz) <- c(\"Terapia\", \"Control\")\ncolnames(matriz) <- c(\"Mejoría\", \"No mejoría\")\n# Chi-cuadrado: frecuencias esperadas\ncat(\"Frecuencias esperadas:\\n\"); print(round(chisq.test(matriz)$expected, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrecuencias esperadas:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Mejoría No mejoría\nTerapia     5.5        4.5\nControl     5.5        4.5\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fisher exact test\nfisher.test(matriz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  matriz\np-value = 0.06978\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n   0.8821175 127.0558418\nsample estimates:\nodds ratio \n  8.153063 \n```\n\n\n:::\n:::\n\n\n**Interpretación:** Con muestras tan pequeñas (n=20), el test exacto de Fisher es más fiable que el χ². Si P < 0.05, hay asociación significativa entre terapia y mejoría.\n\n## ¿Qué Hay Detrás del Test Exacto de Fisher?\n\n::: {.callout-tip}\n**Idea clave:** Fisher calcula la probabilidad **exacta** de obtener una tabla tan o más extrema que la observada, sin usar ninguna aproximación.\n:::\n\n### 1. ¿Por qué \"exacto\"?\n\nEl χ² tradicional usa una aproximación (la distribución χ² es una aproximación de la verdadera distribución del estadístico). Con muestras pequeñas, esta aproximación falla. Fisher evita la aproximación: calcula directamente la probabilidad de la tabla observada.\n\n### 2. La distribución hipergeométrica — El motor matemático\n\nImagina que fijas todos los **márgenes** de la tabla (totales por fila y columna). La pregunta es: ¿de cuántas formas distintas pueden distribuirse los pacientes en las celdas **manteniendo esos totales fijos**?\n\n$$\nP(\\text{tabla}) = \\frac{\\binom{a+b}{a}\\binom{c+d}{c}}{\\binom{n}{a+c}} = \\frac{(a+b)!(c+d)!(a+c)!(b+d)!}{a!b!c!d!n!}\n$$\n\ndonde $a, b, c, d$ son las 4 celdas y $n = a+b+c+d$.\n\n::: {.callout-note}\n**Para el estudiante de fisioterapia:** No necesitas memorizar la fórmula. Lo importante es entender que Fisher calcula la probabilidad de **cada posible tabla** con los mismos totales de fila y columna, y luego suma las probabilidades de todas las tablas **tan o más extremas** que la observada. Esa suma es el P-valor.\n:::\n\n### 3. ¿Qué hace `fisher.test()` en R?\n\nPara nuestra tabla (Terapia: 8 mejoría / 2 no; Control: 3 / 7):\n\n1. **Fija los márgenes:** Terapia = 10, Control = 10, Mejoría = 11, No mejoría = 9\n2. **Enumera todas las tablas posibles** manteniendo esos totales (desde la más favorable a terapia hasta la más favorable a control)\n3. **Calcula la probabilidad** de cada tabla usando la fórmula hipergeométrica\n4. **Suma** las probabilidades de las tablas con efecto $\\geq$ al observado\n5. **Devuelve la suma** → ese es el P-valor exacto\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ilustración conceptual: todas las tablas posibles con los mismos márgenes\n# fisher.test() hace esto internamente:\n# Tabla más extrema a favor de terapia: 10 mejoría / 0 no; Control 1 / 9\n# Tabla más extrema a favor de control:  1 mejoría / 9 no; Control 10 / 0\n# La nuestra:                              8 mejoría / 2 no; Control 3 / 7\n# P-valor = P(nuestra tabla) + P(tablas aún más extremas)\n```\n:::\n\n\n### 4. La intuición clínica\n\nPiensa en una urna con 11 bolas rojas (mejoría) y 9 azules (no mejoría). Sacas 10 bolas al azar para el grupo de terapia. ¿Cuál es la probabilidad de sacar 8 o más rojas solo por azar? Fisher responde esta pregunta **exactamente**, sin necesidad de que el tamaño muestral sea grande.\n\n*¿Por qué el test de Fisher no depende de frecuencias esperadas ≥ 5? Porque no usa ninguna aproximación asintótica — calcula la probabilidad directamente a partir de la combinatoria.*\n\n## Nnt — Número necesario a tratar\n\n::: {.formula-box}\n$$\\NNT = \\frac{1}{|\\DR|} = \\frac{1}{|p_1 - p_2|}$$\n:::\n\n**Interpretación:** NNT = número de pacientes que necesitas tratar con la terapia experimental (vs control) para que **un paciente adicional** se beneficie.\n\n| NNT | Interpretación |\n|:---:|:---|\n| 1–5 | Efecto muy grande |\n| 5–10 | Efecto moderado |\n| 10–20 | Efecto pequeño |\n| > 20 | Efecto muy pequeño |\n\n**Ejemplo:** Electroterapia: 60% mejoría. Ejercicio solo: 36% mejoría.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- 0.60; p2 <- 0.36\nDR <- p1 - p2\nNNT <- 1 / abs(DR)\ncat(\"DR =\", round(DR, 3), \"\\nNNT =\", round(NNT, 1),\n    \"\\n→ Necesitas tratar\", ceiling(NNT), \"pacientes con electroterapia\",\n    \"\\n  para que 1 adicional mejore respecto a ejercicio solo\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDR = 0.24 \nNNT = 4.2 \n→ Necesitas tratar 5 pacientes con electroterapia \n  para que 1 adicional mejore respecto a ejercicio solo\n```\n\n\n:::\n:::\n\n\n## Confusión (Confounding) y paradoja de simpson\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.callout-note}\n**Confusión:** una tercera variable $Z$ asociada simultáneamente con la exposición $X$ y el desenlace $Y$ distorsiona la asociación real. $Z$ **no** es un paso intermedio en la cadena causal $X \\rightarrow Y$.\n:::\n\n**Ejemplos en fisioterapia:**\n- **Gravedad del paciente:** a mayor gravedad, más probable recibir tratamiento intensivo (exposición) y peor pronóstico (desenlace)\n- **Edad:** a mayor edad, distinta indicación terapéutica y distinta tasa de recuperación\n- **Nivel de actividad física basal:** condiciona tanto el tipo de lesión como la respuesta al tratamiento\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.callout-warning}\n**Paradoja de Simpson:** la asociación en datos **agregados** puede **invertirse** al estratificar por una variable confundente [@simpson1951].\n:::\n\n**¿Por qué ocurre?** Porque los tamaños de los subgrupos son distintos. Si un grupo (ej: hospital A) atiende más casos graves, su tasa global de éxito se ve lastrada — aunque sea mejor en cada subgrupo por separado.\n\n:::\n:::\n\n**Control del confounding:**\n- **En el diseño:** aleatorización (elimina confusión conocida y desconocida), restricción, emparejamiento\n- **En el análisis:** estratificación (Mantel-Haenszel), ajuste por regresión\n\n## Paradoja de simpson — Ejemplo visual en fisioterapia\n\n**Contexto:** Dos fisioterapeutas (A y B) tratan pacientes con lumbalgia. Comparan sus tasas de éxito.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3.5, 1))\n\n# --- Datos ---\n# Agregado: A: 160/200 = 80%, B: 90/100 = 90%\n# Estratificado por gravedad:\n# Leves:  A = 155/160 (96.9%), B = 85/90 (94.4%)\n# Graves: A =   5/40  (12.5%), B =  5/10 (50.0%)\n\n# Panel 1: Datos agregados\nbp1 <- barplot(c(80, 90), names = c(\"Fisio A\", \"Fisio B\"),\n               col = c(\"#3498db\", \"coral\"), ylim = c(0, 100),\n               main = \"Datos Agregados\", ylab = \"% Éxito\",\n               cex.main = 1.1, cex.axis = 0.9)\ntext(bp1, c(80, 90) + 4, labels = c(\"160/200\\n(80%)\", \"90/100\\n(90%)\"),\n     cex = 0.85, font = 2)\nmtext(\"→ B parece mejor\", side = 1, line = 2.5, cex = 0.8, col = \"coral\", font = 2)\n\n# Panel 2: Leves\nbp2 <- barplot(c(96.9, 94.4), names = c(\"Fisio A\\n(n=160)\", \"Fisio B\\n(n=90)\"),\n               col = c(\"#3498db\", \"coral\"), ylim = c(0, 100),\n               main = \"Casos LEVES\", ylab = \"% Éxito\",\n               cex.main = 1.1, cex.axis = 0.9)\ntext(bp2, c(96.9, 94.4) + 4, labels = c(\"155/160\\n(96.9%)\", \"85/90\\n(94.4%)\"),\n     cex = 0.85, font = 2)\nmtext(\"→ A ligeramente mejor\", side = 1, line = 2.5, cex = 0.8, col = \"#3498db\", font = 2)\n\n# Panel 3: Graves\nbp3 <- barplot(c(12.5, 50), names = c(\"Fisio A\\n(n=40)\", \"Fisio B\\n(n=10)\"),\n               col = c(\"#3498db\", \"coral\"), ylim = c(0, 100),\n               main = \"Casos GRAVES\", ylab = \"% Éxito\",\n               cex.main = 1.1, cex.axis = 0.9)\ntext(bp3, c(12.5, 50) + 4, labels = c(\"5/40\\n(12.5%)\", \"5/10\\n(50.0%)\"),\n     cex = 0.85, font = 2)\nmtext(\"→ B mejor, pero solo 10 casos\", side = 1, line = 2.5, cex = 0.8, col = \"coral\", font = 2)\n```\n\n::: {.cell-output-display}\n![](T05_ChiCuadrado_files/figure-revealjs/unnamed-chunk-16-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-important}\n**La paradoja explicada:** El Fisio A atiende **40 casos graves** (20% de su carga), mientras que el Fisio B solo atiende **10** (10%). Los casos graves tienen peor pronóstico. La desigualdad en la composición de pacientes arrastra la tasa global de A hacia abajo, creando la ilusión de que B es mejor cuando en realidad A obtiene mejores resultados en pacientes leves (y la aparente ventaja de B en graves se basa en solo 10 pacientes).\n:::\n\n**Lección clínica:** Antes de comparar resultados entre profesionales, servicios o estudios, estratifica siempre por gravedad, edad u otros factores pronósticos. La estadística de Mantel-Haenszel proporciona una medida de asociación ajustada que combina la información de todos los estratos.\n\n---\n\n# Resumen {.center}\n\n::: {.incremental}\n\n1. **$\\chi^2$ de Pearson:** compara frecuencias observadas vs esperadas: $E_{ij} = F_i \\times C_j / T$\n\n2. **Homogeneidad** (2+ muestras) vs **Independencia** (1 muestra) — misma mecánica\n\n3. **Condiciones de validez:** $E_{ij} \\geq 1$ y < 20% con $E_{ij} \\leq 5$\n\n4. **Tablas $2 \\times 2$:** fórmula especial con corrección $c$. Tres tipos de estudio epidemiológico\n\n5. **Medidas de asociación:** $d$ (riesgo absoluto), $R$ (riesgo relativo), $O$ (odds ratio)\n\n6. **El Odds Ratio** es la medida por excelencia — válido en cualquier tipo de estudio\n\n7. **McNemar:** para proporciones apareadas — solo usa celdas discordantes\n\n8. **Residuos estandarizados:** $|R_{ij}| > 1.96$ identifica las celdas responsables de la significación\n\n:::\n\n## Interpretación de la salida de BioEstatR para $\\chi^2$\n\n**Ejemplo: `t2x2(tabla)` para el estudio de fumar y bajo peso:**\n\n```\nTest Chi-cuadrado para tabla 2x2\nχ² = 17.90, gl = 1, P < 0.001\n\nMedidas de asociación:\nOR = 3.77 (IC 95%: 1.95 a 7.30)\nRR = 3.08 (IC 95%: 1.73 a 5.47)\nDR = 0.169 (IC 95%: 0.07 a 0.27)\n\nInterpretación: Asociación significativa (P < 0.001).\nLa odds de bajo peso es 3.77 veces mayor en madres fumadoras.\n```\n\n**Cómo leer la salida:**\n- **$\\chi^2$ y P:** P < 0.001 → asociación significativa\n- **OR = 3.77:** la odds es casi 4 veces mayor en expuestos\n- **IC del OR:** (1.95, 7.30) no contiene 1 → significativo\n- **DR = 0.169:** 16.9 puntos porcentuales más de bajo peso en fumadoras\n\n::: {.callout-tip}\n**Regla de oro:** IC de OR/RR contiene 1 → no significativo. IC de DR contiene 0 → no significativo. Si el IC no toca el valor nulo, la asociación es significativa.\n:::\n\n## Derivación del estadístico $\\chi^2$ desde sus fundamentos\n\n::: {.callout-tip}\n**Material complementario (opcional).** La siguiente derivación asume conocimientos de distribuciones binomial y normal que exceden el nivel requerido para el Grado en Fisioterapia.\n:::\n\n**¿De dónde sale $\\chi^2 = \\sum (O-E)^2/E$?**\n\n::: {.callout-note}\nPearson (1900) demostró que, bajo $H_0$, el estadístico $\\sum (O_i-E_i)^2/E_i$ sigue una distribución $\\chi^2$. La idea clave: cada celda aporta una normal estándar al cuadrado.\n:::\n\n**Paso 1 — Aproximación Normal:** En cada celda, $O_{ij} \\sim \\text{Binomial}(T, p_{ij})$. Para $T$ grande: $O_{ij} \\approx N(E_{ij}, E_{ij}(1-p_{ij})) \\approx N(E_{ij}, E_{ij})$ cuando $p_{ij}$ es pequeño.\n\n**Paso 2 — Estandarización:** $Z_{ij} = \\frac{O_{ij} - E_{ij}}{\\sqrt{E_{ij}}} \\approx N(0,1)$ bajo $H_0$\n\n**Paso 3 — Suma de normales al cuadrado:**\n$$\\chi^2 = \\sum_{i=1}^{r} \\sum_{j=1}^{c} \\frac{(O_{ij} - E_{ij})^2}{E_{ij}}$$\n\nLos totales de filas y columnas son fijos → solo $(r-1)(c-1)$ de las $Z_{ij}$ son independientes → $\\text{gl} = (r-1)(c-1)$.\n\n**Paso 4 — Ejemplo numérico (celda 1,1 del ejemplo de 4 tratamientos):**\n$Z_{11}^2 = (7-9.91)^2/9.91 = 0.855$. Sumando las 12 celdas: $\\chi^2_{12} = 13.87$, $P = 0.031$.\n\n## Puente al tema 6 — De la asociación a la predicción\n\n::: {.callout-important}\n**El test $\\chi^2$ detecta asociación entre variables categóricas. La regresión (Tema 6) modela la relación funcional entre variables.**\n:::\n\n| Característica | $\\chi^2$ (T5) | Regresión (T6) |\n|:---------------|:--------------|:---------------|\n| **Variables** | Ambas categóricas | Ambas continuas (o mixtas) |\n| **¿Qué mide?** | Asociación (¿están relacionadas?) | Relación funcional (¿cómo?) |\n| **Resultado** | P-valor, OR, RR | $\\beta_0, \\beta_1, R^2$, predicciones |\n| **Ejemplo** | ¿Fumar se asocia con bajo peso? | ¿Cuánto aumenta el ROM por sesión? |\n\n**Progresión natural del análisis:**\n1. $\\chi^2$ dice **SI** hay asociación → screening inicial\n2. Regresión dice **CUÁNTO** cambia $Y$ por cada unidad de $X$ → cuantificación\n3. Ambas comparten la misma lógica inferencial: $H_0$, estadístico, P-valor, IC\n\n::: {.exercise}\n## Ejercicio clínico — Análisis de tablas 2×2\n\nUn fisioterapeuta estudia si la práctica de ejercicio terapéutico supervisado (vs. ejercicio en casa) se asocia con la recuperación funcional a los 3 meses en pacientes con artrosis de cadera:\n\n| Ejercicio | Recupera | No recupera | Total |\n|:----------|:--------:|:-----------:|:-----:|\n| Supervisado | 42 | 8 | 50 |\n| En casa | 28 | 22 | 50 |\n| **Total** | **70** | **30** | **100** |\n\n1. ¿Qué tipo de estudio es? Identifica las medidas de asociación apropiadas.\n2. Calcula OR, RR y sus IC 95% usando `tabla2x2()` de BioEstatR. Interpreta.\n3. Realiza el test $\\chi^2$. ¿Es significativa la asociación? ¿Hay confusión por gravedad inicial?\n:::\n\n## Referencias\n\n::: {.reference-box}\n- [@bioestatr2026] — Femia, P. & Luque-Fernández, M. A. (2026). *BioEstatR: Biostatistics Routines in R*. R package. Universidad de Granada.\n- [@luque2026] — Luque-Fernández, M. A. (2026). *Matemáticas para la Estadística Médica con R*. Universidad de Granada.\n- [@pearson1900] — Pearson, K. (1900). On the criterion that a given system of deviations... *Phil. Mag.*, 50(302), 157–175.\n- [@fisher1922] — Fisher, R. A. (1922). On the interpretation of χ² from contingency tables. *J. R. Stat. Soc.*, 85(1), 87–94.\n- [@yates1934] — Yates, F. (1934). Contingency tables involving small numbers. *J. R. Stat. Soc.*, 1(2), 217–235.\n- [@mcnemar1947] — McNemar, Q. (1947). Note on the sampling error of the difference between correlated proportions. *Psychometrika*, 12(2), 153–157.\n- [@mantel1959] — Mantel, N. & Haenszel, W. (1959). Statistical aspects of the analysis of data from retrospective studies. *JNCI*, 22(4), 719–748.\n- [@cornfield1951] — Cornfield, J. (1951). A method of estimating comparative rates. *JNCI*, 11, 1269–1275.\n- [@simpson1951] — Simpson, E. H. (1951). The interpretation of interaction in contingency tables. *J. R. Stat. Soc. B*, 13(2), 238–241.\n- [@woolf1955] — Woolf, B. (1955). On estimating the relation between blood group and disease. *Ann. Hum. Genet.*, 19(4), 251–253.\n- [@agresti2013] — Agresti, A. (2013). *Categorical Data Analysis* (3rd ed.). Wiley.\n- [@rothman2008] — Rothman, K. J., Greenland, S. & Lash, T. L. (2008). *Modern Epidemiology* (3rd ed.). LWW.\n:::\n---\n\n---\n\n## Ejercicio Clínico — Tema V\n\n**Contexto:** Asociación tipo fisioterapia × mejoría (n=100). Manual: 35/50 mejoran. Ejercicio: 25/50.\n\n1. Calcula OR de mejoría (manual vs ejercicio)\n2. Interpreta\n3. ¿Qué test de contraste?\n\n::: {.callout-tip collapse=\"true\"}\n**Solución**\n\n1. $OR = \\frac{35 \\times 25}{15 \\times 25} = \\frac{875}{375} = \\mathbf{2.33}$\n2. Terapia manual tiene 2.33× más odds de mejorar. $P < 0.05$ → significativo\n3. $\\chi^2$ de Pearson (frecuencias esperadas $> 5$)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla <- matrix(c(35, 25, 15, 25), nrow=2,\n                dimnames=list(c(\"Manual\",\"Ejercicio\"), c(\"Mejoria\",\"No mejoria\")))\nchi <- chisq.test(tabla, correct=FALSE)\nOR <- 35*25/(15*25)\n\npar(mfrow=c(1,2), mar=c(4,4,4,1))\n# Panel 1: Barras agrupadas\nbarplot(tabla, beside=TRUE, col=c(\"steelblue\",\"coral\"),\n        main=paste0(\"OR = \", round(OR,2)), ylab=\"Frecuencia\", ylim=c(0,40))\nlegend(\"topright\", c(\"Manual\",\"Ejercicio\"), fill=c(\"steelblue\",\"coral\"), bty=\"n\", cex=0.8)\n# Panel 2: Mosaic\nmosaicplot(t(tabla), main=\"Mosaic: Tipo × Mejoría\", color=c(\"coral\",\"steelblue\"))\n```\n\n::: {.cell-output-display}\n![](T05_ChiCuadrado_files/figure-revealjs/unnamed-chunk-17-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n\ncat(\"OR =\", round(OR,2), \"χ² =\", round(chi$statistic,2),\n    \"gl =\", chi$parameter, \"P =\", round(chi$p.value,4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOR = 2.33 χ² = 4.17 gl = 1 P = 0.0412\n```\n\n\n:::\n:::\n\n:::\n",
    "supporting": [
      "T05_ChiCuadrado_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}