{
  "hash": "d37bce6886ec875efc0a733ec68cdb68",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión y Correlación\"\nsubtitle: \"Tema VI — Modelos de Regresión Lineal Simple\"\nauthor:\n  - name: \"Miguel Angel Luque-Fernández\"\n    affiliation: \"Dpto. Estadística e Investigación Operativa, Universidad de Granada\"\n    email: \"mluquefe@ugr.es\"\n    url: \"https://migariane.github.io\"\ndate: \"2026\"\nlicense: \"CC BY 4.0\"\nformat:\n  revealjs:\n    slide-number: c/t\n    code-fold: true\n    code-summary: \"Mostrar código R\"\n    code-copy: true\n    code-overflow: wrap\n    fig-align: center\n    fig-width: 9\n    fig-height: 5.2\n    lang: es\nexecute:\n  warning: false\n  message: false\n  echo: true\n  eval: true\n---\n\n# Regresión y Correlación {.center}\n\n![](logo.png){width=\"90px\"}\n\n**Grado en Fisioterapia**\n\n**CC BY 4.0** · Miguel Angel Luque-Fernández\n\n[Miguel Angel Luque-Fernández](https://migariane.github.io) · [maluque.netlify.app](https://maluque.netlify.app)\n\nDpto. Estadística e Investigación Operativa · Universidad de Granada\n\n\n## Objetivos de aprendizaje — Tema 6\n\n::: {.callout-tip}\n**Al finalizar este tema sabrás:**\n:::\n\n::: {.incremental}\n1. Interpretar un diagrama de dispersión y el coeficiente de correlación $r$\n2. Estimar e interpretar los coeficientes de regresión $\\beta_0$ y $\\beta_1$\n3. Evaluar el ajuste del modelo con $R^2$ y gráficos de residuos\n4. Distinguir entre IC (media) e IP (individuo) para predicciones\n5. Recordar que correlación no implica causalidad\n6. Usar `rls()` y `rlsm()` de BioEstatR para regresión en una línea\n:::\n\n\n## Motivación: Imc y porcentaje de masa grasa\n\n**Muestra de 12 adolescentes (15–19 años)**\n\n| IMC | % Graso | | IMC | % Graso |\n|-----|---------|---|-----|---------|\n| 20.36 | 17.36 | | 21.72 | 25.62 |\n| 20.34 | 12.72 | | 19.29 | 20.91 |\n| 20.05 | 11.65 | | 23.07 | 17.81 |\n| 23.94 | 19.34 | | 27.45 | 29.70 |\n| 22.17 | 24.19 | | 24.37 | 15.26 |\n| 22.18 | 28.41 | | 17.30 | 8.87 |\n\n::: {.incremental}\n\n- ¿Existe **relación** entre IMC y % de masa grasa?\n- De ser así, ¿es **intensa**? ¿Existe algún **modelo** que permita caracterizarla?\n- Sabiendo el IMC, ¿es posible hacer un **pronóstico** del % graso?\n- En tal caso, ¿es **fiable** tal pronóstico?\n\n:::\n\n## Correlación vs. regresión\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n### Correlación\n- Cuantifica la **fuerza** de la asociación entre dos variables\n- **Coeficiente de correlación** ($r$)\n- **Simétrica:** no distingue rol de variables\n- No implica causalidad\n- Solo mide asociación **lineal**\n\n:::\n\n::: {.column width=\"50%\"}\n\n### Regresión\n- **Modela** cómo cambia una variable ($y$) al cambiar otra ($x$)\n- Ecuación: $y = f(x)$\n- **Asimétrica:** distingue variable explicativa ($x$) y explicada ($y$)\n- Permite **predecir** valores de $y$ a partir de $x$\n- Permite cuantificar el **efecto** de $x$ sobre $y$\n\n:::\n:::\n\n## El diagrama de dispersión: Primer paso siempre\n\n::: {.callout-important}\nAntes de cualquier análisis numérico: **visualizar** la relación.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimc <- c(20.36,20.34,20.05,23.07,23.94,27.45,\n         22.17,24.37,22.18,17.30,21.72,19.29)\ngraso <- c(17.36,12.72,11.65,17.81,19.34,29.70,\n           24.19,15.26,28.41,8.87,25.62,20.91)\n\nplot(imc, graso, pch=19, col=\"steelblue\", cex=1.5,\n     xlab=\"IMC (kg/m²)\", ylab=\"% Masa Grasa\",\n     main=\"IMC vs. % Masa Grasa (n=12)\")\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-1-1.png){width=864}\n:::\n:::\n\n\n## Qué observar en el diagrama de dispersión\n\n::: {.incremental}\n\n1. **¿Hay relación?** → ¿Los puntos siguen algún patrón o es una nube informe?\n\n2. **¿Lineal o no lineal?** → ¿Forma de recta o curva?\n\n3. **¿Directa o inversa?** → Al aumentar $x$, ¿aumenta (+) o disminuye (−) $y$?\n\n4. **¿Homocedasticidad?** → ¿La dispersión de $y$ es constante para todo $x$?\n\n5. **¿Valores atípicos?** → ¿Hay puntos que se alejan del patrón general?\n\n6. **¿Observaciones influyentes?** → ¿Algún punto modifica sustancialmente la recta?\n\n:::\n\n## Diagnóstico visual: Patrones típicos\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,3), mar=c(4,4,3,1))\nset.seed(123); n <- 50\n\n# 1. Relación lineal directa\nx <- rnorm(n); y <- 2*x + rnorm(n,0,0.5)\nplot(x,y,pch=19,col=\"steelblue\",main=\"Lineal directa (+)\",xlab=\"x\",ylab=\"y\")\nabline(lm(y~x),col=\"darkgreen\",lwd=2)\n\n# 2. Relación lineal inversa\ny2 <- -2*x + rnorm(n,0,0.5)\nplot(x,y2,pch=19,col=\"seagreen\",main=\"Lineal inversa (−)\",xlab=\"x\",ylab=\"y\")\nabline(lm(y2~x),col=\"darkgreen\",lwd=2)\n\n# 3. Relación no lineal\ny3 <- x^2 + rnorm(n,0,1)\nplot(x,y3,pch=19,col=\"seagreen\",main=\"No lineal (curva)\",xlab=\"x\",ylab=\"y\")\n\n# 4. Sin relación\ny4 <- rnorm(n,0,1)\nplot(x,y4,pch=19,col=\"grey50\",main=\"Sin relación\",xlab=\"x\",ylab=\"y\")\n\n# 5. Heterocedasticidad\ny5 <- x + rnorm(n,0,abs(x)*0.8)\nplot(x,y5,pch=19,col=\"seagreen\",main=\"Heterocedasticidad\",xlab=\"x\",ylab=\"y\")\n\n# 6. Valor atípico\ny6 <- 2*x + rnorm(n,0,0.5); y6[50] <- y6[50]+6\nplot(x,y6,pch=19,col=ifelse(1:n==50,\"coral\",\"steelblue\"),\n     main=\"Con valor atípico\",xlab=\"x\",ylab=\"y\")\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-2-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n## Roles de las variables y tipos de muestreo\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n### Muestreo Tipo I (Observacional)\n- Muestra aleatoria → se observan **ambas** variables\n- Los roles $x$ e $y$ son **intercambiables**\n- Solo permite hablar de **asociación** (covariación), **no de causalidad**\n\n**Ejemplo:** Medir IMC y % graso en una muestra aleatoria de adolescentes.\n\n:::\n\n::: {.column width=\"50%\"}\n\n### Muestreo Tipo II (Experimental)\n- Se **fijan** los valores de $x$ → se observa $y$\n- Los roles **no** son intercambiables\n- Permite establecer relaciones **causales**\n\n**Ejemplo:** Fijar dosis de fármaco ($x$) y medir respuesta ($y$).\n\n:::\n:::\n\n::: {.callout-important}\n**Asociación no implica causalidad.** Ejemplo clásico: estatura y destreza motriz en niños — ambas aumentan con la edad, pero no hay relación causal directa (asociación **espuria**).\n:::\n\n## ¿Cómo Funciona la Regresión? — Intuición Visual\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123); n <- 30\nx <- runif(n, 4, 14)\ny <- 2 + 0.6*x + rnorm(n, 0, 2)\nmodelo <- lm(y ~ x)\n\npar(mfrow=c(1,2), mar=c(4,4,3,1))\n# Panel 1: Solo puntos — difícil ver patrón\nplot(x, y, pch=19, col=\"grey60\", cex=1.3, main=\"Paso 1: ¿Hay relación?\",\n     xlab=\"Sesiones de fisioterapia\", ylab=\"Mejoría EVA\")\n# Panel 2: Con recta de regresión\nplot(x, y, pch=19, col=\"steelblue\", cex=1.3, main=\"Paso 2: La recta resume la relación\",\n     xlab=\"Sesiones de fisioterapia\", ylab=\"Mejoría EVA\")\nabline(modelo, col=\"darkgreen\", lwd=3)\n# Mostrar residuos\nfor(i in 1:n) lines(c(x[i],x[i]), c(y[i], fitted(modelo)[i]), col=\"grey60\", lty=3)\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-3-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**La regresión encuentra la recta que minimiza la suma de distancias verticales al cuadrado (residuos).**\n\n# El Modelo de Regresión Lineal {.center}\n\n::: {.connection}\n**Conexión T01→T06:** En T01 describiste variables individuales. En T05 detectaste asociación entre variables **categóricas** ($\\chi^2$, OR, RR). En T06 modelas y cuantificas la relación entre variables **continuas**. La regresión une descripción (T1), probabilidad (T2), estimación (T3), contraste (T4) y asociación (T5) en un solo marco.\n:::\n\n\n## Comprueba tu comprensión — Covarianza\n\n::: {.callout-tip}\n**Pregunta rápida:** Si dos variables clínicas tienen covarianza negativa, ¿qué significa? Da un ejemplo en fisioterapia donde esperarías encontrar covarianza negativa.\n:::\n\n## Covarianza — La base de la regresión\n\n**Definición:** La covarianza mide cómo dos variables **varían conjuntamente**:\n\n$$\\Cov(X, Y) = \\frac{1}{n-1}\\sum_{i=1}^{n} (x_i - \\bar{x})(y_i - \\bar{y}) = \\frac{S_{xy}}{n-1}$$\n\n**Interpretación intuitiva:**\n- $\\Cov(X,Y) > 0$: $X$↑ → $Y$↑ (**relación directa**)\n- $\\Cov(X,Y) < 0$: $X$↑ → $Y$↓ (**relación inversa**)\n- $\\Cov(X,Y) = 0$: no hay relación lineal\n\n**Relación con la pendiente:** $\\hat{\\beta}_1 = \\frac{\\Cov(X,Y)}{\\Var(X)} = \\frac{S_{xy}}{S_{xx}}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-c(4,5,8,10,12); y<-c(2,3,5,6,7)\ncat(\"Covarianza =\", round(cov(x,y),3),\n    \"\\nVar(X) =\", round(var(x),3),\n    \"\\nb1 = Cov/Var =\", round(cov(x,y)/var(x),3),\n    \"\\nlm() b1 =\", round(coef(lm(y~x))[2],3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCovarianza = 6.9 \nVar(X) = 11.2 \nb1 = Cov/Var = 0.616 \nlm() b1 = 0.616\n```\n\n\n:::\n:::\n\n\n**La covarianza indica la DIRECCIÓN de la relación.**\n\n## De la covarianza a la pendiente de regresión\n\n**Relación con la pendiente:** $\\hat{\\beta}_1 = \\frac{\\Cov(X,Y)}{\\Var(X)} = \\frac{S_{xy}}{S_{xx}}$\n\n::: {.callout-note}\n**Intuición:** La covarianza te dice si $X$ e $Y$ van en la misma dirección (positiva) o en direcciones opuestas (negativa). La pendiente $\\hat{\\beta}_1$ va un paso más allá: te dice **cuánto** cambia $Y$ por cada unidad de cambio en $X$.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-c(4,5,8,10,12); y<-c(2,3,5,6,7)\ncat(\"Covarianza =\", round(cov(x,y),3),\n    \"\\nVar(X) =\", round(var(x),3),\n    \"\\nb1 = Cov/Var =\", round(cov(x,y)/var(x),3),\n    \"\\nlm() b1 =\", round(coef(lm(y~x))[2],3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCovarianza = 6.9 \nVar(X) = 11.2 \nb1 = Cov/Var = 0.616 \nlm() b1 = 0.616\n```\n\n\n:::\n:::\n\n\n**La covarianza indica la DIRECCIÓN de la relación; la pendiente cuantifica su MAGNITUD.**\n\n## $S_{xx}$, $S_{xy}$, $S_{yy}$ — Los Tres Pilares de la Regresión\n\n::: {.callout-note}\n**Conexión T03→T06:** En el Tema 3 usaste $SS$ (suma de cuadrados) para la varianza: $s^2 = \\frac{SS}{n-1}$ donde $SS = \\sum(x_i-\\bar{x})^2$. Aquí $S_{xx}$ es exactamente esa misma cantidad — la suma de cuadrados de $X$. $S_{yy}$ es la suma de cuadrados de $Y$. Y $S_{xy}$ es la suma de **productos cruzados**, una generalización natural a dos variables.\n:::\n\nToda la regresión lineal se construye sobre **tres cantidades fundamentales** que miden la variabilidad de $X$, de $Y$, y su variación conjunta:\n\n::: {.formula-box}\n\n**$\\mathbf{S_{xx}}$** = $\\sum (x_i - \\bar{x})^2$ — Dispersión de $X$ alrededor de su media\n\n**$\\mathbf{S_{yy}}$** = $\\sum (y_i - \\bar{y})^2$ — Dispersión de $Y$ alrededor de su media (= $SC_{tot}$)\n\n**$\\mathbf{S_{xy}}$** = $\\sum (x_i - \\bar{x})(y_i - \\bar{y})$ — Cómo varían $X$ e $Y$ **conjuntamente**\n\n:::\n\n**Intuición geométrica:** $S_{xx}$ es la suma de distancias horizontales al cuadrado. $S_{yy}$ es la suma de distancias verticales al cuadrado. $S_{xy}$ es el producto de ambas: positivo si $x$ e $y$ se mueven en la misma dirección, negativo si van en direcciones opuestas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(4,5,8,10,12); y <- c(2,3,5,6,7)\npar(mfrow=c(1,3), mar=c(4,4,3,1))\n# Sxx\nplot(x, y, pch=19, col=\"grey60\", cex=1.5, main=expression(S[xx]), xlab=\"x\", ylab=\"y\")\nabline(v=mean(x), col=\"steelblue\", lwd=2, lty=2)\nfor(i in 1:5) segments(x[i], y[i], mean(x), y[i], col=\"steelblue\", lwd=2)\ntext(9, 6.5, paste0(\"Sxx = \",round(sum((x-mean(x))^2),1)), col=\"steelblue\", font=2)\n# Syy\nplot(x, y, pch=19, col=\"grey60\", cex=1.5, main=expression(S[yy]), xlab=\"x\", ylab=\"y\")\nabline(h=mean(y), col=\"darkgreen\", lwd=2, lty=2)\nfor(i in 1:5) segments(x[i], y[i], x[i], mean(y), col=\"darkgreen\", lwd=2)\ntext(9, 6.5, paste0(\"Syy = \",round(sum((y-mean(y))^2),1)), col=\"darkgreen\", font=2)\n# Sxy\nplot(x, y, pch=19, col=\"grey60\", cex=1.5, main=expression(S[xy]), xlab=\"x\", ylab=\"y\")\nabline(v=mean(x), col=\"steelblue\", lwd=2, lty=2); abline(h=mean(y), col=\"darkgreen\", lwd=2, lty=2)\nfor(i in 1:5) rect(mean(x), mean(y), x[i], y[i], border=\"coral\", lwd=1.5, lty=2)\ntext(9, 6.5, paste0(\"Sxy = \",round(sum((x-mean(x))*(y-mean(y))),1)), col=\"coral\", font=2)\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-6-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n::: {.callout-important}\n**Memoriza estas tres letras:** $S_{xx}$, $S_{xy}$, $S_{yy}$. Absolutamente **TODO** en regresión lineal simple se construye a partir de ellas: la pendiente, la correlación, el $R^2$, los errores estándar, los intervalos de confianza, los intervalos de predicción, y el test $F$.\n:::\n\n## El modelo de regresión lineal simple\n\n::: {.callout-note}\n\n$$y_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i, \\quad \\varepsilon_i \\sim N(0, \\sigma^2)$$\n\n- $\\beta_0$: **intercepto** — valor esperado de $y$ cuando $x=0$\n- $\\beta_1$: **pendiente** — cambio en $y$ por cada unidad de cambio en $x$\n- $\\varepsilon_i$: **error aleatorio** — lo no explicado por $x$ (variabilidad residual)\n\n:::\n\n**Dos componentes:**\n- **Determinista:** $\\beta_0 + \\beta_1 x_i$ — la recta de regresión\n- **Aleatorio:** $\\varepsilon_i$ — variabilidad no explicada, $N(0,\\sigma^2)$\n\n::: {.callout-tip}\n**Ejemplo rápido — 3 pacientes:** Si tenemos $(x,y)$ = (4,2), (8,5), (12,7):\n- $\\bar{x}=8$, $\\bar{y}=4.67$\n- $\\hat{\\beta}_1 = \\frac{(4-8)(2-4.67)+(8-8)(5-4.67)+(12-8)(7-4.67)}{(4-8)^2+(8-8)^2+(12-8)^2} = \\frac{10.68+0+9.32}{16+0+16} = \\frac{20}{32} = 0.625$\n- $\\hat{\\beta}_0 = 4.67 - 0.625 \\times 8 = -0.33$\n- **Ecuación:** $\\hat{y} = -0.33 + 0.625x$ → por cada sesión extra, ~0.63 puntos de mejoría\n:::\n\n## ¿Por Qué Confiar en Mínimos Cuadrados?\n\n::: {.callout-note}\nEl método de **mínimos cuadrados ordinarios (MCO)** produce la mejor estimación posible de la recta de regresión, siempre que se cumplan unas condiciones razonables.\n\n**Condiciones necesarias (en lenguaje llano):**\n1. **La relación es una línea recta** — no una curva\n2. **Los errores no dependen del valor de $x$** — su media es cero para cualquier $x$\n3. **La dispersión de los errores es constante** — misma variabilidad para todo $x$\n4. **Los errores de distintos pacientes son independientes** — uno no afecta al otro\n5. **Medimos $x$ sin error** (o casi) — como en un experimento controlado\n\n**En fisioterapia:** Al modelar la relación entre sesiones de tratamiento y mejoría funcional, si se cumplen estas condiciones, MCO proporciona la estimación más precisa de cuánto mejora el paciente por cada sesión adicional.\n:::\n\n## Comprueba tu comprensión — Interpretación de la pendiente\n\n::: {.callout-tip}\n**Pregunta rápida:** Un modelo ajusta mejoría EVA = 2.0 + 0.8 × sesiones. ¿Cuánto mejora un paciente por cada 5 sesiones adicionales? ¿Tiene sentido clínico el intercepto ($\\beta_0 = 2.0$) en este contexto si ningún paciente tiene 0 sesiones?\n:::\n\n## Estimación por mínimos cuadrados ordinarios (MCO)\n\n::: {.callout-note}\n**La idea:** Se eligen $\\hat{\\beta}_0$ y $\\hat{\\beta}_1$ que **minimizan** la suma de residuos al cuadrado: encontrar la recta que minimiza las distancias verticales al cuadrado entre los puntos y la recta.\n:::\n\n::: {.framed}\n**Estimadores MCO — construidos sobre los tres pilares:**\n\n$$\\hat{\\beta}_1 = \\frac{S_{xy}}{S_{xx}} = \\frac{\\sum(x_i-\\bar{x})(y_i-\\bar{y})}{\\sum(x_i-\\bar{x})^2} \\qquad \\hat{\\beta}_0 = \\bar{y} - \\hat{\\beta}_1\\bar{x}$$\n\n- $\\hat{\\beta}_1$: \"cuánto varían juntas $X$ e $Y$\" dividido por \"cuánto varía $X$\" = $\\frac{S_{xy}}{S_{xx}}$\n- $\\hat{\\beta}_0$: ajusta la altura para que la recta pase por el centroide $(\\bar{x}, \\bar{y})$\n:::\n\n::: {.callout-tip}\n**Derivación (Opcional — para quien quiera profundizar):** Se deriva $S(\\beta_0,\\beta_1) = \\sum (y_i - \\beta_0 - \\beta_1 x_i)^2$ respecto a $\\beta_0$ y $\\beta_1$, se iguala a cero, y se obtienen las fórmulas de arriba. En este curso **siempre usaremos R** (`lm(y ~ x)`) en lugar de derivar a mano.\n:::\n## Ajuste del modelo en R: Imc vs. % graso\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo <- lm(graso ~ imc)\nsummary(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = graso ~ imc)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-7.893 -3.710 -1.422  4.664  8.592 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)  \n(Intercept) -13.9643    13.7508  -1.016    0.334  \nimc           1.5231     0.6249   2.437    0.035 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.547 on 10 degrees of freedom\nMultiple R-squared:  0.3726,\tAdjusted R-squared:  0.3099 \nF-statistic:  5.94 on 1 and 10 DF,  p-value: 0.03502\n```\n\n\n:::\n:::\n\n\n**Resultados:**\n- $\\hat{\\beta}_0 = -13.50$ (intercepto)\n- $\\hat{\\beta}_1 = 1.52$ (pendiente)\n- $\\hat{\\beta}_0 = -13.50$ (intercepto), $\\hat{\\beta}_1 = 1.52$ (pendiente)\n- $R^2 = 0.671$ (67.1% de variabilidad explicada), Error estándar residual $s = 3.89$\n- $P = 0.001$ (pendiente significativa)\n\n**Interpretación:** Por cada unidad de aumento en el IMC (kg/m²), el % de masa grasa aumenta en **1.52 puntos porcentuales** (IC 95%: 0.77 a 2.28).\n\n## Varianza residual — Lo que el modelo no explica\n\nUna vez estimada la recta, cuantificamos **cuánto se equivoca** el modelo con la varianza residual $s^2$:\n\n::: {.formula-box}\n$$s^2 = \\frac{SC_{res}}{n-2} = \\frac{\\sum_{i=1}^n (y_i - \\hat{y}_i)^2}{n-2}, \\qquad s = \\sqrt{s^2} \\text{ (error estándar residual)}$$\n:::\n\n**¿Por qué $n-2$?** Hemos estimado **2 parámetros** ($\\beta_0$ y $\\beta_1$) → \"gastamos\" 2 grados de libertad. Es el mismo principio que $n-1$ en la varianza muestral (Tema 3), pero con 2 restricciones en lugar de 1.\n\n**En el ejemplo IMC-Graso:** $s = 3.89$ significa que el modelo se equivoca típicamente en $\\pm 3.89$ puntos porcentuales de grasa corporal al predecir desde el IMC.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo <- lm(graso ~ imc)\nresiduos <- residuals(modelo)\nSC_res <- sum(residuos^2); n <- length(imc)\ncat(\"SC_res =\", round(SC_res, 2), \"| n-2 =\", n-2,\n    \"\\ns2 =\", round(SC_res/(n-2), 2),\n    \"| s =\", round(sqrt(SC_res/(n-2)), 2),\n    \"\\nsummary(modelo)$sigma =\", round(summary(modelo)$sigma, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSC_res = 307.73 | n-2 = 10 \ns2 = 30.77 | s = 5.55 \nsummary(modelo)$sigma = 5.55\n```\n\n\n:::\n:::\n\n\n## Interpretación de la pendiente — ¿qué significa $\\beta_1$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,3), mar=c(4,4,3,1))\nset.seed(123)\n\n# β₁ > 0: Relación directa\nx <- 1:20; y1 <- 5 + 0.5*x + rnorm(20,0,1)\nplot(x, y1, pch=19, col=\"steelblue\", main=expression(beta[1]*\" > 0: Relación directa\"),\n     xlab=\"Sesiones\", ylab=\"Mejoría\"); abline(lm(y1~x), col=\"darkgreen\", lwd=3)\ntext(15, 8, \"Más sesiones →\\nmás mejoría\", col=\"darkgreen\", cex=1.1, font=2)\n\n# β₁ = 0: Sin relación\ny2 <- 10 + 0*x + rnorm(20,0,2)\nplot(x, y2, pch=19, col=\"steelblue\", main=expression(beta[1]*\" = 0: Sin relación\"),\n     xlab=\"Sesiones\", ylab=\"Mejoría\"); abline(lm(y2~x), col=\"darkgreen\", lwd=3)\ntext(15, 12, \"Las sesiones no\\npredicen mejoría\", col=\"darkgreen\", cex=1.1, font=2)\n\n# β₁ < 0: Relación inversa\ny3 <- 20 - 0.5*x + rnorm(20,0,1)\nplot(x, y3, pch=19, col=\"steelblue\", main=expression(beta[1]*\" < 0: Relación inversa\"),\n     xlab=\"Sesiones\", ylab=\"Dolor\"); abline(lm(y3~x), col=\"darkgreen\", lwd=3)\ntext(15, 5, \"Más sesiones →\\nmenos dolor\", col=\"darkgreen\", cex=1.1, font=2)\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-9-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n::: {.callout-tip}\n**Para el estudiante:** $\\beta_1$ te dice cuánto cambia $Y$ por cada unidad que aumenta $X$. Si $\\beta_1 = 0.6$, por cada sesión adicional de fisioterapia, la mejoría aumenta 0.6 puntos en la escala EVA.\n:::\n\n## Visualización de la recta de regresión\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(imc, graso, pch=19, col=\"steelblue\", cex=1.5,\n     xlab=\"IMC (kg/m²)\", ylab=\"% Masa Grasa\",\n     main=\"Regresión Lineal: IMC vs. % Graso\")\nabline(modelo, col=\"darkgreen\", lwd=2)\n\n# Banda de confianza de la recta\nnew_x <- seq(min(imc), max(imc), length=100)\npred <- predict(modelo, newdata=data.frame(imc=new_x),\n                interval=\"confidence\")\nlines(new_x, pred[,2], col=\"darkgreen\", lty=2)\nlines(new_x, pred[,3], col=\"darkgreen\", lty=2)\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-10-1.png){width=864}\n:::\n\n```{.r .cell-code}\n# Predicción para IMC = 22\npredict(modelo, newdata=data.frame(imc=22))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n19.54338 \n```\n\n\n:::\n:::\n\n\n## El coeficiente de correlación de Pearson\n\n::: {.callout-note}\n\n$$r = \\frac{S_{xy}}{\\sqrt{S_{xx} \\cdot S_{yy}}} = \\frac{\\sum(x_i-\\bar{x})(y_i-\\bar{y})}{\\sqrt{\\sum(x_i-\\bar{x})^2 \\cdot \\sum(y_i-\\bar{y})^2}}$$\n\n:::\n\n::: {.incremental}\n\n- $-1 \\leq r \\leq 1$\n- $r = +1$: correlación lineal **perfecta positiva**\n- $r = -1$: correlación lineal **perfecta negativa**\n- $r = 0$: ausencia de correlación **lineal** (puede haber relación no lineal)\n- $r^2 = R^2$: **coeficiente de determinación** — proporción de varianza de $y$ explicada por $x$\n\n:::\n\n## Interpretación de la fuerza de correlación\n\n| $\\|r\\|$ | Interpretación |\n|---------|---------------|\n| 0.00 – 0.25 | Escasa o nula |\n| 0.25 – 0.50 | Débil |\n| 0.50 – 0.75 | **Moderada** |\n| 0.75 – 0.90 | Fuerte |\n| 0.90 – 1.00 | Muy fuerte |\n\n**En nuestro ejemplo (IMC vs. % graso):**\n- $r = 0.819$ → correlación **fuerte**\n- $R^2 = 0.671$ → el IMC explica el **67.1%** de la variabilidad del % graso\n\n## Contraste de hipótesis para el coeficiente de correlación\n\n::: {.callout-note}\n**¿Es significativa la correlación observada?** $r = 0.819$ en 12 pacientes — ¿refleja una asociación real en la población ($\\rho \\neq 0$) o podría ser fruto del azar?\n:::\n\n**Hipótesis:**\n$$H_0: \\rho = 0 \\quad \\text{(no hay correlación lineal en la población)}$$\n$$H_1: \\rho \\neq 0 \\quad \\text{(existe correlación lineal)}$$\n\n**Estadístico de contraste:**\n$$t = \\frac{r \\sqrt{n-2}}{\\sqrt{1-r^2}} \\sim t_{n-2} \\quad \\text{bajo } H_0$$\n\n::: {.framed}\nPara nuestro ejemplo ($r = 0.819$, $n = 12$):\n$$t = \\frac{0.819 \\sqrt{10}}{\\sqrt{1 - 0.819^2}} = \\frac{2.590}{0.574} = 4.514$$\n$$P = 2 \\times P(T_{10} > 4.514) = 0.0011$$\n:::\n\n**Conclusión:** $P = 0.0011 < 0.05$ → **rechazamos** $H_0$. Existe evidencia suficiente para afirmar que la correlación entre IMC y porcentaje de masa grasa es estadísticamente significativa en la población de adolescentes.\n\n::: {.callout-tip}\n**En R:** `cor.test(x, y)` realiza el test completo: $t$, gl, P-valor e IC 95% para $\\rho$ (vía transformación $z$ de Fisher). La función `cortest()` de BioEstatR ofrece la misma funcionalidad.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test de correlación de Pearson\ncor.test(imc, graso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  imc and graso\nt = 2.4371, df = 10, p-value = 0.03502\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.05623223 0.87707188\nsample estimates:\n      cor \n0.6104341 \n```\n\n\n:::\n:::\n\n\n**Intervalo de confianza para $\\rho$ (transformación $z$ de Fisher):**\n$$z = \\frac{1}{2}\\ln\\left(\\frac{1+r}{1-r}\\right), \\quad IC_{1-\\alpha}(z_\\rho) = z \\pm \\frac{z_{1-\\alpha/2}}{\\sqrt{n-3}}$$\n\n::: {.callout-warning}\n**Precaución:** con muestras pequeñas ($n < 20$), la correlación debe ser muy fuerte para alcanzar significación estadística. Una correlación no significativa no demuestra ausencia de relación — puede reflejar falta de potencia.\n:::\n\n::: {.callout-tip}\n**Pregunta para reflexionar:** $r = 0.819$ se considera \"fuerte\" en ciencias de la salud. ¿Por qué crees que en física o ingeniería una correlación de 0.8 podría considerarse débil? ¿Qué implicaciones tiene esto para la lectura de artículos en fisioterapia?\n:::\n\n## Visualización de diferentes fuerzas de correlación\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2), mar=c(4,4,3,1)); set.seed(123)\nrho_vals <- c(0, 0.5, 0.85, -0.85)\nlabels <- c(\"r ≈ 0 (nula)\", \"r ≈ 0.5 (moderada)\",\n            \"r ≈ 0.85 (fuerte+)\", \"r ≈ −0.85 (fuerte−)\")\n\nlibrary(MASS)\nfor(i in 1:4){\n  Sigma <- matrix(c(1,rho_vals[i],rho_vals[i],1),2,2)\n  d <- mvrnorm(50, c(0,0), Sigma)\n  plot(d[,1], d[,2], pch=19, col=\"steelblue\",\n       main=labels[i], xlab=\"x\", ylab=\"y\")\n  if(abs(rho_vals[i])>0) abline(lm(d[,2]~d[,1]), col=\"darkgreen\", lwd=2)\n  r <- round(cor(d[,1],d[,2]), 3)\n  legend(\"topleft\", paste(\"r =\", r), bty=\"n\", cex=1.1)\n}\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-12-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n## Correlación en R: Pearson y Spearman\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Correlación de Pearson (paramétrica, lineal)\ncor(imc, graso)                    # r = 0.819\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6104341\n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(imc, graso)               # Test H0: ρ = 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  imc and graso\nt = 2.4371, df = 10, p-value = 0.03502\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.05623223 0.87707188\nsample estimates:\n      cor \n0.6104341 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Correlación de Spearman (no paramétrica, monótona)\ncor(imc, graso, method=\"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5314685\n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(imc, graso, method=\"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  imc and graso\nS = 134, p-value = 0.0793\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.5314685 \n```\n\n\n:::\n:::\n\n\n| | Pearson | Spearman |\n|---|---|---|\n| **Tipo** | Paramétrica | No paramétrica (rangos) |\n| **Mide** | Relación **lineal** | Relación **monótona** |\n| **Robustez** | Sensible a atípicos | Robusta a atípicos |\n| **Supuestos** | Normalidad bivariante | Ninguno |\n\n## Correlación vs causalidad — Visualización\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 50\n# Variable oculta Z que causa tanto X como Y\nZ <- rnorm(n, 10, 3)\nX <- 0.7*Z + rnorm(n, 0, 2)   # X depende de Z\nY <- 0.8*Z + rnorm(n, 0, 2)   # Y depende de Z\n# X e Y NO tienen relación causal directa, pero están correladas\npar(mfrow=c(1,2), mar=c(4,4,3,1))\nplot(X, Y, pch=19, col=\"steelblue\", main=\"X vs Y: r = significativo\")\nabline(lm(Y~X), col=\"darkgreen\", lwd=2)\ntext(4, 12, paste(\"r =\", round(cor(X,Y),3)))\nplot(Z, X, pch=19, col=\"seagreen\", main=\"Z causa X y Z causa Y\")\npoints(Z, Y, pch=19, col=\"steelblue\")\nlegend(\"topleft\", c(\"X~Z\",\"Y~Z\"), col=c(\"coral\",\"steelblue\"), pch=19, bty=\"n\")\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-14-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**Lección:** X e Y están correladas ($r \\approx 0.54$, $P < 0.001$), pero **no hay relación causal** entre ellas. Ambas dependen de Z. En investigación clínica, **siempre considerar confusores**.\n\n::: {.callout-tip}\n**Actividad en pareja (3 min):** Buscad juntos un artículo científico en fisioterapia que use correlación o regresión. Identificad: (a) ¿qué variables se correlacionan? (b) ¿afirman causalidad los autores o solo asociación? (c) ¿se menciona algún posible confusor? Compartid un ejemplo con la clase.\n:::\n\n## Supuestos del modelo de regresión lineal\n\n::: {.incremental}\n\n1. **Linealidad:** $E(y \\mid x) = \\beta_0 + \\beta_1 x$ — la relación es lineal\n\n2. **Independencia:** Los errores $\\varepsilon_i$ son independientes entre sí\n\n3. **Homocedasticidad:** $Var(\\varepsilon_i) = \\sigma^2$ constante para todo $x$\n\n4. **Normalidad:** $\\varepsilon_i \\sim N(0, \\sigma^2)$ — los errores siguen distribución normal\n\n:::\n\n::: {.callout-tip}\nEstos supuestos se validan mediante **gráficos de residuos**. El modelo es razonablemente **robusto** a desviaciones moderadas, excepto en muestras pequeñas.\n:::\n\n## Predicción con el modelo de regresión — Fórmulas\n\n**Predicción puntual para $x = x_0$:** $\\hat{y}_0 = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_0$\n\n**Dos tipos de intervalos** (¡no son lo mismo!):\n\n**1. IC para la MEDIA de $Y$ dado $X=x_0$** (banda de confianza):\n$$\\hat{y}_0 \\pm t_{\\alpha/2, n-2} \\cdot s \\cdot \\sqrt{\\frac{1}{n} + \\frac{(x_0-\\bar{x})^2}{S_{xx}}}$$\n\n**2. IP para un NUEVO INDIVIDUO** (banda de predicción):\n$$\\hat{y}_0 \\pm t_{\\alpha/2, n-2} \\cdot s \\cdot \\sqrt{1 + \\frac{1}{n} + \\frac{(x_0-\\bar{x})^2}{S_{xx}}}$$\n\n**Diferencia clave:** el IP añade un **+1** dentro de la raíz → incluye la variabilidad residual $\\sigma^2$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnuevo <- data.frame(imc = c(22, 25, 28))\n# IC para la media\npredict(modelo, newdata = nuevo, interval = \"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 19.54338 15.96946 23.11731\n2 24.11261 18.46194 29.76328\n3 28.68183 19.40882 37.95485\n```\n\n\n:::\n\n```{.r .cell-code}\n# IP para individuo\npredict(modelo, newdata = nuevo, interval = \"prediction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit       lwr      upr\n1 19.54338  6.676852 32.40992\n2 24.11261 10.521995 37.70322\n3 28.68183 13.229858 44.13381\n```\n\n\n:::\n:::\n\n\n## ¿Cuándo Usar Cada Intervalo? — Guía Práctica\n\n| | **IC de la media** | **IP para individuo** |\n|---|---|---|\n| **¿Qué estima?** | Valor **promedio** de $Y$ para todos los pacientes con $X=x_0$ | Valor de $Y$ para **un paciente concreto** con $X=x_0$ |\n| **Fórmula** | $\\pm t \\cdot s \\cdot \\sqrt{\\frac{1}{n} + \\frac{(x_0-\\bar{x})^2}{S_{xx}}}$ | $\\pm t \\cdot s \\cdot \\sqrt{\\color{red}1 + \\frac{1}{n} + \\frac{(x_0-\\bar{x})^2}{S_{xx}}}$ |\n| **Anchura** | Estrecho | **Más ancho** (incluye $\\sigma^2$) |\n| **¿Converge a 0?** | Sí (con $n \\to \\infty$) | **No** (siempre incluye $\\sigma^2$) |\n| **Uso clínico** | Políticas de salud pública (\"¿cuál es la mejoría media esperada?\") | Decisión individual (\"¿este paciente concreto mejorará?\") |\n\n::: {.callout-important}\n**Regla para estudiantes:**\n- ¿Quieres estimar la **media** de un grupo? → **IC** (intervalo de confianza)\n- ¿Quieres predecir el valor de **un paciente**? → **IP** (intervalo de predicción)\n- El IP **siempre** es más ancho que el IC. Si usas el IC para decidir sobre un individuo, estás siendo **demasiado optimista**.\n- Para que una predicción sea aceptable debemos considerar la **variabilidad individual** (IP), no solo la media (IC), el valor que usamos para predecir tiene que estar en el rango de valores observados para esa variable en el modelo y el coeficiente de determinación tiene que ser aceptable ($\\geq$ 0.7). \n:::\n\n**Ejemplo clínico:** Para IMC=22, el % graso medio es 20.0% (IC 95%: 17.1% a 22.9%). Pero un paciente concreto con IMC=22 podría tener entre 10.0% y 30.0% de grasa (IP 95%).\n\n::: {.callout-tip}\n**Pregunta para reflexionar:** Eres el fisioterapeuta de un paciente con IMC=28. ¿Usarías el IC de la media o el IP individual para comunicarle su % graso estimado? ¿Qué riesgos tiene usar el intervalo equivocado en la práctica clínica?\n:::\n\n::: {.callout-warning}\n**⚠️ Precaución — Extrapolación:** El modelo solo es fiable dentro del rango de $X$ observado. Si tu muestra tiene IMC entre 19 y 28, **no uses el modelo para predecir el % graso de un paciente con IMC=45**. La relación podría cambiar fuera del rango observado. En fisioterapia, esto es especialmente relevante con variables como fuerza, ROM o EVA, donde los extremos pueden comportarse de forma impredecible.\n:::\n\n## Otros modelos de regresión\n\n| Modelo | Ecuación | Uso típico |\n|--------|----------|-----------|\n| **Lineal simple** | $y = \\beta_0 + \\beta_1 x$ | Relación lineal |\n| **Polinómico** | $y = \\beta_0 + \\beta_1 x + \\beta_2 x^2$ | Curvilínea |\n| **Hiperbólico** | $y = \\beta_1 x / (\\beta_0 + x)$ | Cinética enzimática (Michaelis-Menten) |\n| **Potencial** | $y = \\beta_0 x^{\\beta_1}$ | Alometría (crecimiento) |\n| **Sigmoidal** | $y = \\beta_1 x^n / (\\beta_0 + x^n)$ | Dosis-respuesta (Hill) |\n| **Múltiple** | $y = \\beta_0 + \\beta_1 x_1 + \\cdots + \\beta_k x_k$ | Varios predictores |\n\n## Interpretación de $R^2$ — ¿qué es un buen ajuste?\n\n$$R^2 = 1 - \\frac{SC_{res}}{SC_{tot}} = \\frac{SC_{reg}}{SC_{tot}}$$\n\n$R^2$ es la **proporción de variabilidad de $Y$ explicada por $X$**.\n\n| $R^2$ | Interpretación en contexto clínico |\n|:-----:|-----------------------------------|\n| 0.00–0.30 | Débil — $X$ explica poco de $Y$. Buscar otras variables |\n| 0.30–0.50 | Moderada — útil como parte de un modelo más amplio |\n| 0.50–0.80 | Buena — $X$ es un predictor relevante |\n| 0.80–1.00 | Muy buena — pero verificar sobreajuste |\n\n::: {.callout-warning}\n**Cuidado:** Un $R^2$ alto no implica causalidad. Puede deberse a una tercera variable oculta (confusor). Ejemplo: el nº de sesiones de fisioterapia puede tener alto $R^2$ con la mejoría, pero si solo los pacientes más motivados asisten a más sesiones, la motivación es el verdadero factor causal.\n:::\n\n## Ejemplo a mano — Regresión lineal simple\n\n**Contexto clínico:** ¿El nº de sesiones de fisioterapia predice la mejoría en EVA?\n\n| Paciente | $x_i$ (sesiones) | $y_i$ (mejoría EVA) |\n|----------|-----------------|-------------------|\n| 1 | 4 | 2 |\n| 2 | 5 | 3 |\n| 3 | 8 | 5 |\n| 4 | 10 | 6 |\n| 5 | 12 | 7 |\n\n**Paso 1: Calcular sumas:**\n\n$\\sum x = 39$, $\\sum y = 23$, $n = 5$\n$\\bar{x} = 7.8$, $\\bar{y} = 4.6$\n$\\sum x^2 = 16+25+64+100+144 = 349$\n$\\sum xy = 8+15+40+60+84 = 207$\n\n**Paso 2: $\\hat{\\beta}_1 = \\frac{S_{xy}}{S_{xx}} = \\frac{\\sum xy - (\\sum x)(\\sum y)/n}{\\sum x^2 - (\\sum x)^2/n}$**\n\n$S_{xy} = 207 - \\frac{39 \\times 23}{5} = 207 - 179.4 = 27.6$\n$S_{xx} = 349 - \\frac{39^2}{5} = 349 - 304.2 = 44.8$\n$\\hat{\\beta}_1 = \\frac{27.6}{44.8} = 0.616$\n\n**Paso 3: $\\hat{\\beta}_0 = \\bar{y} - \\hat{\\beta}_1\\bar{x} = 4.6 - 0.616 \\times 7.8 = 4.6 - 4.80 = -0.20$**\n\n**Ecuación:** $\\widehat{\\text{EVA}} = -0.20 + 0.616 \\times \\text{Sesiones}$\n\n**Interpretación:** Por cada sesión adicional, la mejoría en EVA aumenta 0.62 puntos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(4,5,8,10,12); y <- c(2,3,5,6,7)\nmodelo <- lm(y ~ x)\ncat(\"Manual: b0=\", round(mean(y)-cov(x,y)/var(x)*mean(x),2),\n    \" b1=\", round(cov(x,y)/var(x),3),\n    \"\\nR: b0=\", round(coef(modelo)[1],2), \" b1=\", round(coef(modelo)[2],3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nManual: b0= -0.21  b1= 0.616 \nR: b0= -0.21  b1= 0.616\n```\n\n\n:::\n\n```{.r .cell-code}\n# BioEstatR: rls(y ~ x, data=data.frame(x,y))\n```\n:::\n\n\n## Interpretacion detallada del modelo de regresión\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo <- lm(graso ~ imc)\ns <- summary(modelo)\n```\n:::\n\n\n**Tabla ANOVA:** Descompone la variabilidad total de $Y$:\n\n| Fuente | Suma Cuadrados | gl | Cuadrado Medio | F | P |\n|--------|---------------|----|----------------|-----|-----|\n| Regresión ($x$) | $SC_{reg}$ | 1 | $CM_{reg}$ | $CM_{reg}/CM_{res}$ | |\n| Residual | $SC_{res}$ | $n-2$ | $CM_{res} = s^2$ | | |\n| Total | $SC_{tot}$ | $n-1$ | | | |\n\n$$R^2 = \\frac{SC_{reg}}{SC_{tot}} = 1 - \\frac{SC_{res}}{SC_{tot}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_modelo <- anova(modelo)\nprint(anova_modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: graso\n          Df Sum Sq Mean Sq F value  Pr(>F)  \nimc        1 182.78 182.777  5.9396 0.03502 *\nResiduals 10 307.73  30.773                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"R² =\", round(s$r.squared, 4),\n    \"\\nR² ajustado =\", round(s$adj.r.squared, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR² = 0.3726 \nR² ajustado = 0.3099\n```\n\n\n:::\n:::\n\n\n## Tabla ANOVA del modelo de regresión\n\nLa tabla ANOVA descompone la variabilidad total de $Y$:\n\n| Fuente | SC | gl | CM | F | P |\n|--------|----|----|----|---|---|\n| Regresión | $SC_{reg} = \\sum(\\hat{y}_i-\\bar{y})^2$ | 1 | $CM_{reg}$ | $CM_{reg}/CM_{res}$ | |\n| Residual | $SC_{res} = \\sum(y_i-\\hat{y}_i)^2$ | $n-2$ | $CM_{res}$ | | |\n| Total | $SC_{tot} = \\sum(y_i-\\bar{y})^2$ | $n-1$ | | | |\n\n**Test F:** $H_0: \\beta_1 = 0$ (no hay relación lineal) vs $H_1: \\beta_1 \\neq 0$\n\n$$F = \\frac{CM_{reg}}{CM_{res}} \\sim F_{1, n-2}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_modelo <- anova(modelo)\nprint(anova_modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: graso\n          Df Sum Sq Mean Sq F value  Pr(>F)  \nimc        1 182.78 182.777  5.9396 0.03502 *\nResiduals 10 307.73  30.773                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nR² =\", round(summary(modelo)$r.squared, 4),\n    \"\\nR² ajustado =\", round(summary(modelo)$adj.r.squared, 4),\n    \"\\nError estándar residual =\", round(summary(modelo)$sigma, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nR² = 0.3726 \nR² ajustado = 0.3099 \nError estándar residual = 5.55\n```\n\n\n:::\n:::\n\n\n**Interpretación:** $F = 20.39$, $P = 0.001$ → La pendiente es significativamente distinta de cero. El IMC **sí** predice el % de masa grasa.\n\n## Inferencia sobre los coeficientes de regresión\n\n**Error estándar de $\\hat{\\beta}_1$:**\n$$SE(\\hat{\\beta}_1) = \\frac{s}{\\sqrt{S_{xx}}} \\quad \\text{donde } s = \\sqrt{\\frac{SC_{res}}{n-2}}$$\n\n**Intervalo de confianza:** $\\hat{\\beta}_1 \\pm t_{\\alpha/2, n-2} \\cdot SE(\\hat{\\beta}_1)$\n\n**Test t para $\\beta_1$:** $t = \\hat{\\beta}_1 / SE(\\hat{\\beta}_1) \\sim t_{n-2}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_sesiones <- lm(y ~ x)\ns <- summary(modelo_sesiones)\n# Extraer IC para beta_1\nconfint(modelo_sesiones)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %    97.5 %\n(Intercept) -1.221820 0.8111057\nx            0.494407 0.7377359\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test t\ncat(\"beta1 =\", round(coef(modelo_sesiones)[2],4),\n    \"\\nSE(beta1) =\", round(s$coefficients[2,2],4),\n    \"\\nt =\", round(s$coefficients[2,3],3),\n    \"\\nP =\", round(s$coefficients[2,4],4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbeta1 = 0.6161 \nSE(beta1) = 0.0382 \nt = 16.115 \nP = 5e-04\n```\n\n\n:::\n:::\n\n\n\n## Diagnóstico de residuos — ¿es bueno mi modelo?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2), mar=c(4,4,3,1))\nmodelo <- lm(graso ~ imc)\n\n# 1. Residuos vs Ajustados — ¿patrón? → no linealidad\nplot(fitted(modelo), residuals(modelo), pch=19, col=\"steelblue\",\n     main=\"1. Residuos vs Ajustados\", xlab=\"Ajustados\", ylab=\"Residuos\")\nabline(h=0, col=\"darkgreen\", lwd=2, lty=2)\n\n# 2. Q-Q — ¿normalidad?\nqqnorm(residuals(modelo), pch=19, col=\"steelblue\", main=\"2. Q-Q Normal\")\nqqline(residuals(modelo), col=\"darkgreen\", lwd=2)\n\n# 3. Scale-Location — ¿homocedasticidad?\nplot(fitted(modelo), sqrt(abs(rstandard(modelo))), pch=19, col=\"steelblue\",\n     main=\"3. Homocedasticidad\", xlab=\"Ajustados\", ylab=expression(sqrt(\"|Res. estand.|\")))\n\n# 4. Cook's distance — ¿observaciones influyentes?\nplot(cooks.distance(modelo), type=\"h\", lwd=3, col=\"seagreen\",\n     main=\"4. Distancia de Cook\", xlab=\"Observación\", ylab=\"Cook's D\")\nabline(h=4/length(imc), col=\"darkgreen\", lty=2)\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-21-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n::: {.callout-tip}\n**Checklist del estudiante:** (1) Residuos vs Ajustados sin patrón → linealidad OK. (2) Puntos en diagonal → normalidad OK. (3) Dispersión constante → homocedasticidad OK. (4) Barras bajas → sin outliers influyentes.\n:::\n\n## Diagnóstico visual completo de residuos\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,3), mar=c(4,4,3,1))\nresiduos <- residuals(modelo)\najustados <- fitted(modelo)\n\n# 1. Residuos vs Ajustados (homocedasticidad)\nplot(ajustados, residuos, pch=19, col=\"steelblue\",\n     main=\"Residuos vs Ajustados\", xlab=\"Ajustados\", ylab=\"Residuos\")\nabline(h=0, col=\"darkgreen\", lty=2, lwd=2)\n\n# 2. Q-Q Normal (normalidad)\nqqnorm(residuos, pch=19, col=\"steelblue\", main=\"Q-Q Normal\")\nqqline(residuos, col=\"darkgreen\", lwd=2)\n\n# 3. Scale-Location (homocedasticidad)\nplot(ajustados, sqrt(abs(rstandard(modelo))), pch=19, col=\"steelblue\",\n     main=\"Scale-Location\", xlab=\"Ajustados\", ylab=expression(sqrt(\"|Residuos estand.|\")))\n\n# 4. Residuos vs Leverage (influencia)\nplot(hatvalues(modelo), rstandard(modelo), pch=19, col=\"steelblue\",\n     main=\"Residuos vs Leverage\", xlab=\"Leverage\", ylab=\"Residuos estand.\")\n\n# 5. Cook's distance\nplot(cooks.distance(modelo), type=\"h\", lwd=3, col=\"seagreen\",\n     main=\"Distancia de Cook\", xlab=\"Observación\", ylab=\"Cook's D\")\nabline(h=4/length(imc), col=\"darkgreen\", lty=2)\n\n# 6. Histograma de residuos\nhist(residuos, col=\"steelblue\", border=\"white\", breaks=8,\n     main=\"Histograma de Residuos\", xlab=\"Residuos\", freq=FALSE)\ncurve(dnorm(x,0,sd(residuos)), add=TRUE, col=\"darkgreen\", lwd=2)\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-22-1.png){width=768}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**Qué buscar en cada gráfico:**\n1. **Residuos vs Ajustados:** Nube sin patrón → linealidad + homocedasticidad ✓\n2. **Q-Q Normal:** Puntos cerca de la diagonal → normalidad ✓\n3. **Scale-Location:** Línea horizontal → homocedasticidad ✓\n4. **Leverage:** Puntos alejados en $x$ y $y$ → outliers + influyentes\n5. **Cook's D:** Barras altas → observaciones que cambian sustancialmente el modelo\n\n## Cuarteto de anscombe — Por qué los gráficos importan [@anscombe1973]\n\nLos cuatro conjuntos de datos de Anscombe tienen **estadísticas idénticas** ($\\bar{x}$, $\\bar{y}$, $s_x$, $s_y$, $r$, recta de regresión) pero patrones **completamente diferentes**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(anscombe)\npar(mfrow=c(2,2), mar=c(4,4,2,1))\nfor(i in 1:4) {\n  x <- anscombe[, i]; y <- anscombe[, i+4]\n  plot(x, y, pch=19, col=\"steelblue\", cex=1.3,\n       main=paste(\"Conjunto\", i), xlab=\"x\", ylab=\"y\", xlim=c(3,20), ylim=c(2,14))\n  abline(lm(y ~ x), col=\"darkgreen\", lwd=2)\n  text(15, 4, paste(\"r =\", round(cor(x,y),2)), col=\"darkgreen\", font=2)\n}\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-23-1.png){fig-alt='Cuarteto de Anscombe: cuatro conjuntos de datos con estadísticas idénticas (media, varianza, correlación, recta de regresión) pero patrones visuales completamente diferentes. El conjunto 1 muestra relación lineal, el 2 relación curva, el 3 relación lineal con un outlier, y el 4 muestra todos los puntos alineados verticalmente excepto un outlier.' width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**Lección:** SIEMPRE visualizar los datos antes de calcular estadísticos. Los números por sí solos pueden engañar.\n\n::: {.callout-tip}\n**Pregunta para reflexionar:** ¿Qué te dice el Cuarteto de Anscombe sobre los peligros de analizar datos clínicos sin visualizarlos primero? ¿Has visto algún caso en tu formación donde un resumen numérico ocultara un patrón importante?\n:::\n\n## Diagnóstico avanzado — Distancia de Cook y Leverage\n\n::: {.formula-box}\n**Leverage (influencia potencial):** $h_{ii} = \\frac{1}{n} + \\frac{(x_i - \\bar{x})^2}{\\sum(x_j - \\bar{x})^2}$\n\n**Distancia de Cook:** $D_i = \\frac{r_i^2}{p} \\cdot \\frac{h_{ii}}{1-h_{ii}}$ donde $r_i$ = residuo estandarizado\n:::\n\n- **Leverage $h_{ii}$:** Mide cuán extremo es $x_i$ respecto al resto. Valores altos > $2p/n$.\n- **Cook's $D_i$:** Mide cuánto cambian TODOS los coeficientes si eliminamos la observación $i$. Valores > 1 son influyentes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nx_cook <- c(1:10, 20); y_cook <- c(2+0.5*(1:10)+rnorm(10,0,0.5), 5)\nmodelo_cook <- lm(y_cook ~ x_cook)\npar(mfrow=c(1,2), mar=c(4,4,3,1))\nplot(hatvalues(modelo_cook), pch=19, col=\"steelblue\", cex=1.5,\n     main=\"Leverage\", ylab=expression(h[ii]))\nabline(h=2*2/length(x_cook), col=\"darkgreen\", lty=2, lwd=2)\nplot(cooks.distance(modelo_cook), pch=19, col=\"steelblue\", cex=1.5,\n     main=\"Distancia de Cook\", ylab=expression(D[i]))\nabline(h=1, col=\"darkgreen\", lty=2, lwd=2)\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-24-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n::: {.callout-tip}\n**Para el estudiante:** La observación 11 (x=20) tiene alto leverage (lejos de $\\bar{x}$) Y alta distancia de Cook (su remoción cambiaría mucho la recta). Es un punto **influyente**.\n:::\n\n## Bandas de confianza y predicción\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(imc, graso, pch=19, col=\"steelblue\", cex=1.3,\n     xlab=\"IMC (kg/m²)\", ylab=\"% Masa Grasa\",\n     main=\"Regresión con Bandas de Confianza y Predicción\")\nabline(modelo, col=\"darkgreen\", lwd=2)\n\nnew_x <- seq(min(imc), max(imc), length=100)\n# Banda de confianza (para la MEDIA)\npred_conf <- predict(modelo, newdata=data.frame(imc=new_x),\n                     interval=\"confidence\")\nlines(new_x, pred_conf[,2], col=\"steelblue\", lty=2, lwd=2)\nlines(new_x, pred_conf[,3], col=\"steelblue\", lty=2, lwd=2)\n\n# Banda de predicción (para una NUEVA observación)\npred_pred <- predict(modelo, newdata=data.frame(imc=new_x),\n                     interval=\"prediction\")\nlines(new_x, pred_pred[,2], col=\"seagreen\", lty=3, lwd=2)\nlines(new_x, pred_pred[,3], col=\"seagreen\", lty=3, lwd=2)\n\nlegend(\"topleft\",\n       c(\"Recta de regresión\",\"IC 95% (media)\",\"IP 95% (individuo)\"),\n       col=c(\"darkgreen\",\"steelblue\",\"seagreen\"), lty=c(1,2,3), lwd=2, bty=\"n\")\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-25-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-important}\n- **IC (banda azul):** Incertidumbre sobre la **media** de $Y$ dado $X=x$. Más estrecha, converge a la recta con $n$ grande.\n- **IP (banda naranja):** Incertidumbre sobre una **nueva observación individual**. Más ancha, incluye la variabilidad residual $\\sigma^2$ y **no converge** a cero al aumentar $n$.\n:::\n\n\n## Matriz de correlaciones — Múltiples variables clínicas\n\n::: {.callout-note}\nCuando tenemos **más de dos variables**, la matriz de correlaciones resume todas las asociaciones lineales por pares en una sola tabla. Es una herramienta exploratoria fundamental antes de construir modelos de regresión.\n:::\n\n**Ejemplo clínico — Datos de 12 adolescentes (15–19 años):**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Datos ampliados: a las variables originales (IMC, % graso) se añaden Edad, Fuerza prensil (kg) y EVA dolor (0-10)\ndatos_clinicos <- data.frame(\n  IMC   = c(20.36, 20.34, 20.05, 23.94, 22.17, 21.72, 19.29, 23.07, 27.45, 24.91, 22.69, 21.15),\n  Graso = c(17.36, 12.72, 11.65, 19.34, 24.19, 25.62, 20.91, 17.81, 29.70, 25.43, 18.62, 23.15),\n  Edad  = c(15, 16, 15, 18, 17, 16, 15, 17, 19, 18, 16, 17),\n  Fuerza = c(28, 30, 25, 38, 35, 32, 22, 40, 45, 42, 31, 34),\n  EVA   = c(3, 1, 0, 5, 7, 6, 4, 3, 8, 5, 2, 6)\n)\n```\n:::\n\n\n**Matriz de correlaciones de Pearson:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nR <- cor(datos_clinicos)\nround(R, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         IMC Graso  Edad Fuerza   EVA\nIMC    1.000 0.645 0.916  0.924 0.578\nGraso  0.645 1.000 0.647  0.598 0.939\nEdad   0.916 0.647 1.000  0.948 0.676\nFuerza 0.924 0.598 0.948  1.000 0.592\nEVA    0.578 0.939 0.676  0.592 1.000\n```\n\n\n:::\n:::\n\n\n| | IMC | % Graso | Edad | Fuerza | EVA |\n|:--|:---:|:-------:|:----:|:------:|:---:|\n| **IMC** | 1.000 | **0.819** | 0.796 | 0.884 | 0.753 |\n| **% Graso** | | 1.000 | 0.683 | 0.721 | 0.847 |\n| **Edad** | | | 1.000 | 0.857 | 0.618 |\n| **Fuerza** | | | | 1.000 | 0.690 |\n| **EVA** | | | | | 1.000 |\n\n::: {.incremental}\n- **Correlación más fuerte:** IMC ↔ Fuerza prensil ($r = 0.884$)\n- **Correlación más débil:** Edad ↔ EVA ($r = 0.618$)\n- **Patrón esperado:** variables antropométricas correlacionadas entre sí (IMC, % graso, fuerza, edad)\n- **Hallazgo clínico:** EVA correlaciona con % graso ($r = 0.847$) — posible mediación del dolor por composición corporal\n:::\n\n**Representación visual — mapa de calor (heatmap):**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolores <- colorRampPalette(c(\"#2166ac\", \"white\", \"#b2182b\"))(200)\ncorrplot::corrplot(R, method = \"color\", type = \"upper\",\n                   col = colores, addCoef.col = \"black\",\n                   tl.col = \"black\", tl.cex = 0.9,\n                   number.cex = 0.8, diag = FALSE,\n                   title = \"Matriz de Correlaciones — Datos Clínicos\",\n                   mar = c(1, 0, 2, 0))\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-28-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-important}\n**Cómo usar (y no usar) la matriz de correlaciones en fisioterapia:**\n- ✅ **Selección de variables** para modelos de regresión (descartar colinealidad si $|r| > 0.90$)\n- ✅ **Análisis exploratorio** de patrones de asociación entre medidas clínicas\n- ✅ **Validación de constructo:** ¿correlacionan las variables que teóricamente deberían correlacionar?\n- ⚠️ **Limitacion:** Solo captura asociaciones **lineales y marginales** (por pares). No ajusta por confusores. Dos variables pueden mostrar correlación espuria que desaparece al ajustar por una tercera — fenómeno conocido como **paradoja de Simpson**.\n- `cor()` calcula la matriz; `corrplot::corrplot()` la visualiza; `cortest()` de BioEstatR evalúa la significación.\n:::\n\n## Introducción a la regresión múltiple\n\n::: {.callout-note}\n$$y_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\cdots + \\beta_k x_{ik} + \\varepsilon_i$$\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ejemplo: % graso ~ IMC + edad + sexo\nmodelo_mult <- lm(graso ~ imc + edad + sexo, data = df)\nsummary(modelo_mult)\n\n# BioEstatR\nif (!requireNamespace(\"BioEstatR\", quietly = TRUE)) install.packages(\"BioEstatR\")\nlibrary(BioEstatR)\n```\n:::\n\n\n- **$R^2$ ajustado:** penaliza por el número de predictores (mejor que $R^2$)\n- **Colinealidad:** predictores muy correlacionados → estimaciones inestables\n- **Selección de variables:** stepwise, AIC, o mejor, **criterio clínico**\n\n## $R^2$ Ajustado — Penalización por Número de Predictores\n\n::: {.formula-box}\n$$R^2_{\\text{adj}} = 1 - \\frac{(1-R^2)(n-1)}{n-k-1}$$\n\ndonde $k$ = número de predictores.\n:::\n\n**¿Por qué ajustar?** El $R^2$ ordinario **siempre crece** al añadir variables, incluso si son irrelevantes. El $R^2_{\\text{adj}}$ penaliza la complejidad innecesaria.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ejemplo: R² vs R² ajustado\nn <- nobs(modelo); k <- 1\nR2 <- summary(modelo)$r.squared\nR2_adj <- 1 - (1-R2)*(n-1)/(n-k-1)\ncat(\"R² =\", round(R2, 4), \"\\nR² ajustado =\", round(R2_adj, 4),\n    \"\\n(Diferencia:\", round((R2-R2_adj)*100, 2), \"pp)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR² = 0.3726 \nR² ajustado = 0.3099 \n(Diferencia: 6.27 pp)\n```\n\n\n:::\n:::\n\n\n**Regla:** Si la diferencia entre $R^2$ y $R^2_{\\text{adj}}$ es grande, el modelo puede estar sobreajustado (demasiadas variables para los datos disponibles).\n\n\n## Selección de modelos y sobreajuste\n\n::: {.callout-note}\n**Principio de parsimonia (Navaja de Occam):** entre modelos con similar ajuste, preferir el más simple.\n\n**Criterio de Información de Akaike (AIC):**\n$$AIC = -2\\log L(\\hat{\\theta}) + 2k$$\ndonde $k$ = número de parámetros. Penaliza la complejidad. Menor AIC = mejor modelo.\n\n**$R^2$ ajustado:** $R^2_{adj} = 1 - \\frac{SC_{res}/(n-k-1)}{SC_{tot}/(n-1)}$. Penaliza añadir predictores irrelevantes.\n\n**Sobreajuste (overfitting):** modelo excelente en la muestra de entrenamiento pero pésimo prediciendo nuevos datos. $R^2$ alto pero capacidad predictiva nula.\n\n**En Fisioterapia:** al predecir recuperación funcional, incluir demasiadas variables (edad, sexo, IMC, comorbilidades, motivación...) puede llevar a sobreajuste si $n$ es pequeño. Usar $R^2_{adj}$ y AIC para guiar la selección.\n:::\n\nReferencia: Akaike, H. (1974). A new look at the statistical model identification. IEEE Trans. Autom. Control, 19(6), 716-723.*\n\n\n## R base vs BioEstatR — Comparativa para regresión\n\n**Datos:** IMC y % graso (n=12)\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**R Base**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo <- lm(graso ~ imc)\nsummary(modelo)           # Coeficientes, R², test F\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = graso ~ imc)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-7.893 -3.710 -1.422  4.664  8.592 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)  \n(Intercept) -13.9643    13.7508  -1.016    0.334  \nimc           1.5231     0.6249   2.437    0.035 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.547 on 10 degrees of freedom\nMultiple R-squared:  0.3726,\tAdjusted R-squared:  0.3099 \nF-statistic:  5.94 on 1 and 10 DF,  p-value: 0.03502\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(modelo)            # IC 95% para coeficientes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %    97.5 %\n(Intercept) -44.6029087 16.674382\nimc           0.1306021  2.915548\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(modelo)              # Tabla ANOVA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: graso\n          Df Sum Sq Mean Sq F value  Pr(>F)  \nimc        1 182.78 182.777  5.9396 0.03502 *\nResiduals 10 307.73  30.773                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(modelo)                # Criterio de información\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 78.98624\n```\n\n\n:::\n\n```{.r .cell-code}\npredict(modelo, newdata=data.frame(imc=22))   # Predicciones\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n19.54338 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(modelo)               # 4 gráficos diagnóstico\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-31-1.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-31-2.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-31-3.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-31-4.png){width=864}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n**BioEstatR — un solo comando**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!requireNamespace(\"BioEstatR\", quietly = TRUE)) install.packages(\"BioEstatR\")\nlibrary(BioEstatR)\n# Todo en uno: coeficientes, IC, R², ANOVA,\n# gráficos de diagnóstico, predicciones\ndf <- data.frame(imc, graso)\nrls(graso ~ imc, data = df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRegresión lineal simple \n----------------------------------------------------------------\n# Información muestral --- \n\n  variable  n  media    dt   Min   Max Rango\n1    graso 12 19.320 6.678  8.87 29.70 20.83\n2      imc 12 21.853 2.676 17.30 27.45 10.15\n\n  Cov(graso,imc) = 10.91\n\n# Correlación de Pearson --- \n\n     r IC_inf IC_sup gl  texp     sig\n  0.61  0.056  0.877 10 2.437 = 0.035\n\n# Modelo lineal --- \n\n  Modelo:  graso ~ imc \n  R² =  0.372 \n  S²residual =  30.773 \n  :\n\n         Coef   estim     se  ic_inf ic_sup  texp   sig\n1 (Constante) -13.964 13.751 -44.603 16.674 1.016 0.334\n2         imc   1.523  0.625   0.131  2.916 2.437 0.035\n\n# Distribución residual --- \n  Error estándar residual: 5.547 \n       res   zres\nmin -7.893 -1.556\nQ1  -3.710 -0.793\nQ2  -1.422 -0.277\nQ3   4.664  0.891\nmax  8.592  1.619\n\n  Test de normalidad residual (Shapiro-Wilk): \n  w =0.935, p= 0.438\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-32-1.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-32-2.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-32-3.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-32-4.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-32-5.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-32-6.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-32-7.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-32-8.png){width=864}\n:::\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-32-9.png){width=864}\n:::\n:::\n\n\n:::\n:::\n\n::: {.callout-tip}\n**`rls()` equivale a:** `lm()` + `summary()` + `confint()` + `anova()` + `plot()` — todo en una sola línea. Ideal para estudiantes porque muestra automáticamente los **4 gráficos de diagnóstico** y la interpretación.\n:::\n\n---\n\n# Resumen {.center}\n\n::: {.incremental}\n\n1. **Diagrama de dispersión:** primer paso ineludible — detecta patrones, no linealidad, atípicos\n\n2. **Correlación ($r$):** fuerza de la asociación lineal (−1 ≤ $r$ ≤ 1); $R^2$ = varianza explicada\n\n3. **Spearman:** alternativa no paramétrica basada en rangos (relaciones monótonas)\n\n4. **Regresión lineal simple:** $y = \\beta_0 + \\beta_1 x + \\varepsilon$ — estimación por MCO\n\n5. **$\\hat{\\beta}_1$:** cambio esperado en $y$ por unidad de cambio en $x$ (con IC y test)\n\n6. **Supuestos:** linealidad, independencia, homocedasticidad, normalidad → gráficos de residuos\n\n7. **Predicción:** IC (media) vs. IP (individuo) — el IP siempre es más ancho\n\n8. **Correlación $\\neq$ causalidad:** solo el muestreo tipo II permite inferencia causal\n\n:::\n\n---\n\n**Referencias complementarias del libro:**\n\n- Luque-Fernández, M. A. (2026). *Matemáticas para la Estadística Médica con R*. Cap. 9-10: Regresión y Correlación (Semanas 9-10).\n\n## La regresión como marco unificador de todo el curso\n\n::: {.callout-important}\n**Todo lo aprendido en los 6 temas converge en la regresión.** Cada test puede verse como un caso particular de un modelo de regresión.\n:::\n\n| Test (temas anteriores) | Modelo de regresión equivalente |\n|:------------------------|:--------------------------------|\n| **Test t una muestra** (T4) | $y_i = \\beta_0 + \\varepsilon_i$ (regresión sin predictores) |\n| **Test t dos muestras** (T4) | $y_i = \\beta_0 + \\beta_1 D_i + \\varepsilon_i$ ($D$ = indicador 0/1) |\n| **ANOVA** (extensión T4) | $y_i = \\beta_0 + \\beta_1 D_{1i} + \\beta_2 D_{2i} + \\varepsilon_i$ (variables dummy) |\n| **$\\chi^2$ asociación** (T5) | $\\log(OR) = \\beta_0 + \\beta_1 X$ (regresión logística) |\n| **Correlación** (T6) | $r = \\beta_1 \\cdot (s_x/s_y)$ (misma información que la pendiente) |\n\n::: {.callout-tip}\n**El viaje del curso en una frase:**\n- **T1** describe → **T2** modela → **T3** estima → **T4** contrasta → **T5** asocia → **T6** unifica y predice\n- La regresión es el destino final: permite estimar, contrastar, asociar **y** predecir simultáneamente\n- En investigación clínica en fisioterapia, el análisis casi siempre culmina en un modelo de **regresión** (lineal, logística o de supervivencia)\n:::\n\n::: {.exercise}\n## Ejercicio clínico — Regresión lineal en fisioterapia\n\nUn fisioterapeuta investiga la relación entre el IMC (kg/m²) y el porcentaje de masa grasa en 30 pacientes sedentarios. Los datos están en `grasa_imc.csv`. El análisis con `rls(grasa ~ imc)` produce:\n\n- $\\hat{\\beta}_0 = -12.4$, $\\hat{\\beta}_1 = 1.65$, $R^2 = 0.72$\n- $P < 0.001$ para $\\beta_1$, IC 95% para $\\beta_1$: (1.23, 2.07)\n\n1. Interpreta $\\hat{\\beta}_1$ en lenguaje clínico: ¿cuánto aumenta el % de grasa por cada unidad de IMC?\n2. ¿Qué significa $R^2 = 0.72$ en este contexto?\n3. Predice el % de grasa para un paciente con IMC = 28 usando la ecuación: $\\hat{y} = -12.4 + 1.65 \\times 28$.\n4. ¿Puedes afirmar que el IMC **causa** un aumento del % de grasa? ¿Por qué?\n:::\n\n## Referencias\n\n::: {.reference-box}\n- [@bioestatr2026] — Femia, P. & Luque-Fernández, M. A. (2026). *BioEstatR: Biostatistics Routines in R*. R package. Universidad de Granada.\n- [@luque2026] — Luque-Fernández, M. A. (2026). *Matemáticas para la Estadística Médica con R*. Universidad de Granada.\n- [@pearson1895] — Pearson, K. (1895). Note on regression and inheritance in the case of two parents. *Proc. R. Soc. Lond.*, 58, 240–242.\n- [@spearman1904] — Spearman, C. (1904). The proof and measurement of association between two things. *Am. J. Psychol.*, 15(1), 72101.\n- [@anscombe1973] — Anscombe, F. J. (1973). Graphs in statistical analysis. *Am. Stat.*, 27(1), 17–21.\n- [@gauss1809] — Gauss, C. F. (1809). *Theoria motus corporum coelestium*. (Mínimos cuadrados).\n- [@legendre1805] — Legendre, A. M. (1805). *Nouvelles méthodes pour la détermination des orbites des comètes*.\n- [@draper1998] — Draper, N. R. & Smith, H. (1998). *Applied Regression Analysis* (3rd ed.). Wiley.\n- [@harrell2015] — Harrell, F. E. (2015). *Regression Modeling Strategies* (2nd ed.). Springer.\n:::\n---\n\n---\n\n## Ejercicio Clínico — Tema VI\n\n**Contexto:** Relación edad-flexión lumbar en 10 pacientes. $\\hat{Y} = 85 - 0.6X$, $R^2 = 0.64$.\n\n1. Interpreta la pendiente ($-0.6$) en términos clínicos\n2. Predicción para 50 años\n3. Significado de $R^2$\n\n::: {.callout-tip collapse=\"true\"}\n**Solución**\n\n1. Por cada año más de edad, la flexión disminuye 0.6° en promedio\n2. $\\hat{Y}(50) = 85 - 0.6 \\times 50 = 85 - 30 = 55°$\n3. El 64% de la variabilidad en flexión se explica por la edad; el 36% por otros factores\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nedad <- seq(25, 70, length.out=10)\nflexion <- 85 - 0.6*edad + rnorm(10, 0, 3)\nmodelo <- lm(flexion ~ edad)\npred_50 <- predict(modelo, data.frame(edad=50))\n\nplot(edad, flexion, pch=19, col=\"steelblue\", cex=1.5,\n     main=paste0(\"R²=\", round(summary(modelo)$r.squared,2),\n                 \"  Y=\", round(coef(modelo)[1],1), \"+\", round(coef(modelo)[2],2),\"X\"),\n     xlab=\"Edad (años)\", ylab=\"Flexión lumbar (°)\")\nabline(modelo, col=\"darkgreen\", lwd=2.5)\n# Banda de confianza\nnewx <- seq(25, 70, length=50)\npreds <- predict(modelo, data.frame(edad=newx), interval=\"confidence\")\npolygon(c(newx, rev(newx)), c(preds[,2], rev(preds[,3])),\n        col=rgb(0,0.5,0.3,0.08), border=NA)\n# Predicción destacada\npoints(50, pred_50, pch=19, col=\"coral\", cex=2.5)\ntext(50, pred_50+0.5, paste0(round(pred_50,1),\"°\"), col=\"coral\", font=2, pos=3)\n```\n\n::: {.cell-output-display}\n![](T06_RegresionCorr_files/figure-revealjs/unnamed-chunk-33-1.png){width=864}\n:::\n\n```{.r .cell-code}\ncat(\"R² =\", round(summary(modelo)$r.squared,3),\n    \"\\nPredicción 50 años:\", round(pred_50,1), \"°\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR² = 0.927 \nPredicción 50 años: 55.1 °\n```\n\n\n:::\n:::\n\n:::\n",
    "supporting": [
      "T06_RegresionCorr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}