{
  "hash": "e111691c2459600ec807ff1924f35405",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Contraste de Hipótesis\"\nsubtitle: \"Tema IV (Parte I) — Fundamentos, Tests para Una Muestra y Normalidad\"\nauthor:\n  - name: \"Miguel Angel Luque-Fernández\"\n    affiliation: \"Dpto. Estadística e Investigación Operativa, Universidad de Granada\"\n    email: \"mluquefe@ugr.es\"\n    url: \"https://migariane.github.io\"\ndate: \"2026\"\nlicense: \"CC BY 4.0\"\nformat:\n  revealjs:\n    slide-number: c/t\n    code-fold: true\n    code-summary: \"Mostrar código R\"\n    code-copy: true\n    code-overflow: wrap\n    fig-align: center\n    fig-width: 9\n    fig-height: 5.2\n    lang: es\nexecute:\n  warning: false\n  message: false\n  echo: true\n  eval: true\n---\n\n# Contraste de Hipótesis {.center}\n\n![](logo.png){width=\"90px\"}\n\n**Grado en Fisioterapia**\n\n**CC BY 4.0** · Miguel Angel Luque-Fernández\n\n[Miguel Angel Luque-Fernández](https://migariane.github.io) · [maluque.netlify.app](https://maluque.netlify.app)\n\nDpto. Estadística e Investigación Operativa · Universidad de Granada\n\n## Objetivos de aprendizaje — Tema 4\n\n::: {.callout-tip}\n**Al finalizar este tema sabrás:**\n:::\n\n::: {.incremental}\n1. Formular $H_0$ y $H_1$ para cualquier problema clínico\n2. Distinguir Error Tipo I ($\\alpha$) de Error Tipo II ($\\beta$) y entender la potencia\n3. Interpretar correctamente un P-valor (¡no es la probabilidad de $H_0$!)\n4. Aplicar el test t para una muestra, dos muestras independientes y pareadas\n5. Decidir entre test paramétrico y no paramétrico según los datos\n6. Usar `testt()`, `testp()`, `testmcnemar()` y `testwx()` de BioEstatR\n:::\n\n## ¿Por Qué Necesito los Tests de Hipótesis como Fisioterapeuta?\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**En tu práctica clínica diaria:**\n\n- ¿Es mejor la terapia manual que el ejercicio para la cervicalgia?\n- ¿Reduce significativamente el dolor mi protocolo de tratamiento?\n- ¿Hay diferencias reales entre dos grupos de pacientes?\n\n**El P-valor responde:** ¿son estos resultados probablemente debidos al azar?\n\n:::\n\n::: {.column width=\"50%\"}\n\n**En tu lectura crítica de artículos:**\n\n- \"El tratamiento mostró eficacia (P = 0.03)\" → ¿es fiable?\n- \"No hubo diferencias significativas (P = 0.12)\" → ¿seguro que no hay efecto, o la muestra era pequeña?\n- \"El IC 95% fue (−0.5, 8.2)\" → ¿es clínicamente relevante?\n\n:::\n:::\n\n**\"Lo que la estadística nos dice no es si un efecto existe, sino cuán sorprendentes son los datos si asumimos que no existe.\"** — Ronald Fisher [@fisher1925]\n\n\n\n\n# Marco Conceptual {.center}\n\n![](logo.png){width=\"90px\"}\n\n**Grado en Fisioterapia**\n\nCC BY 4.0 — Miguel Angel Luque-Fernández\n\n## Mapa conceptual — El universo de los tests de hipótesis\n\nAntes de sumergirnos en fórmulas, visualicemos el **esquema completo** que guía la elección del test adecuado:\n\n### ¿Qué queremos comparar?\n\n| Situación | Diseño | Test paramétrico | No paramétrico |\n|:----------|:-------|:-----------------|:--------------------|\n| **Una muestra** vs referencia | $\\bar{x}$ vs $\\mu_0$ | **t-Student** (1 m) | Wilcoxon signed-rank |\n| **Dos muestras independientes** | Grupo A vs B | **t-Student / Welch** | Mann-Whitney $U$ |\n| **Dos muestras pareadas** | Antes vs después | **t pareado** | Wilcoxon paired |\n| **Más de 2 muestras** | 3+ grupos | ANOVA | Kruskal-Wallis |\n\n### Homogeneidad de varianzas — ¿Student o Welch?\n\n::: {.columns}\n::: {.column width=\"50%\"}\n$$H_0: \\sigma_1^2 = \\sigma_2^2 \\quad H_1: \\sigma_1^2 \\neq \\sigma_2^2$$\n\n- $P > 0.05$ → varianzas iguales → **t-Student**\n- $P \\leq 0.05$ → varianzas distintas → **t-Welch**\n:::\n::: {.column width=\"50%\"}\n::: {.callout-tip}\n**Regla práctica:** ante la duda, **usa siempre Welch**. Tiene potencia casi idéntica a Student cuando las varianzas son iguales, y es válido cuando no lo son.\n:::\n:::\n:::\n\n### ¿Bilateral o unilateral?\n\n| | Bilateral | Unilateral |\n|:--|:----------|:-----------|\n| $H_1$ | $\\mu_1 \\neq \\mu_2$ | $\\mu_1 > \\mu_2$ |\n| $\\alpha$ | Repartido en 2 colas | Concentrado en 1 cola |\n| **Regla** | Usar por defecto | Solo con justificación previa |\n\n### Métodos computacionales — Bootstrap\n\nCuando los supuestos no se cumplen y $n$ es pequeño, el **bootstrap** (Efron, 1979) remuestrea los datos con reemplazo $B$ veces para construir la distribución empírica del estadístico sin asumir Normalidad.\n\n## Árbol de decisión clínico — ¿qué test uso?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar=c(0,0,0,0), bg=NA)\nplot(NA, xlim=c(0,10), ylim=c(0,10), axes=F, xlab=\"\", ylab=\"\")\n\n# ── Nodo raíz ──\nrect(4.2, 9.4, 5.8, 10.1, col=\"#2c3e50\", border=NA, lwd=0)\ntext(5, 9.75, \"¿Variable Normal?\", cex=0.78, font=2, col=\"white\")\n\n# Ramas principales con gradiente\nsegments(5, 9.4, 3, 8.6, lwd=3, col=\"#27ae60\")\nsegments(5, 9.4, 7, 8.6, lwd=3, col=\"coral\")\ntext(3.9, 9.0, \"SÍ\", cex=0.75, font=2, col=\"#27ae60\")\ntext(6.1, 9.0, \"NO\", cex=0.75, font=2, col=\"coral\")\n\n# ── Rama SÍ ──\nrect(2.2, 7.9, 3.8, 8.6, col=\"#d5f5e3\", border=\"#27ae60\", lwd=2.5)\ntext(3, 8.25, \"¿n ≥ 60? (TCL)\", cex=0.68, font=2, col=\"#1e6e3e\")\nsegments(3, 7.9, 1.8, 6.9, lwd=2.5, col=\"#27ae60\")\nsegments(3, 7.9, 4.2, 6.9, lwd=2.5, col=\"#e67e22\")\ntext(2.3, 7.4, \"SÍ\", cex=0.65, font=2, col=\"#27ae60\")\ntext(3.7, 7.4, \"NO\", cex=0.65, font=2, col=\"#e67e22\")\n\n# Hoja: t-Student (válido TCL)\nrect(1.0, 6.2, 2.6, 6.8, col=\"#27ae60\", border=NA)\ntext(1.8, 6.5, \"t-Student\\n(válido TCL)\", cex=0.6, font=2, col=\"white\")\n\n# Nodo intermedio: Shapiro\nrect(3.5, 6.2, 4.9, 6.8, col=\"#fef9e7\", border=\"#e67e22\", lwd=2.5)\ntext(4.2, 6.5, \"Shapiro-Wilk\\n¿P > 0.05?\", cex=0.62, font=2, col=\"#e67e22\")\nsegments(4.2, 6.2, 3.5, 5.2, lwd=2, col=\"#27ae60\")\nsegments(4.2, 6.2, 4.9, 5.2, lwd=2, col=\"coral\")\ntext(3.8, 5.7, \"SÍ\", cex=0.6, font=2, col=\"#27ae60\")\ntext(4.5, 5.7, \"NO\", cex=0.6, font=2, col=\"coral\")\n\n# Hojas Shapiro\nrect(2.8, 4.5, 4.0, 5.1, col=\"#27ae60\", border=NA)\ntext(3.4, 4.8, \"t-Student\", cex=0.6, font=2, col=\"white\")\nrect(4.3, 4.5, 5.7, 5.1, col=\"coral\", border=NA)\ntext(5.0, 4.8, \"Wilcoxon /\\nMann-Whitney\", cex=0.55, font=2, col=\"white\")\n\n# ── Rama NO ──\nrect(6.2, 7.9, 7.8, 8.6, col=\"#fadbd8\", border=\"coral\", lwd=2.5)\ntext(7, 8.25, \"¿n ≥ 60? (TCL)\", cex=0.68, font=2, col=\"coral\")\nsegments(7, 7.9, 5.8, 6.9, lwd=2.5, col=\"#27ae60\")\nsegments(7, 7.9, 8.2, 6.9, lwd=2.5, col=\"coral\")\ntext(6.3, 7.4, \"SÍ\", cex=0.65, font=2, col=\"#27ae60\")\ntext(7.7, 7.4, \"NO\", cex=0.65, font=2, col=\"coral\")\n\n# Hojas rama NO\nrect(5.0, 6.2, 6.6, 6.8, col=\"#27ae60\", border=NA)\ntext(5.8, 6.5, \"t-Student\\n(válido TCL)\", cex=0.6, font=2, col=\"white\")\nrect(7.4, 6.2, 9.0, 6.8, col=\"coral\", border=NA)\ntext(8.2, 6.5, \"Wilcoxon /\\nMann-Whitney\", cex=0.55, font=2, col=\"white\")\n\n# ── Leyenda ──\nrect(0.3, 1.4, 1.5, 2.2, col=\"#27ae60\", border=NA)\ntext(1.7, 1.8, \"Test paramétrico\", cex=0.55, pos=4, font=2)\nrect(3.3, 1.4, 4.5, 2.2, col=\"coral\", border=NA)\ntext(4.7, 1.8, \"Test no paramétrico\", cex=0.55, pos=4, font=2)\nrect(6.5, 1.4, 7.7, 2.2, col=\"#fef9e7\", border=\"#e67e22\", lwd=2)\ntext(7.9, 1.8, \"Verificar supuestos\", cex=0.55, pos=4, font=2)\n```\n\n::: {.cell-output-display}\n![](T04_I_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-1-1.png){fig-alt='Árbol de decisión clínico para elegir el test estadístico adecuado. Empieza preguntando si la variable es Normal. Si es Normal, pregunta si n≥60. Si no es Normal, también pregunta si n≥60. Las ramas llevan a t-Student, Shapiro-Wilk o tests no paramétricos.' width=864}\n:::\n:::\n\n\n::: {.callout-tip}\n**Regla nemotécnica:** Normal + n ≥ 60 → t-Student directo. Normal + n < 60 → verificar Shapiro. No Normal + n ≥ 60 → t-Student (TCL). No Normal + n < 60 → no paramétrico.\n:::\n\n## ¿Por Qué $n \\geq 60$? — Justificación del Teorema Central del Límite\n\n::: {.callout-important}\nEl **Teorema Central del Límite** (Tema 3) establece que para cualquier variable con media $\\mu$ y varianza $\\sigma^2$ finitas:\n\n$$\\frac{\\bar{X} - \\mu}{\\sigma / \\sqrt{n}} \\xrightarrow{\\mathcal{D}} N(0,1) \\quad \\text{cuando} \\quad n \\to \\infty$$\n:::\n\n**¿Qué significa esto en la práctica?** La distribución de $\\bar{X}$ se aproxima a una Normal **sin importar la forma de los datos originales**. La velocidad de convergencia depende de la asimetría de la distribución subyacente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,3), mar=c(3,3,3,1))\nset.seed(123)\nns <- c(5, 15, 30, 60, 100, 200)\nfor(i in 1:length(ns)){\n  n <- ns[i]\n  medias <- replicate(5000, mean(rexp(n, rate=1)))  # exponencial (muy asimétrica)\n  hist(medias, col=\"#d4e6f1\", border=\"white\", freq=FALSE, breaks=30,\n       main=paste0(\"n = \", n), xlab=expression(bar(x)), cex.main=1.1)\n  curve(dnorm(x, mean=1, sd=1/sqrt(n)), add=T, col=\"coral\", lwd=2)\n  if(i==1) legend(\"topright\", c(\"Dist. muestral\", \"Normal teórica\"),\n                  col=c(\"#d4e6f1\",\"coral\"), lwd=c(NA,2), pch=c(15,NA), bty=\"n\", cex=0.7)\n}\n```\n\n::: {.cell-output-display}\n![](T04_I_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-2-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**¿Por qué exactamente 60?** No es un número mágico, sino un **punto de convergencia empírico**:\n\n| $n$ | Calidad de la aproximación Normal | ¿Test t válido? |\n|:---:|:----------------------------------|:----------------|\n| $n < 15$ | Mala (sesgo visible) | Solo si datos ≈ Normales |\n| $15 \\leq n < 30$ | Aceptable para datos simétricos | Verificar Shapiro-Wilk |\n| $30 \\leq n < 60$ | Buena para la mayoría de casos | t-Student razonable |\n| **$n \\geq 60$** | **Excelente (independiente de la distribución)** | **t-Student válido sin verificar Normalidad** |\n\n::: {.callout-tip}\n**En fisioterapia:** si tienes 60 o más pacientes, el TCL te protege. No necesitas preocuparte por si los datos de ROM, fuerza o dolor son Normales — la media muestral ya lo es. Con menos de 60, verifica siempre la normalidad con Shapiro-Wilk y Q-Q plot.\n:::\n\n## ¿Qué es un Contraste de Hipótesis? — Analogía Judicial\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**El contraste de hipótesis es como un juicio:**\n\n- **$H_0$:** \"El acusado es **inocente**\" (presunción de inocencia)\n- **$H_1$:** \"El acusado es **culpable**\"\n\nLa carga de la prueba recae sobre quien acusa. Se necesita **evidencia suficiente** para rechazar $H_0$. \"No culpable\" no es \"inocente\".\n\n:::\n\n::: {.column width=\"50%\"}\n\n**En estadística aplicada a Fisioterapia:**\n\n- **$H_0$:** \"La terapia no tiene efecto\" (lo asumido)\n- **$H_1$:** \"La terapia sí tiene efecto\" (lo que se investiga)\n\n**No rechazar $H_0 \\neq$ probar $H_0$.** Solo significa que los datos no aportan evidencia suficiente para declarar un efecto.\n\n:::\n:::\n\n## La lógica del contraste — Visualización intuitiva\n\n**Pregunta clave:** ¿Es la diferencia observada lo suficientemente grande como para no deberse al azar?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\npar(mfrow=c(1,2), mar=c(4,4,3,1))\n# Escenario A: Diferencia pequeña (ruido)\ncurve(dnorm(x, 0, 1), -4, 6, lwd=3, col=\"steelblue\", ylab=\"Densidad\",\n      main=\"Caso A: Diferencia NO significativa\", xlab=\"Efecto observado\")\nabline(v=0, lwd=2, col=\"grey40\"); abline(v=0.5, lwd=3, col=\"darkgreen\")\ntext(0.5, 0.35, \"Diferencia\", col=\"darkgreen\", pos=4, font=2)\ntext(2, 0.28, \"Pequeña → probablemente azar\\n→ NO rechazar H0\", col=\"darkgreen\", cex=0.9)\n# Escenario B: Diferencia grande (señal)\ncurve(dnorm(x, 0, 1), -4, 6, lwd=3, col=\"steelblue\", ylab=\"\",\n      main=\"Caso B: Diferencia SIGNIFICATIVA\", xlab=\"Efecto observado\")\nabline(v=0, lwd=2, col=\"grey40\"); abline(v=3, lwd=3, col=\"darkgreen\")\ntext(3, 0.35, \"Diferencia\", col=\"darkgreen\", pos=4, font=2)\ntext(2, 0.28, \"Grande → improbable por azar\\n→ RECHAZAR H0\", col=\"darkgreen\", cex=0.9)\n```\n\n::: {.cell-output-display}\n![](T04_I_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-3-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**Regla intuitiva:** Si la diferencia observada es tan grande que sería muy raro verla solo por azar ($P < 0.05$), concluimos que hay un efecto real.\n\n## Hipótesis nula y alternativa — Definiciones formales\n\n::: {.callout-note}\nProcedimiento de **Inferencia Estadistica** para tomar una **decisión** sobre un parámetro poblacional usando información **muestral**.\n:::\n\n- **$H_0$ (Nula):** lo asumido cierto. Igualdad, homogeneidad. Especifica distribución conocida.\n- **$H_1$ (Alternativa):** negación de $H_0$. Diferencia, asociación. No especifica distribución.\n\n**Ejemplos:** $H_0: \\mu = \\mu_0$, $H_0: p = p_0$, $H_0: \\mu_1 = \\mu_2$, $H_0: p_1 = p_2$\n\n## Del estadístico muestral al estadístico de contraste — Conexión t3→t4\n\n::: {.callout-note}\n**En Tema 3 aprendiste** que los estadísticos muestrales tienen su propia distribución:\n\n$$\\bar{X} \\sim N\\left(\\mu, \\frac{\\sigma}{\\sqrt{n}}\\right) \\qquad \\text{(distribución de la media muestral)}$$\n\n**En Tema 4 añadimos $H_0$:** si suponemos $H_0: \\mu = \\mu_0$ cierta, entonces:\n\n$$\\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} \\quad \\xrightarrow{H_0} \\quad T = \\frac{\\bar{X} - \\mu_0}{s/\\sqrt{n}} \\sim t_{n-1}$$\n\n**El estadístico de contraste $T$ es simplemente el estadístico muestral $\\bar{X}$ estandarizado bajo $H_0$.**\n:::\n\n**¿Por qué funciona?** Bajo $H_0$, $T$ tiene una distribución **conocida** ($t_{n-1}$). Si el $T$ observado es un valor muy extremo de esa distribución conocida → los datos contradicen $H_0$ → rechazamos $H_0$.\n\n## Desarrollo teórico — Test para $\\mu$\n\n::: {.incremental}\n- $X \\sim N(\\mu, \\sigma)$ → distribución de la variable original\n- $\\bar{x} \\sim N(\\mu, \\sigma/\\sqrt{n})$ → distribución de la media muestral\n- $t_{\\text{exp}} = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}} \\sim t_{n-1}$ → estadístico de contraste bajo $H_0$\n:::\n\n**Ejemplo — METs/semana (n=12):** $\\bar{x}=189.76$, $s=62.02$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn<-12; xbar<-189.76; s<-62.02\ncat(\"Caso a (mu0=200): t =\", round((xbar-200)/(s/sqrt(n)),3),\n    \"P =\", round(2*pt(-abs((xbar-200)/(s/sqrt(n))),11),4),\n    \"\\nCaso b (mu0=230): t =\", round((xbar-230)/(s/sqrt(n)),3),\n    \"P =\", round(2*pt(-abs((xbar-230)/(s/sqrt(n))),11),4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCaso a (mu0=200): t = -0.572 P = 0.5789 \nCaso b (mu0=230): t = -2.248 P = 0.0461\n```\n\n\n:::\n:::\n\n\n## El estadístico de contraste — Visualización del concepto\n\n**Misma idea que en T3, pero ahora bajo $H_0$:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,3), mar=c(4,4,3,1))\n\n# Panel 1: Distribución de X (datos originales)\ncurve(dnorm(x, 130, 5), 115, 145, lwd=3, col=\"steelblue\",\n      main=\"1. Distribución de X\", xlab=\"Flexión (°)\", ylab=\"f(x)\")\nabline(v=130, col=\"darkgreen\", lwd=2); text(135, 0.07, \"μ₀=130\", col=\"darkgreen\", font=2)\n\n# Panel 2: Distribución de la media muestral (T3)\ncurve(dnorm(x, 130, 5/sqrt(6)), 124, 136, lwd=3, col=\"darkgreen\",\n      main=\"2. Dist. de X̄ (Tema 3)\", xlab=\"Media muestral\", ylab=\"f(x̄)\")\nabline(v=130, col=\"darkgreen\", lwd=2); text(131, 0.9, \"μ=130\", col=\"darkgreen\", font=2)\n\n# Panel 3: Estadístico de contraste T (T4 — estandarizado bajo H₀)\ncurve(dt(x, 5), -4, 4, lwd=3, col=\"seagreen\",\n      main=\"3. Estadístico T (Tema 4)\", xlab=\"t = (x̄-μ₀)/(s/√n)\", ylab=\"f(t)\")\nabline(v=0, col=\"darkgreen\", lwd=2); text(1, 0.3, \"0 (H₀ cierta)\", col=\"darkgreen\", font=2)\n# Marcar región de rechazo\nt_crit <- qt(0.975, 5)\nabline(v=c(-t_crit, t_crit), col=\"grey40\", lty=2, lwd=2)\ntext(3, 0.05, \"Rechazo\", col=\"darkgreen\", cex=0.8)\ntext(-3, 0.05, \"Rechazo\", col=\"darkgreen\", cex=0.8)\n```\n\n::: {.cell-output-display}\n![](T04_I_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-5-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**Paso 1 (T3):** $\\bar{X}$ es una VA con distribución conocida.\n**Paso 2 (T4):** Estandarizamos bajo $H_0$ → $T \\sim t_{n-1}$. Si $|T|$ es grande → rechazamos $H_0$.\n\n## Errores tipo i ($\\alpha$) y tipo ii ($\\beta$) — Visualización\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualización de errores con dos distribuciones\npar(mar=c(4,4,3,1))\nx <- seq(-4, 8, 0.01)\ny_H0 <- dnorm(x, 0, 1)     # Distribución bajo H0\ny_H1 <- dnorm(x, 3, 1)     # Distribución bajo H1 (efecto real)\nplot(x, y_H0, type=\"l\", lwd=3, col=\"steelblue\", ylab=\"Densidad\",\n     main=expression(paste(\"Errores Tipo I (\", alpha, \") y Tipo II (\", beta, \")\")),\n     ylim=c(0,0.45), xlab=\"Estadístico de contraste\")\nlines(x, y_H1, lwd=3, col=\"seagreen\")\nt_crit <- qnorm(0.975)  # 1.96\nabline(v=t_crit, col=\"grey40\", lty=2, lwd=2)\n# α — cola derecha bajo H0\nxf <- seq(t_crit, 8, 0.01); yf <- dnorm(xf, 0, 1)\npolygon(c(xf, rev(xf)), c(yf, rep(0,length(yf))), col=rgb(0,0,1,0.25), border=NA)\ntext(3.2, 0.04, expression(alpha/2), col=\"steelblue\", cex=1.3, font=2)\n# β — bajo H1 a la izquierda de t_crit\nxf <- seq(-4, t_crit, 0.01); yf <- dnorm(xf, 3, 1)\npolygon(c(xf, rev(xf)), c(yf, rep(0,length(yf))), col=rgb(0,0.5,0.3,0.2), border=NA)\ntext(0.8, 0.08, expression(beta), col=\"darkgreen\", cex=1.3, font=2)\n# Potencia (1-β)\nxf <- seq(t_crit, 8, 0.01); yf <- dnorm(xf, 3, 1)\npolygon(c(xf, rev(xf)), c(yf, rep(0,length(yf))), col=rgb(0,0.8,0,0.2), border=NA)\ntext(4.8, 0.04, \"1-β\", col=\"darkgreen\", cex=1.2, font=2)\nlegend(\"topleft\", c(expression(H[0]), expression(H[1])), col=c(\"steelblue\",\"seagreen\"), lwd=3, bty=\"n\")\n```\n\n::: {.cell-output-display}\n![](T04_I_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-6-1.png){fig-alt='Visualización de los errores Tipo I (alfa) y Tipo II (beta) con dos distribuciones normales solapadas. La distribución bajo H0 en azul (centrada en 0) y bajo H1 en verde (centrada en 3). El área azul a la derecha de la línea crítica vertical es alfa (error Tipo I), el área verde a la izquierda es beta (error Tipo II), y el área verde a la derecha es la potencia (1-beta).' width=864}\n:::\n:::\n\n\n| | $H_0$ cierta | $H_0$ falsa |\n|---|---|---|\n| **Aceptar $H_0$** | ✓ $(1-\\alpha)$ | Error II ($\\beta$) |\n| **Rechazar $H_0$** | Error I ($\\alpha$) | ✓ Potencia ($1-\\beta$) |\n\n- $\\alpha$ fijado por el investigador (típicamente 0.05). No depende de $n$.\n- $\\beta$ desconocido. Depende de $n$, $\\alpha$, y magnitud del efecto real.\n- **Para reducir ambos errores:** aumentar $n$.\n\n::: {.callout-note}\n**Definiciones formales (Neyman-Pearson, 1933)**\n\nSea $T$ el estadístico de contraste y $\\mathcal{R}$ la región de rechazo:\n\n$$\\alpha = P(\\text{Rechazar } H_0 \\mid H_0 \\text{ cierta}) = P(T \\in \\mathcal{R} \\mid H_0)$$\n\n$$\\beta = P(\\text{No rechazar } H_0 \\mid H_0 \\text{ falsa}) = P(T \\notin \\mathcal{R} \\mid H_1)$$\n\n$$\\text{Potencia} = 1 - \\beta = P(\\text{Rechazar } H_0 \\mid H_1 \\text{ cierta}) = P(T \\in \\mathcal{R} \\mid H_1)$$\n\n**Relación fundamental:** $\\alpha$ y $\\beta$ están inversamente relacionados. Para un $n$ fijo, reducir $\\alpha$ aumenta $\\beta$. La única forma de reducir ambos simultáneamente es aumentar $n$.\n:::\n\n*Si un estudio con n=10 no rechaza $H_0$, ¿podemos concluir que el tratamiento no funciona? ¿Por qué?*\n\n## Ejemplo de cálculo del p-valor desde la tabla t de Student\n\n**Caso:** $t_{\\text{exp}} = 2.40$ con gl = 10. Obtener P sin ordenador.\n\nEn la fila gl=10 de la tabla t-Student:\n$t_{0.05;10} = 2.228 < 2.40 < t_{0.02;10} = 2.764$\n\nPor tanto: **$0.02 < P < 0.05$** → Significativo (P < 0.05)\n\n**Más ejemplos con gl=10:**\n\n| $t_{\\text{exp}}$ | Acotación | Valor P | Decision ($\\alpha=0.05$) |\n|:---:|:---|:---|:---|\n| 2.40 | $t_{0.05}=2.228 < 2.40 < t_{0.02}=2.764$ | $0.02 < P < 0.05$ | Rechazar $H_0$ |\n| 1.21 | $t_{0.30}=1.093 < 1.21 < t_{0.20}=1.372$ | $0.20 < P < 0.30$ | Aceptar $H_0$ (NS) |\n| 2.11 | $t_{0.10}=1.812 < 2.11 < t_{0.05}=2.228$ | $0.05 < P < 0.10$ | Aceptar $H_0$ (Indicios) |\n| 6.33 | $t_{0.001}=4.587 < 6.33$ | $P < 0.001$ | Rechazar $H_0$ |\n| 0.55 | $0.55 < t_{0.50}=0.700$ | $P > 0.50$ | Aceptar $H_0$ (NS) |\n\n**Con ordenador:** siempre se obtiene P exacta con 3 decimales (o $P < 0.001$).\n\n## Valor p — ¿cómo de sorpresivos son los datos?\n\n**P = probabilidad de observar unos datos tan o más extremos que los nuestros, si $H_0$ fuera cierta.**\n\n::: {.columns}\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualización del P-valor\ncurve(dt(x, 11), -4, 4, lwd=3, col=\"steelblue\", ylab=\"Densidad\",\n      main=\"P-valor visualizado — t(11), texp = 2.25\")\nabline(v=c(-2.25, 2.25), col=\"darkgreen\", lwd=2, lty=2)\n# Área del P-valor (dos colas)\nxr <- seq(2.25, 4, 0.01); yr <- dt(xr, 11)\npolygon(c(xr, rev(xr)), c(yr, rep(0,length(yr))), col=rgb(0,0.5,0.3,0.3), border=NA)\nxl <- seq(-4, -2.25, 0.01); yl <- dt(xl, 11)\npolygon(c(xl, rev(xl)), c(yl, rep(0,length(yl))), col=rgb(0,0.5,0.3,0.3), border=NA)\ntext(0, 0.2, \"P = área verde\", font=2, cex=1.2)\ntext(2.8, 0.03, paste0(\"P = \", round(2*pt(-2.25,11),4)), col=\"darkgreen\", font=2)\n```\n\n::: {.cell-output-display}\n![](T04_I_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-7-1.png){width=864}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"45%\"}\n\n**Interpretación intuitiva:**\n\n| P | ¿Qué significa? |\n|---|-----------------|\n| **P = 0.58** | Muy probable bajo $H_0$ → **NO** rechazar |\n| **P = 0.03** | Poco probable bajo $H_0$ → **Rechazar** |\n| **P = 0.001** | Muy improbable → **Fuerte evidencia** |\n\n**P NO es** la probabilidad de que $H_0$ sea cierta. **P ES** la probabilidad de los datos si $H_0$ fuera cierta.\n\n:::\n:::\n\n*Un P=0.051 y un P=0.049, ¿son realmente diferentes en su interpretación clínica?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-c(125,132,128,135,130,126); t<-(mean(x)-130)/(sd(x)/sqrt(6))\ncat(\"t =\", round(t,3), \"→ P(t) =\", round(2*pt(-abs(t),5),4),\n    \"\\nP(z aprox) =\", round(2*pnorm(-abs(t)),4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt = -0.432 → P(t) = 0.6835 \nP(z aprox) = 0.6655\n```\n\n\n:::\n:::\n\n\n## Bilateral vs unilateral\n\n| | Bilateral | Unilateral |\n|---|---|---|\n| $H_1$ | $\\mu \\neq \\mu_0$ | $\\mu > \\mu_0$ (o $<$) |\n| $\\alpha$ | 2 colas | 1 cola |\n| Potencia | Menor | Mayor |\n\n::: {.callout-note}\nElegir unilateral **antes** de ver los datos. Elegirlo después = p-hacking.\n:::\n\n## Normalidad — ¿cómo verificarla antes del test?\n\n**Antes de aplicar un test t, debemos verificar la normalidad de la variable (o usar el TCL con $n \\geq 60$).**\n\n**Métodos gráficos:** histograma con curva Normal, diagrama de cajas, Q-Q plot.\n\n**Tests formales:**\n- **Shapiro-Wilk:** la mejor opción para muestras pequeñas y moderadas\n- **Kolmogorov-Smirnov:** solo para muestras grandes (aproximado)\n- **D\\'Agostino:** se puede calcular a mano\n\n**H0 en tests de normalidad:** \"La variable tiene distribución Normal\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos <- c(125,132,128,135,130,126,156, 140, 138, 142, 130, 128)\n# Shapiro-Wilk (R base)\nshapiro.test(datos)  # P > 0.05 → normalidad asumible\n# BioEstatR: test + Q-Q plot en un solo paso\nlibrary(BioEstatR); testnormal(datos)\n```\n:::\n\n\n::: {.callout-warning}\n**Cuidado con muestras pequeñas:** con $n$ pequeño, los tests de normalidad tienen poca potencia. Tienden a NO rechazar $H_{0}$ aunque los datos no sean normales. Complementar SIEMPRE con gráficos.\n:::\n\n## Test para una media (t-Student)\n\n$$t = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}} \\sim t_{n-1}$$\n\n**Ejemplo:** Flexión rodilla en 6 pacientes: 125°,132°,128°,135°,130°,126°. ¿$\\mu = 130°$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(125,132,128,135,130,126)\nt.test(x, mu = 130)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  x\nt = -0.43234, df = 5, p-value = 0.6835\nalternative hypothesis: true mean is not equal to 130\n95 percent confidence interval:\n 125.3695 133.2972\nsample estimates:\nmean of x \n 129.3333 \n```\n\n\n:::\n\n```{.r .cell-code}\n# BioEstatR: testt(m = mean(x), s = sd(x), n = length(x), m0 = 130)\n```\n:::\n\n\n**Salida:** $t=-0.43$, gl=5, $P=0.683$ → No significativo. IC 95%: (126.4°, 132.9°).\n\n## Test para una proporción — Ejemplo detallado\n\n**Contexto:** Prevalencia de tabaquismo en estudiantes. En 2012 era del 22%. En 2013: n=287, x=48 fumadores. ¿Ha cambiado?\n\n**Paso 1 — Hipótesis:** $H_0: p = 0.22$ vs $H_1: p \\neq 0.22$\n\n**Paso 2 — Condiciones:** $np_0 = 287 \\times 0.22 = 63.14 > 5$ ✓; $nq_0 = 287 \\times 0.78 = 223.86 > 5$ ✓\n\n**Paso 3 — Estadístico:** $z = \\frac{x - np_0 - 0.5}{\\sqrt{np_0q_0}} = \\frac{48 - 63.14 - 0.5}{\\sqrt{287 \\times 0.22 \\times 0.78}} = -2.09$\n\n**Paso 4 — P-valor:** $0.03 < P < 0.04$ → **Rechazamos H0** ($P < 0.05$)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-48; n<-287; p0<-0.22\nz<-(x - n*p0 - 0.5)/sqrt(n*p0*(1-p0))\nP<-2*pnorm(-abs(z))\ncat(\"z =\", round(z,3), \"P =\", round(P,4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz = -2.229 P = 0.0258\n```\n\n\n:::\n:::\n\n\n**Conclusión:** La prevalencia ha cambiado significativamente. IC 95% Wilson: (12.7%, 21.7%). El 22% de 2012 no esta en el IC → confirmación visual.\n\n**Si los datos hubieran sido x=33, n=200:** $z=-1.79$, $0.07 < P < 0.08$ → NO significativo (indicios).\n\n## Test para una proporción\n\n$$Z = \\frac{\\hat{p} - p_0}{\\sqrt{p_0(1-p_0)/n}} \\sim N(0,1)$$\n\n::: {.callout-note}\n**Corrección de continuidad:** Para muestras pequeñas, se aplica la corrección de Yates: $Z = \\frac{|x - np_0| - 0.5}{\\sqrt{np_0(1-p_0)}}$. La decisión de usarla depende del contexto clínico y del tamaño muestral.\n:::\n\n**Ejemplo:** 47 de 50 muestras COVID positivas ($\\hat{p}=0.94$). $H_0: p = 0.95$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-47; n<-50; p0<-0.95\nz<-(x/n-p0)/sqrt(p0*(1-p0)/n)\ncat(\"z =\", round(z,3), \"P =\", round(2*pnorm(-abs(z)),4),\n    \"\\nNo significativo: 94% no difiere de 95% (P = 0.745)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz = -0.324 P = 0.7456 \nNo significativo: 94% no difiere de 95% (P = 0.745)\n```\n\n\n:::\n:::\n\n\n## Interpretación de la salida de `testt()` en BioEstatR\n\n**Ejemplo: `testt(m = 129.33, s = 3.78, n = 6, m0 = 130)`**\n\n```\nTest t para una muestra\nH0: mu = 130\nt = -0.432, gl = 5, P = 0.683\nIC 95% para mu: [126.4, 132.9]\nEstimación del efecto bruto: mu - 130 = -0.67\nIC 95% para el efecto: [-4.64, 3.31]\nTest de Shapiro-Wilk: W = 0.956, P = 0.789\n```\n\n**Cómo leer la salida:**\n- **t y P:** estadístico y P-valor → P = 0.683 > 0.05 → NO rechazar H0\n- **IC 95%:** [126.4, 132.9] contiene 130 → compatible con H0\n- **Efecto bruto:** diferencia estimada = -0.67° (clínicamente irrelevante)\n- **Shapiro-Wilk:** P = 0.789 → normalidad OK\n\n::: {.callout-tip}\n**Para el estudiante:** `testt()` integra test + IC + normalidad en una salida. Si P > 0.05 y el IC contiene a μ₀ → no hay evidencia para rechazar H0.\n:::\n\n## BioEstatR — `testt` para una muestra\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(BioEstatR)\n# Media (con estadísticos resumidos)\ntestt(m = 129.33, s = 3.78, n = 6, m0 = 130)\n\n# Proporción (con x y n)\ntestt(x = 47, n = 50, p0 = 0.95)\n```\n:::\n\n\n**Salida de `testt`:** Muestra automáticamente: estadístico, gl, P-valor, IC 95%, estimación del efecto bruto, y test de normalidad (Shapiro-Wilk) para medias.\n---\n\n---\n\n## Ejercicio Clínico — Tema IV (Parte I)\n\n**Contexto:** Flexión rodilla en 6 pacientes: 125°, 132°, 128°, 135°, 130°, 126°. Referencia: 130°.\n\n1. Formula $H_0$ y $H_1$\n2. Interpreta: $t=-0.43$, $gl=5$, $P=0.683$, IC 95% [126.4°, 132.9°]\n3. ¿Conclusión clínica?\n\n::: {.callout-tip collapse=\"true\"}\n**Solución**\n\n1. $H_0: \\mu = 130°$ vs $H_1: \\mu \\neq 130°$ (bilateral)\n2. $P = 0.683 > 0.05$ → NO rechazar $H_0$. El IC contiene 130°\n3. Sin evidencia suficiente de cambio en la flexión media\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(125,132,128,135,130,126)\ntt <- t.test(x, mu=130)\n\npar(mfrow=c(1,2), mar=c(4,4,3,1))\n# Panel 1: Datos vs referencia\nstripchart(x, method=\"jitter\", pch=19, col=\"steelblue\", cex=1.5,\n           xlim=c(122,138), main=\"Flexión vs H0: μ=130°\", xlab=\"Grados (°)\")\nabline(v=130, col=\"darkgreen\", lwd=2, lty=2)\npoints(mean(x), 1.2, pch=19, col=\"darkgreen\", cex=2)\ntext(mean(x), 1.35, paste0(\"x̄=\", round(mean(x),1)), col=\"darkgreen\", font=2, pos=3)\n# Panel 2: Distribución t\ncurve(dt(x, 5), -4, 4, lwd=3, col=\"steelblue\",\n      main=paste0(\"t(5): P=\", round(tt$p.value,3)), xlab=\"t\", ylab=\"Densidad\")\nabline(v=c(-qt(0.975,5), qt(0.975,5)), col=\"grey\", lty=3)\nabline(v=tt$statistic, col=\"darkgreen\", lwd=2)\ntext(tt$statistic, 0.35, paste0(\"t=\", round(tt$statistic,2)), col=\"darkgreen\", font=2, pos=4)\n```\n\n::: {.cell-output-display}\n![](T04_I_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-14-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n\ncat(\"t =\", round(tt$statistic,2), \"gl =\", tt$parameter, \"P =\", round(tt$p.value,4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt = -0.43 gl = 5 P = 0.6835\n```\n\n\n:::\n:::\n\n:::\n",
    "supporting": [
      "T04_I_Test_Hipotesis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}