{
  "hash": "b614a87258f2c2d2b6f05c849cd4c263",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Contraste de Hipótesis\"\nsubtitle: \"Tema IV — Tests Paramétricos y No Paramétricos\"\nauthor:\n  - name: \"Miguel Angel Luque-Fernández\"\n    affiliation: \"Dpto. Estadística e Investigación Operativa, Universidad de Granada\"\n    email: \"mluquefe@ugr.es\"\n    url: \"https://migariane.github.io\"\ndate: \"2026\"\nlicense: \"CC BY 4.0\"\nformat:\n  revealjs:\n    slide-number: c/t\n    code-fold: true\n    code-summary: \"Mostrar código R\"\n    code-copy: true\n    code-overflow: wrap\n    fig-align: center\n    fig-width: 9\n    fig-height: 5.2\n    lang: es\nexecute:\n  warning: false\n  message: false\n  echo: true\n  eval: true\n---\n\n# Contraste de Hipótesis {.center}\n\n![](logo.png){width=\"90px\"}\n\n**Grado en Fisioterapia**\n\n**CC BY 4.0** · Miguel Angel Luque-Fernández\n\n[Miguel Angel Luque-Fernández](https://migariane.github.io) · [maluque.netlify.app](https://maluque.netlify.app)\n\nDpto. Estadística e Investigación Operativa · Universidad de Granada\n\n## Objetivos de aprendizaje — Tema 4\n\n::: {.callout-tip}\n**Al finalizar este tema sabrás:**\n:::\n\n::: {.incremental}\n1. Formular $H_0$ y $H_1$ para cualquier problema clínico\n2. Distinguir Error Tipo I ($\\alpha$) de Error Tipo II ($\\beta$) y entender la potencia\n3. Interpretar correctamente un P-valor (¡no es la probabilidad de $H_0$!)\n4. Aplicar el test t para una muestra, dos muestras independientes y pareadas\n5. Decidir entre test paramétrico y no paramétrico según los datos\n6. Usar `testt()`, `testp()`, `testmcnemar()` y `testwx()` de BioEstatR\n:::\n\n## ¿Por Qué Necesito los Tests de Hipótesis como Fisioterapeuta?\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**En tu práctica clínica diaria:**\n\n- ¿Es mejor la terapia manual que el ejercicio para la cervicalgia?\n- ¿Reduce significativamente el dolor mi protocolo de tratamiento?\n- ¿Hay diferencias reales entre dos grupos de pacientes?\n\n**El P-valor responde:** ¿son estos resultados probablemente debidos al azar?\n\n:::\n\n::: {.column width=\"50%\"}\n\n**En tu lectura crítica de artículos:**\n\n- \"El tratamiento mostró eficacia (P = 0.03)\" → ¿es fiable?\n- \"No hubo diferencias significativas (P = 0.12)\" → ¿seguro que no hay efecto, o la muestra era pequeña?\n- \"El IC 95% fue (−0.5, 8.2)\" → ¿es clínicamente relevante?\n\n:::\n:::\n\n**\"Lo que la estadística nos dice no es si un efecto existe, sino cuán sorprendentes son los datos si asumimos que no existe.\"** — Ronald Fisher [@fisher1925]\n\n\n\n\n# Marco Conceptual {.center}\n\n![](logo.png){width=\"90px\"}\n\n**Grado en Fisioterapia**\n\nCC BY 4.0 — Miguel Angel Luque-Fernández\n\n## Mapa conceptual — El universo de los tests de hipótesis\n\nAntes de sumergirnos en fórmulas, visualicemos el **esquema completo** que guía la elección del test adecuado:\n\n### ¿Qué queremos comparar?\n\n| Situación | Diseño | Test paramétrico | No paramétrico |\n|:----------|:-------|:-----------------|:--------------------|\n| **Una muestra** vs referencia | $\\bar{x}$ vs $\\mu_0$ | **t-Student** (1 m) | Wilcoxon signed-rank |\n| **Dos muestras independientes** | Grupo A vs B | **t-Student / Welch** | Mann-Whitney $U$ |\n| **Dos muestras pareadas** | Antes vs después | **t pareado** | Wilcoxon paired |\n| **Más de 2 muestras** | 3+ grupos | ANOVA | Kruskal-Wallis |\n\n### Homogeneidad de varianzas — ¿Student o Welch?\n\n::: {.columns}\n::: {.column width=\"50%\"}\n$$H_0: \\sigma_1^2 = \\sigma_2^2 \\quad H_1: \\sigma_1^2 \\neq \\sigma_2^2$$\n\n- $P > 0.05$ → varianzas iguales → **t-Student**\n- $P \\leq 0.05$ → varianzas distintas → **t-Welch**\n:::\n::: {.column width=\"50%\"}\n::: {.callout-tip}\n**Regla práctica:** ante la duda, **usa siempre Welch**. Tiene potencia casi idéntica a Student cuando las varianzas son iguales, y es válido cuando no lo son.\n:::\n:::\n:::\n\n### ¿Bilateral o unilateral?\n\n| | Bilateral | Unilateral |\n|:--|:----------|:-----------|\n| $H_1$ | $\\mu_1 \\neq \\mu_2$ | $\\mu_1 > \\mu_2$ |\n| $\\alpha$ | Repartido en 2 colas | Concentrado en 1 cola |\n| **Regla** | Usar por defecto | Solo con justificación previa |\n\n### Métodos computacionales — Bootstrap\n\nCuando los supuestos no se cumplen y $n$ es pequeño, el **bootstrap** (Efron, 1979) remuestrea los datos con reemplazo $B$ veces para construir la distribución empírica del estadístico sin asumir Normalidad.\n\n## Árbol de decisión clínico — ¿qué test uso?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar=c(0,0,0,0), bg=NA)\nplot(NA, xlim=c(0,10), ylim=c(0,10), axes=F, xlab=\"\", ylab=\"\")\n\n# ── Nodo raíz ──\nrect(4.2, 9.4, 5.8, 10.1, col=\"#2c3e50\", border=NA, lwd=0)\ntext(5, 9.75, \"¿Variable Normal?\", cex=0.78, font=2, col=\"white\")\n\n# Ramas principales con gradiente\nsegments(5, 9.4, 3, 8.6, lwd=3, col=\"#27ae60\")\nsegments(5, 9.4, 7, 8.6, lwd=3, col=\"#c0392b\")\ntext(3.9, 9.0, \"SÍ\", cex=0.75, font=2, col=\"#27ae60\")\ntext(6.1, 9.0, \"NO\", cex=0.75, font=2, col=\"#c0392b\")\n\n# ── Rama SÍ ──\nrect(2.2, 7.9, 3.8, 8.6, col=\"#d5f5e3\", border=\"#27ae60\", lwd=2.5)\ntext(3, 8.25, \"¿n ≥ 60? (TCL)\", cex=0.68, font=2, col=\"#1e6e3e\")\nsegments(3, 7.9, 1.8, 6.9, lwd=2.5, col=\"#27ae60\")\nsegments(3, 7.9, 4.2, 6.9, lwd=2.5, col=\"#e67e22\")\ntext(2.3, 7.4, \"SÍ\", cex=0.65, font=2, col=\"#27ae60\")\ntext(3.7, 7.4, \"NO\", cex=0.65, font=2, col=\"#e67e22\")\n\n# Hoja: t-Student (válido TCL)\nrect(1.0, 6.2, 2.6, 6.8, col=\"#27ae60\", border=NA)\ntext(1.8, 6.5, \"t-Student\\n(válido TCL)\", cex=0.6, font=2, col=\"white\")\n\n# Nodo intermedio: Shapiro\nrect(3.5, 6.2, 4.9, 6.8, col=\"#fef9e7\", border=\"#e67e22\", lwd=2.5)\ntext(4.2, 6.5, \"Shapiro-Wilk\\n¿P > 0.05?\", cex=0.62, font=2, col=\"#e67e22\")\nsegments(4.2, 6.2, 3.5, 5.2, lwd=2, col=\"#27ae60\")\nsegments(4.2, 6.2, 4.9, 5.2, lwd=2, col=\"#c0392b\")\ntext(3.8, 5.7, \"SÍ\", cex=0.6, font=2, col=\"#27ae60\")\ntext(4.5, 5.7, \"NO\", cex=0.6, font=2, col=\"#c0392b\")\n\n# Hojas Shapiro\nrect(2.8, 4.5, 4.0, 5.1, col=\"#27ae60\", border=NA)\ntext(3.4, 4.8, \"t-Student\", cex=0.6, font=2, col=\"white\")\nrect(4.3, 4.5, 5.7, 5.1, col=\"#c0392b\", border=NA)\ntext(5.0, 4.8, \"Wilcoxon /\\nMann-Whitney\", cex=0.55, font=2, col=\"white\")\n\n# ── Rama NO ──\nrect(6.2, 7.9, 7.8, 8.6, col=\"#fadbd8\", border=\"#c0392b\", lwd=2.5)\ntext(7, 8.25, \"¿n ≥ 60? (TCL)\", cex=0.68, font=2, col=\"#c0392b\")\nsegments(7, 7.9, 5.8, 6.9, lwd=2.5, col=\"#27ae60\")\nsegments(7, 7.9, 8.2, 6.9, lwd=2.5, col=\"#c0392b\")\ntext(6.3, 7.4, \"SÍ\", cex=0.65, font=2, col=\"#27ae60\")\ntext(7.7, 7.4, \"NO\", cex=0.65, font=2, col=\"#c0392b\")\n\n# Hojas rama NO\nrect(5.0, 6.2, 6.6, 6.8, col=\"#27ae60\", border=NA)\ntext(5.8, 6.5, \"t-Student\\n(válido TCL)\", cex=0.6, font=2, col=\"white\")\nrect(7.4, 6.2, 9.0, 6.8, col=\"#c0392b\", border=NA)\ntext(8.2, 6.5, \"Wilcoxon /\\nMann-Whitney\", cex=0.55, font=2, col=\"white\")\n\n# ── Leyenda ──\nrect(0.3, 1.4, 1.5, 2.2, col=\"#27ae60\", border=NA)\ntext(1.7, 1.8, \"Test paramétrico\", cex=0.55, pos=4, font=2)\nrect(3.3, 1.4, 4.5, 2.2, col=\"#c0392b\", border=NA)\ntext(4.7, 1.8, \"Test no paramétrico\", cex=0.55, pos=4, font=2)\nrect(6.5, 1.4, 7.7, 2.2, col=\"#fef9e7\", border=\"#e67e22\", lwd=2)\ntext(7.9, 1.8, \"Verificar supuestos\", cex=0.55, pos=4, font=2)\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-1-1.png){fig-alt='Árbol de decisión clínico para elegir el test estadístico adecuado. Empieza preguntando si la variable es Normal. Si es Normal, pregunta si n≥60. Si no es Normal, también pregunta si n≥60. Las ramas llevan a t-Student, Shapiro-Wilk o tests no paramétricos.' width=864}\n:::\n:::\n\n\n::: {.callout-tip}\n**Regla nemotécnica:** Normal + n ≥ 60 → t-Student directo. Normal + n < 60 → verificar Shapiro. No Normal + n ≥ 60 → t-Student (TCL). No Normal + n < 60 → no paramétrico.\n:::\n\n## ¿Por Qué $n \\geq 60$? — Justificación del Teorema Central del Límite\n\n::: {.callout-important}\nEl **Teorema Central del Límite** (Tema 3) establece que para cualquier variable con media $\\mu$ y varianza $\\sigma^2$ finitas:\n\n$$\\frac{\\bar{X} - \\mu}{\\sigma / \\sqrt{n}} \\xrightarrow{\\mathcal{D}} N(0,1) \\quad \\text{cuando} \\quad n \\to \\infty$$\n:::\n\n**¿Qué significa esto en la práctica?** La distribución de $\\bar{X}$ se aproxima a una Normal **sin importar la forma de los datos originales**. La velocidad de convergencia depende de la asimetría de la distribución subyacente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,3), mar=c(3,3,3,1))\nset.seed(123)\nns <- c(5, 15, 30, 60, 100, 200)\nfor(i in 1:length(ns)){\n  n <- ns[i]\n  medias <- replicate(5000, mean(rexp(n, rate=1)))  # exponencial (muy asimétrica)\n  hist(medias, col=\"#d4e6f1\", border=\"white\", freq=FALSE, breaks=30,\n       main=paste0(\"n = \", n), xlab=expression(bar(x)), cex.main=1.1)\n  curve(dnorm(x, mean=1, sd=1/sqrt(n)), add=T, col=\"#c0392b\", lwd=2)\n  if(i==1) legend(\"topright\", c(\"Dist. muestral\", \"Normal teórica\"),\n                  col=c(\"#d4e6f1\",\"#c0392b\"), lwd=c(NA,2), pch=c(15,NA), bty=\"n\", cex=0.7)\n}\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-2-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**¿Por qué exactamente 60?** No es un número mágico, sino un **punto de convergencia empírico**:\n\n| $n$ | Calidad de la aproximación Normal | ¿Test t válido? |\n|:---:|:----------------------------------|:----------------|\n| $n < 15$ | Mala (sesgo visible) | Solo si datos ≈ Normales |\n| $15 \\leq n < 30$ | Aceptable para datos simétricos | Verificar Shapiro-Wilk |\n| $30 \\leq n < 60$ | Buena para la mayoría de casos | t-Student razonable |\n| **$n \\geq 60$** | **Excelente (independiente de la distribución)** | **t-Student válido sin verificar Normalidad** |\n\n::: {.callout-tip}\n**En fisioterapia:** si tienes 60 o más pacientes, el TCL te protege. No necesitas preocuparte por si los datos de ROM, fuerza o dolor son Normales — la media muestral ya lo es. Con menos de 60, verifica siempre la normalidad con Shapiro-Wilk y Q-Q plot.\n:::\n\n## ¿Qué es un Contraste de Hipótesis? — Analogía Judicial\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**El contraste de hipótesis es como un juicio:**\n\n- **$H_0$:** \"El acusado es **inocente**\" (presunción de inocencia)\n- **$H_1$:** \"El acusado es **culpable**\"\n\nLa carga de la prueba recae sobre quien acusa. Se necesita **evidencia suficiente** para rechazar $H_0$. \"No culpable\" no es \"inocente\".\n\n:::\n\n::: {.column width=\"50%\"}\n\n**En estadística aplicada a Fisioterapia:**\n\n- **$H_0$:** \"La terapia no tiene efecto\" (lo asumido)\n- **$H_1$:** \"La terapia sí tiene efecto\" (lo que se investiga)\n\n**No rechazar $H_0 \\neq$ probar $H_0$.** Solo significa que los datos no aportan evidencia suficiente para declarar un efecto.\n\n:::\n:::\n\n## La lógica del contraste — Visualización intuitiva\n\n**Pregunta clave:** ¿Es la diferencia observada lo suficientemente grande como para no deberse al azar?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\npar(mfrow=c(1,2), mar=c(4,4,3,1))\n# Escenario A: Diferencia pequeña (ruido)\ncurve(dnorm(x, 0, 1), -4, 6, lwd=3, col=\"steelblue\", ylab=\"Densidad\",\n      main=\"Caso A: Diferencia NO significativa\", xlab=\"Efecto observado\")\nabline(v=0, lwd=2, col=\"grey40\"); abline(v=0.5, lwd=3, col=\"darkgreen\")\ntext(0.5, 0.35, \"Diferencia\", col=\"darkgreen\", pos=4, font=2)\ntext(2, 0.28, \"Pequeña → probablemente azar\\n→ NO rechazar H0\", col=\"darkgreen\", cex=0.9)\n# Escenario B: Diferencia grande (señal)\ncurve(dnorm(x, 0, 1), -4, 6, lwd=3, col=\"steelblue\", ylab=\"\",\n      main=\"Caso B: Diferencia SIGNIFICATIVA\", xlab=\"Efecto observado\")\nabline(v=0, lwd=2, col=\"grey40\"); abline(v=3, lwd=3, col=\"darkgreen\")\ntext(3, 0.35, \"Diferencia\", col=\"darkgreen\", pos=4, font=2)\ntext(2, 0.28, \"Grande → improbable por azar\\n→ RECHAZAR H0\", col=\"darkgreen\", cex=0.9)\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-3-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**Regla intuitiva:** Si la diferencia observada es tan grande que sería muy raro verla solo por azar ($P < 0.05$), concluimos que hay un efecto real.\n\n## Hipótesis nula y alternativa — Definiciones formales\n\n::: {.callout-note}\nProcedimiento de **Inferencia Estadistica** para tomar una **decisión** sobre un parámetro poblacional usando información **muestral**.\n:::\n\n- **$H_0$ (Nula):** lo asumido cierto. Igualdad, homogeneidad. Especifica distribución conocida.\n- **$H_1$ (Alternativa):** negación de $H_0$. Diferencia, asociación. No especifica distribución.\n\n**Ejemplos:** $H_0: \\mu = \\mu_0$, $H_0: p = p_0$, $H_0: \\mu_1 = \\mu_2$, $H_0: p_1 = p_2$\n\n## Del estadístico muestral al estadístico de contraste — Conexión t3→t4\n\n::: {.callout-note}\n**En Tema 3 aprendiste** que los estadísticos muestrales tienen su propia distribución:\n\n$$\\bar{X} \\sim N\\left(\\mu, \\frac{\\sigma}{\\sqrt{n}}\\right) \\qquad \\text{(distribución de la media muestral)}$$\n\n**En Tema 4 añadimos $H_0$:** si suponemos $H_0: \\mu = \\mu_0$ cierta, entonces:\n\n$$\\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} \\quad \\xrightarrow{H_0} \\quad T = \\frac{\\bar{X} - \\mu_0}{s/\\sqrt{n}} \\sim t_{n-1}$$\n\n**El estadístico de contraste $T$ es simplemente el estadístico muestral $\\bar{X}$ estandarizado bajo $H_0$.**\n:::\n\n**¿Por qué funciona?** Bajo $H_0$, $T$ tiene una distribución **conocida** ($t_{n-1}$). Si el $T$ observado es un valor muy extremo de esa distribución conocida → los datos contradicen $H_0$ → rechazamos $H_0$.\n\n## Desarrollo teórico — Test para $\\mu$\n\n::: {.incremental}\n- $X \\sim N(\\mu, \\sigma)$ → distribución de la variable original\n- $\\bar{x} \\sim N(\\mu, \\sigma/\\sqrt{n})$ → distribución de la media muestral\n- $t_{\\text{exp}} = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}} \\sim t_{n-1}$ → estadístico de contraste bajo $H_0$\n:::\n\n**Ejemplo — METs/semana (n=12):** $\\bar{x}=189.76$, $s=62.02$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn<-12; xbar<-189.76; s<-62.02\ncat(\"Caso a (mu0=200): t =\", round((xbar-200)/(s/sqrt(n)),3),\n    \"P =\", round(2*pt(-abs((xbar-200)/(s/sqrt(n))),11),4),\n    \"\\nCaso b (mu0=230): t =\", round((xbar-230)/(s/sqrt(n)),3),\n    \"P =\", round(2*pt(-abs((xbar-230)/(s/sqrt(n))),11),4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCaso a (mu0=200): t = -0.572 P = 0.5789 \nCaso b (mu0=230): t = -2.248 P = 0.0461\n```\n\n\n:::\n:::\n\n\n## El estadístico de contraste — Visualización del concepto\n\n**Misma idea que en T3, pero ahora bajo $H_0$:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,3), mar=c(4,4,3,1))\n\n# Panel 1: Distribución de X (datos originales)\ncurve(dnorm(x, 130, 5), 115, 145, lwd=3, col=\"steelblue\",\n      main=\"1. Distribución de X\", xlab=\"Flexión (°)\", ylab=\"f(x)\")\nabline(v=130, col=\"darkgreen\", lwd=2); text(135, 0.07, \"μ₀=130\", col=\"darkgreen\", font=2)\n\n# Panel 2: Distribución de la media muestral (T3)\ncurve(dnorm(x, 130, 5/sqrt(6)), 124, 136, lwd=3, col=\"darkgreen\",\n      main=\"2. Dist. de X̄ (Tema 3)\", xlab=\"Media muestral\", ylab=\"f(x̄)\")\nabline(v=130, col=\"darkgreen\", lwd=2); text(131, 0.9, \"μ=130\", col=\"darkgreen\", font=2)\n\n# Panel 3: Estadístico de contraste T (T4 — estandarizado bajo H₀)\ncurve(dt(x, 5), -4, 4, lwd=3, col=\"seagreen\",\n      main=\"3. Estadístico T (Tema 4)\", xlab=\"t = (x̄-μ₀)/(s/√n)\", ylab=\"f(t)\")\nabline(v=0, col=\"darkgreen\", lwd=2); text(1, 0.3, \"0 (H₀ cierta)\", col=\"darkgreen\", font=2)\n# Marcar región de rechazo\nt_crit <- qt(0.975, 5)\nabline(v=c(-t_crit, t_crit), col=\"grey40\", lty=2, lwd=2)\ntext(3, 0.05, \"Rechazo\", col=\"darkgreen\", cex=0.8)\ntext(-3, 0.05, \"Rechazo\", col=\"darkgreen\", cex=0.8)\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-5-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n**Paso 1 (T3):** $\\bar{X}$ es una VA con distribución conocida.\n**Paso 2 (T4):** Estandarizamos bajo $H_0$ → $T \\sim t_{n-1}$. Si $|T|$ es grande → rechazamos $H_0$.\n\n## Errores tipo i ($\\alpha$) y tipo ii ($\\beta$) — Visualización\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualización de errores con dos distribuciones\npar(mar=c(4,4,3,1))\nx <- seq(-4, 8, 0.01)\ny_H0 <- dnorm(x, 0, 1)     # Distribución bajo H0\ny_H1 <- dnorm(x, 3, 1)     # Distribución bajo H1 (efecto real)\nplot(x, y_H0, type=\"l\", lwd=3, col=\"steelblue\", ylab=\"Densidad\",\n     main=expression(paste(\"Errores Tipo I (\", alpha, \") y Tipo II (\", beta, \")\")),\n     ylim=c(0,0.45), xlab=\"Estadístico de contraste\")\nlines(x, y_H1, lwd=3, col=\"seagreen\")\nt_crit <- qnorm(0.975)  # 1.96\nabline(v=t_crit, col=\"grey40\", lty=2, lwd=2)\n# α — cola derecha bajo H0\nxf <- seq(t_crit, 8, 0.01); yf <- dnorm(xf, 0, 1)\npolygon(c(xf, rev(xf)), c(yf, rep(0,length(yf))), col=rgb(0,0,1,0.25), border=NA)\ntext(3.2, 0.04, expression(alpha/2), col=\"blue\", cex=1.3, font=2)\n# β — bajo H1 a la izquierda de t_crit\nxf <- seq(-4, t_crit, 0.01); yf <- dnorm(xf, 3, 1)\npolygon(c(xf, rev(xf)), c(yf, rep(0,length(yf))), col=rgb(0,0.5,0.3,0.2), border=NA)\ntext(0.8, 0.08, expression(beta), col=\"darkgreen\", cex=1.3, font=2)\n# Potencia (1-β)\nxf <- seq(t_crit, 8, 0.01); yf <- dnorm(xf, 3, 1)\npolygon(c(xf, rev(xf)), c(yf, rep(0,length(yf))), col=rgb(0,0.8,0,0.2), border=NA)\ntext(4.8, 0.04, \"1-β\", col=\"darkgreen\", cex=1.2, font=2)\nlegend(\"topleft\", c(expression(H[0]), expression(H[1])), col=c(\"steelblue\",\"seagreen\"), lwd=3, bty=\"n\")\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-6-1.png){fig-alt='Visualización de los errores Tipo I (alfa) y Tipo II (beta) con dos distribuciones normales solapadas. La distribución bajo H0 en azul (centrada en 0) y bajo H1 en verde (centrada en 3). El área azul a la derecha de la línea crítica vertical es alfa (error Tipo I), el área verde a la izquierda es beta (error Tipo II), y el área verde a la derecha es la potencia (1-beta).' width=864}\n:::\n:::\n\n\n| | $H_0$ cierta | $H_0$ falsa |\n|---|---|---|\n| **Aceptar $H_0$** | ✓ $(1-\\alpha)$ | Error II ($\\beta$) |\n| **Rechazar $H_0$** | Error I ($\\alpha$) | ✓ Potencia ($1-\\beta$) |\n\n- $\\alpha$ fijado por el investigador (típicamente 0.05). No depende de $n$.\n- $\\beta$ desconocido. Depende de $n$, $\\alpha$, y magnitud del efecto real.\n- **Para reducir ambos errores:** aumentar $n$.\n\n::: {.callout-note}\n**Definiciones formales (Neyman-Pearson, 1933)**\n\nSea $T$ el estadístico de contraste y $\\mathcal{R}$ la región de rechazo:\n\n$$\\alpha = P(\\text{Rechazar } H_0 \\mid H_0 \\text{ cierta}) = P(T \\in \\mathcal{R} \\mid H_0)$$\n\n$$\\beta = P(\\text{No rechazar } H_0 \\mid H_0 \\text{ falsa}) = P(T \\notin \\mathcal{R} \\mid H_1)$$\n\n$$\\text{Potencia} = 1 - \\beta = P(\\text{Rechazar } H_0 \\mid H_1 \\text{ cierta}) = P(T \\in \\mathcal{R} \\mid H_1)$$\n\n**Relación fundamental:** $\\alpha$ y $\\beta$ están inversamente relacionados. Para un $n$ fijo, reducir $\\alpha$ aumenta $\\beta$. La única forma de reducir ambos simultáneamente es aumentar $n$.\n:::\n\n*Si un estudio con n=10 no rechaza $H_0$, ¿podemos concluir que el tratamiento no funciona? ¿Por qué?*\n\n## Ejemplo de cálculo del p-valor desde la tabla t de Student\n\n**Caso:** $t_{\\text{exp}} = 2.40$ con gl = 10. Obtener P sin ordenador.\n\nEn la fila gl=10 de la tabla t-Student:\n$t_{0.05;10} = 2.228 < 2.40 < t_{0.02;10} = 2.764$\n\nPor tanto: **$0.02 < P < 0.05$** → Significativo (P < 0.05)\n\n**Más ejemplos con gl=10:**\n\n| $t_{\\text{exp}}$ | Acotación | Valor P | Decision ($\\alpha=0.05$) |\n|:---:|:---|:---|:---|\n| 2.40 | $t_{0.05}=2.228 < 2.40 < t_{0.02}=2.764$ | $0.02 < P < 0.05$ | Rechazar $H_0$ |\n| 1.21 | $t_{0.30}=1.093 < 1.21 < t_{0.20}=1.372$ | $0.20 < P < 0.30$ | Aceptar $H_0$ (NS) |\n| 2.11 | $t_{0.10}=1.812 < 2.11 < t_{0.05}=2.228$ | $0.05 < P < 0.10$ | Aceptar $H_0$ (Indicios) |\n| 6.33 | $t_{0.001}=4.587 < 6.33$ | $P < 0.001$ | Rechazar $H_0$ |\n| 0.55 | $0.55 < t_{0.50}=0.700$ | $P > 0.50$ | Aceptar $H_0$ (NS) |\n\n**Con ordenador:** siempre se obtiene P exacta con 3 decimales (o $P < 0.001$).\n\n## Valor p — ¿cómo de sorpresivos son los datos?\n\n**P = probabilidad de observar unos datos tan o más extremos que los nuestros, si $H_0$ fuera cierta.**\n\n::: {.columns}\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualización del P-valor\ncurve(dt(x, 11), -4, 4, lwd=3, col=\"steelblue\", ylab=\"Densidad\",\n      main=\"P-valor visualizado — t(11), texp = 2.25\")\nabline(v=c(-2.25, 2.25), col=\"darkgreen\", lwd=2, lty=2)\n# Área del P-valor (dos colas)\nxr <- seq(2.25, 4, 0.01); yr <- dt(xr, 11)\npolygon(c(xr, rev(xr)), c(yr, rep(0,length(yr))), col=rgb(0,0.5,0.3,0.3), border=NA)\nxl <- seq(-4, -2.25, 0.01); yl <- dt(xl, 11)\npolygon(c(xl, rev(xl)), c(yl, rep(0,length(yl))), col=rgb(0,0.5,0.3,0.3), border=NA)\ntext(0, 0.2, \"P = área verde\", font=2, cex=1.2)\ntext(2.8, 0.03, paste0(\"P = \", round(2*pt(-2.25,11),4)), col=\"darkgreen\", font=2)\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-7-1.png){width=864}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"45%\"}\n\n**Interpretación intuitiva:**\n\n| P | ¿Qué significa? |\n|---|-----------------|\n| **P = 0.58** | Muy probable bajo $H_0$ → **NO** rechazar |\n| **P = 0.03** | Poco probable bajo $H_0$ → **Rechazar** |\n| **P = 0.001** | Muy improbable → **Fuerte evidencia** |\n\n**P NO es** la probabilidad de que $H_0$ sea cierta. **P ES** la probabilidad de los datos si $H_0$ fuera cierta.\n\n:::\n:::\n\n*Un P=0.051 y un P=0.049, ¿son realmente diferentes en su interpretación clínica?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-c(125,132,128,135,130,126); t<-(mean(x)-130)/(sd(x)/sqrt(6))\ncat(\"t =\", round(t,3), \"→ P(t) =\", round(2*pt(-abs(t),5),4),\n    \"\\nP(z aprox) =\", round(2*pnorm(-abs(t)),4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt = -0.432 → P(t) = 0.6835 \nP(z aprox) = 0.6655\n```\n\n\n:::\n:::\n\n\n## Bilateral vs unilateral\n\n| | Bilateral | Unilateral |\n|---|---|---|\n| $H_1$ | $\\mu \\neq \\mu_0$ | $\\mu > \\mu_0$ (o $<$) |\n| $\\alpha$ | 2 colas | 1 cola |\n| Potencia | Menor | Mayor |\n\n::: {.callout-note}\nElegir unilateral **antes** de ver los datos. Elegirlo después = p-hacking.\n:::\n\n## Normalidad — ¿cómo verificarla antes del test?\n\n**Antes de aplicar un test t, debemos verificar la normalidad de la variable (o usar el TCL con $n \\geq 60$).**\n\n**Métodos gráficos:** histograma con curva Normal, diagrama de cajas, Q-Q plot.\n\n**Tests formales:**\n- **Shapiro-Wilk:** la mejor opción para muestras pequeñas y moderadas\n- **Kolmogorov-Smirnov:** solo para muestras grandes (aproximado)\n- **D\\'Agostino:** se puede calcular a mano\n\n**H0 en tests de normalidad:** \"La variable tiene distribución Normal\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos <- c(125,132,128,135,130,126,156, 140, 138, 142, 130, 128)\n# Shapiro-Wilk (R base)\nshapiro.test(datos)  # P > 0.05 → normalidad asumible\n# BioEstatR: test + Q-Q plot en un solo paso\nlibrary(BioEstatR); testnormal(datos)\n```\n:::\n\n\n::: {.callout-warning}\n**Cuidado con muestras pequeñas:** con $n$ pequeño, los tests de normalidad tienen poca potencia. Tienden a NO rechazar $H_{0}$ aunque los datos no sean normales. Complementar SIEMPRE con gráficos.\n:::\n\n## Test para una media (t-Student)\n\n$$t = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}} \\sim t_{n-1}$$\n\n**Ejemplo:** Flexión rodilla en 6 pacientes: 125°,132°,128°,135°,130°,126°. ¿$\\mu = 130°$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(125,132,128,135,130,126)\nt.test(x, mu = 130)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  x\nt = -0.43234, df = 5, p-value = 0.6835\nalternative hypothesis: true mean is not equal to 130\n95 percent confidence interval:\n 125.3695 133.2972\nsample estimates:\nmean of x \n 129.3333 \n```\n\n\n:::\n\n```{.r .cell-code}\n# BioEstatR: testt(m = mean(x), s = sd(x), n = length(x), m0 = 130)\n```\n:::\n\n\n**Salida:** $t=-0.43$, gl=5, $P=0.683$ → No significativo. IC 95%: (126.4°, 132.9°).\n\n## Test para una proporción — Ejemplo detallado\n\n**Contexto:** Prevalencia de tabaquismo en estudiantes. En 2012 era del 22%. En 2013: n=287, x=48 fumadores. ¿Ha cambiado?\n\n**Paso 1 — Hipótesis:** $H_0: p = 0.22$ vs $H_1: p \\neq 0.22$\n\n**Paso 2 — Condiciones:** $np_0 = 287 \\times 0.22 = 63.14 > 5$ ✓; $nq_0 = 287 \\times 0.78 = 223.86 > 5$ ✓\n\n**Paso 3 — Estadístico:** $z = \\frac{x - np_0 - 0.5}{\\sqrt{np_0q_0}} = \\frac{48 - 63.14 - 0.5}{\\sqrt{287 \\times 0.22 \\times 0.78}} = -2.09$\n\n**Paso 4 — P-valor:** $0.03 < P < 0.04$ → **Rechazamos H0** ($P < 0.05$)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-48; n<-287; p0<-0.22\nz<-(x - n*p0 - 0.5)/sqrt(n*p0*(1-p0))\nP<-2*pnorm(-abs(z))\ncat(\"z =\", round(z,3), \"P =\", round(P,4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz = -2.229 P = 0.0258\n```\n\n\n:::\n:::\n\n\n**Conclusión:** La prevalencia ha cambiado significativamente. IC 95% Wilson: (12.7%, 21.7%). El 22% de 2012 no esta en el IC → confirmación visual.\n\n**Si los datos hubieran sido x=33, n=200:** $z=-1.79$, $0.07 < P < 0.08$ → NO significativo (indicios).\n\n## Test para una proporción\n\n$$Z = \\frac{\\hat{p} - p_0}{\\sqrt{p_0(1-p_0)/n}} \\sim N(0,1)$$\n\n::: {.callout-note}\n**Corrección de continuidad:** Para muestras pequeñas, se aplica la corrección de Yates: $Z = \\frac{|x - np_0| - 0.5}{\\sqrt{np_0(1-p_0)}}$. La decisión de usarla depende del contexto clínico y del tamaño muestral.\n:::\n\n**Ejemplo:** 47 de 50 muestras COVID positivas ($\\hat{p}=0.94$). $H_0: p = 0.95$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-47; n<-50; p0<-0.95\nz<-(x/n-p0)/sqrt(p0*(1-p0)/n)\ncat(\"z =\", round(z,3), \"P =\", round(2*pnorm(-abs(z)),4),\n    \"\\nNo significativo: 94% no difiere de 95% (P = 0.745)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz = -0.324 P = 0.7456 \nNo significativo: 94% no difiere de 95% (P = 0.745)\n```\n\n\n:::\n:::\n\n\n## Interpretación de la salida de `testt()` en BioEstatR\n\n**Ejemplo: `testt(m = 129.33, s = 3.78, n = 6, m0 = 130)`**\n\n```\nTest t para una muestra\nH0: mu = 130\nt = -0.432, gl = 5, P = 0.683\nIC 95% para mu: [126.4, 132.9]\nEstimación del efecto bruto: mu - 130 = -0.67\nIC 95% para el efecto: [-4.64, 3.31]\nTest de Shapiro-Wilk: W = 0.956, P = 0.789\n```\n\n**Cómo leer la salida:**\n- **t y P:** estadístico y P-valor → P = 0.683 > 0.05 → NO rechazar H0\n- **IC 95%:** [126.4, 132.9] contiene 130 → compatible con H0\n- **Efecto bruto:** diferencia estimada = -0.67° (clínicamente irrelevante)\n- **Shapiro-Wilk:** P = 0.789 → normalidad OK\n\n::: {.callout-tip}\n**Para el estudiante:** `testt()` integra test + IC + normalidad en una salida. Si P > 0.05 y el IC contiene a μ₀ → no hay evidencia para rechazar H0.\n:::\n\n## BioEstatR — `testt` para una muestra\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(BioEstatR)\n# Media (con estadísticos resumidos)\ntestt(m = 129.33, s = 3.78, n = 6, m0 = 130)\n\n# Proporción (con x y n)\ntestt(x = 47, n = 50, p0 = 0.95)\n```\n:::\n\n\n**Salida de `testt`:** Muestra automáticamente: estadístico, gl, P-valor, IC 95%, estimación del efecto bruto, y test de normalidad (Shapiro-Wilk) para medias.\n\n---\n\n# De una Muestra a Dos Muestras {.center}\n\n## Test para dos medias independientes — Student y welch\n\n**Contexto clínico:** Comparar ROM de rodilla entre dos grupos de fisioterapia.\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Student (asume $\\sigma_1^2 = \\sigma_2^2$):**\n$$t = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_p\\sqrt{1/n_1 + 1/n_2}} \\sim t_{n_1+n_2-2}$$\n$$s_p^2 = \\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1+n_2-2}$$\n\nUsar solo si test F: $P > 0.05$\n:::\n\n::: {.column width=\"50%\"}\n**Welch (NO asume $\\sigma_1^2 = \\sigma_2^2$):**\n$$t = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{s_1^2/n_1 + s_2^2/n_2}} \\sim t_{\\nu}$$\n$$\\nu \\approx \\frac{(s_1^2/n_1 + s_2^2/n_2)^2}{\\frac{(s_1^2/n_1)^2}{n_1-1} + \\frac{(s_2^2/n_2)^2}{n_2-1}}$$\n\ngl por Satterthwaite. **Usar por defecto.**\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng1<-c(125,132,128,135,130,126); g2<-c(140,148,142,155,138,150,145)\nt.test(g1, g2)                     # Welch (recomendado — por defecto en R)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  g1 and g2\nt = -5.8717, df = 10.214, p-value = 0.0001443\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -22.18554 -10.00494\nsample estimates:\nmean of x mean of y \n 129.3333  145.4286 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(g1, g2, var.equal = TRUE)   # Student (solo si σ₁² = σ₂²)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  g1 and g2\nt = -5.6633, df = 11, p-value = 0.0001459\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -22.350490  -9.839987\nsample estimates:\nmean of x mean of y \n 129.3333  145.4286 \n```\n\n\n:::\n:::\n\n\n**IC 95% para la diferencia:** $\\bar{x}_1 - \\bar{x}_2 \\pm t_{\\alpha/2} \\cdot SE$. Si contiene 0 → no significativo.\n\n## Test F para igualdad de varianzas\n\n$$F = s_1^2 / s_2^2 \\sim F_{n_1-1, n_2-1}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar.test(g1, g2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  g1 and g2\nF = 0.39682, num df = 5, denom df = 6, p-value = 0.3294\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.06627422 2.76889997\nsample estimates:\nratio of variances \n         0.3968212 \n```\n\n\n:::\n\n```{.r .cell-code}\n# P > 0.05 → varianzas iguales → Student\n# P ≤ 0.05 → varianzas distintas → Welch\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(df(x,5,5), 0, 4, lwd=3, col=\"steelblue\", main=\"Distribución F(5,5)\")\nabline(v=c(qf(0.025,5,5), qf(0.975,5,5)), col=\"darkgreen\", lty=2)\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-16-1.png){width=864}\n:::\n:::\n\n\n## Test para dos proporciones independientes\n\n$$\\hat{p} = \\frac{x_1+x_2}{n_1+n_2}; \\quad Z = \\frac{\\hat{p}_1 - \\hat{p}_2}{\\sqrt{\\hat{p}(1-\\hat{p})(1/n_1+1/n_2)}}$$\n\n**Ejemplo:** Tratamiento A: 30/50 (60%). Tratamiento B: 18/50 (36%).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx1<-30; n1<-50; x2<-18; n2<-50\np_pool<-(x1+x2)/(n1+n2)\nz<-(x1/n1-x2/n2)/sqrt(p_pool*(1-p_pool)*(1/n1+1/n2))\ncat(\"z =\", round(z,3), \"P =\", round(2*pnorm(-abs(z)),4),\n    \"\\nDiferencia significativa: A > B (P = 0.016)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz = 2.402 P = 0.0163 \nDiferencia significativa: A > B (P = 0.016)\n```\n\n\n:::\n:::\n\n\n**BioEstatR dos muestras:** `testt(m=g1, m1=g2, par=FALSE)` medias. `testp(x1=30, n1=50, x2=18, n2=50)` proporciones.\n\n## El concepto de apareamiento (Pairing)\n\n::: {.callout-note}\n**Apareamiento:** cada sujeto se mide **dos veces** (o dos sujetos se emparejan por caracteristicas). Las observaciones **no son independientes**: pertenecen al mismo individuo o par.\n:::\n\n**¿Por qué aparear?** Elimina la variabilidad **entre sujetos** → **más potencia** para detectar diferencias. Cada sujeto es su propio control.\n\n**Disenos típicos en fisioterapia:**\n- **Antes/Después:** EVA-dolor pre y post tratamiento\n- **Cross-over:** mismo paciente recibe terapia A y B (orden aleatorizado)\n- **Pares emparejados:** dos pacientes con misma edad, sexo, gravedad → uno a cada tratamiento\n- **Bilateral:** medir miembro derecho vs izquierdo del mismo paciente\n\n**Ejemplo visual:** 5 pacientes medidos antes y después:\n\n\n::: {.cell}\n\n```{.r .cell-code}\na<-c(7,8,6,9,7); d<-c(4,5,3,6,5)\nplot(rep(1:2,each=5), c(a,d), pch=19, col=rep(1:5,2), cex=1.5,\n     xaxt=\"n\", xlim=c(0.5,2.5), xlab=\"\", ylab=\"EVA-dolor\",\n     main=\"Datos Pareados: Antes vs Después (n=5)\")\naxis(1, at=1:2, labels=c(\"Antes\",\"Después\"))\nfor(i in 1:5) lines(c(1,2), c(a[i],d[i]), col=i, lty=2)\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-18-1.png){width=864}\n:::\n:::\n\n\n**Todos los pacientes mejoran** (líneas bajan) → evidencia clara de efecto.\n\n## Test pareado para medias\n\n$d_i = x_{i1} - x_{i2}$; $t = \\bar{d}/(s_d/\\sqrt{n}) \\sim t_{n-1}$\n\n**Ejemplo — EVA-dolor pre/post fisioterapia (n=5):**\n\n| Paciente | 1 | 2 | 3 | 4 | 5 |\n|:--------:|:-:|:-:|:-:|:-:|:-:|\n| Antes | 7 | 8 | 6 | 9 | 7 |\n| Después | 4 | 5 | 3 | 6 | 5 |\n| $d_i$ | −3 | −3 | −3 | −3 | −2 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\na<-c(7,8,6,9,7); d<-c(4,5,3,6,5)\nt.test(a, d, paired=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  a and d\nt = 14, df = 4, p-value = 0.000151\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 2.244711 3.355289\nsample estimates:\nmean difference \n            2.8 \n```\n\n\n:::\n\n```{.r .cell-code}\n# BioEstatR: testt(m = a, m1 = d, par = TRUE)\n```\n:::\n\n\n$\\bar{d}=-2.8$, $t=-14.0$, $P<0.001$ → Reducción significativa del dolor.\n\n## Test pareado para proporciones — McNemar\n\n**Tabla de datos apareados:**\n\n| | Después + | Después − |\n|---|---|---|\n| **Antes +** | $n_{11}$ | $n_{12}$ |\n| **Antes −** | $n_{21}$ | $n_{22}$ |\n\n$$\\chi^2 = \\frac{(|n_{12}-n_{21}|-0.5)^2}{n_{12}+n_{21}} \\sim \\chi^2_1$$\n\n**Ejemplo — Terapia A vs B (n=166):** 38 ambas, 15 solo A, 31 solo B, 82 ninguna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn12<-15; n21<-31\nchi2<-(abs(n12-n21)-0.5)^2/(n12+n21)\nP<-pchisq(chi2,1,lower.tail=FALSE)\ncat(\"chi2 =\", round(chi2,3), \"P =\", round(P,4),\n    \"\\nTerapia B significativamente superior (P = 0.027)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchi2 = 5.223 P = 0.0223 \nTerapia B significativamente superior (P = 0.027)\n```\n\n\n:::\n:::\n\n\n## BioEstatR — `testt` pareado, `testp` y `testmcnemar`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(BioEstatR)\n# Medias pareadas\ntestt(m = a, m1 = d, par = TRUE)\n\n# Proporciones pareadas — McNemar\ntestmcnemar(n = c(38, 15, 31, 82))\n\n# Proporciones (general: 1 muestra, 2 muestras, pareadas)\ntestp(x = 47, n = 50, p0 = 0.95)                     # 1 muestra\ntestp(x1 = 30, n1 = 50, x2 = 18, n2 = 50)            # 2 independientes\ntestmcnemar(n = c(38, 15, 31, 82))                          # Pareadas (McNemar)\n```\n:::\n\n\n**`testmcnemar`:** función específica para McNemar. **`testp`:** función general para proporciones (1 muestra, 2 independientes o pareadas).\n\n## ¿Cuándo Usar Tests No Paramétricos?\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Usar cuando:**\n1. $n$ pequeño y datos **no normales** (Shapiro-Wilk $P < 0.05$)\n2. Variables **ordinales** (EVA, escalas Likert)\n3. **Outliers** extremos\n:::\n::: {.column width=\"50%\"}\n**Ventajas:** robustos, pocos supuestos.\n**Desventajas:** menor potencia si se cumplen los supuestos paramétricos. Usan **rangos** en vez de valores originales.\n:::\n:::\n\n## Tests basados en rangos la idea fundamental\n\n::: {.callout-note}\n**¿Qué es un rango?** Dado un conjunto de $n$ observaciones $X_1, X_2, \\ldots, X_n$, el **rango** $R_i$ de la observación $X_i$ es su posición al ordenar todos los valores de menor a mayor:\n\n$$R_i = \\#\\{j : X_j \\leq X_i\\}$$\n:::\n\n**¿Por que usar rangos en lugar de los valores originales?**\n\n1. **Robustez:** Un valor extremo no distorsiona los rangos. Si la ROM máxima pasa de 150° a 300°, su rango solo cambia de $n$ a $n$ (sigue siendo el mayor).\n2. **Invarianza:** Los rangos no dependen de la escala — son los mismos para grados Celsius, Fahrenheit o Kelvin.\n3. **Distribución conocida bajo $H_0$:** Si $H_0$ es cierta (no hay efecto), los rangos se asignan aleatoriamente y su distribución es exactamente conocida — **sin necesidad de asumir Normalidad**.\n\n::: {.example-box}\n**Transformación a rangos — ejemplo visual con $n=6$ pacientes (flexión de rodilla):**\n\n| Paciente | ROM (°) | → Ordenado | → Rango |\n|:--------:|:-------:|:----------:|:-------:|\n| 1 | 125 | 120 | 1 |\n| 2 | 142 | 125 | 2 |\n| 3 | 120 | 130 | 3 |\n| 4 | 155 | 142 | 4 |\n| 5 | 130 | 148 | 5 |\n| 6 | 148 | 155 | 6 |\n\n**Perdemos las distancias, pero conservamos el orden.** Solo sabemos que 155 > 148 > 142 > ...; no sabemos «cuánto mayor».\n:::\n\n*Intuición clínica:* Si un tratamiento es efectivo, los rangos de los pacientes tratados tenderán a ser más altos (o más bajos, según la variable) que los del grupo control. Los tests de rangos cuantifican cuán improbable es observar la configuración de rangos obtenida si el tratamiento no tuviera efecto.\n\n## Test de Wilcoxon Signed-Rank — Cálculo paso a paso\n\n**Contexto:** Queremos contrastar si la mediana poblacional $\\theta$ es igual a un valor de referencia $\\theta_0$.\n\n::: {.callout-note}\n$$H_0: \\theta = \\theta_0 \\quad \\text{vs.} \\quad H_1: \\theta \\neq \\theta_0$$\n:::\n\n::: {.incremental}\n\n**Paso 1 — Calcular las diferencias:** $D_i = X_i - \\theta_0$ para cada observación.\n\n**Paso 2 — Excluir ceros:** Eliminar las observaciones con $D_i = 0$ y reducir $n$ en consecuencia.\n\n**Paso 3 — Rangos de las diferencias absolutas:** Ordenar $|D_1|, |D_2|, \\ldots, |D_n|$ de menor a mayor y asignar rangos $R_i = \\operatorname{rank}(|D_i|)$. Si hay empates, se asigna el rango promedio.\n\n**Paso 4 — Rangos con signo:** $R_i^+ = R_i \\cdot \\operatorname{sign}(D_i)$.\n\n**Paso 5 — El estadístico $W^+$:** Suma de los rangos con diferencias **positivas**:\n\n$$W^+ = \\sum_{i: D_i > 0} R_i$$\n\nAnálogamente, $W^- = \\sum_{i: D_i < 0} R_i$.\n\n**Propiedad de control:** $W^+ + W^- = \\frac{n(n+1)}{2}$\n\n:::\n\n*(Para $n \\geq 12$, $W^+$ se aproxima a una Normal con $\\E[W^+] = \\frac{n(n+1)}{4}$ y $\\Var(W^+) = \\frac{n(n+1)(2n+1)}{24}$. R lo calcula automáticamente.)*\n\n## Wilcoxon Signed-Rank ejemplo de cálculo manual\n\n::: {.example-box}\n**Contexto clínico:** Queremos saber si la flexión de rodilla de 8 pacientes tras una intervención de fisioterapia difiere del valor de referencia poblacional $\\theta_0 = 130°$.\n\n| Paciente | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |\n|:--------:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|\n| ROM (°) | 122 | 135 | 128 | 141 | 131 | 126 | 146 | 139 |\n:::\n\n**$H_0: \\theta = 130°$ vs $H_1: \\theta \\neq 130°$ ($\\alpha = 0.05$)**\n\n**Paso 1 — Calcular $D_i = X_i - 130$:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(122, 135, 128, 141, 131, 126, 146, 139)\ntheta0 <- 130\nD <- x - theta0\ncat(\"Diferencias Di:\", D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDiferencias Di: -8 5 -2 11 1 -4 16 9\n```\n\n\n:::\n:::\n\n\n**Tabla de cálculo manual:**\n\n| $i$ | $X_i$ | $D_i$ | $|D_i|$ | Rango de $|D_i|$ | Signo de $D_i$ | Rango con signo |\n|:---:|:-----:|:-----:|:------:|:----------------:|:--------------:|:---------------:|\n| 1 | 122 | −8 | 8 | 5 | − | −5 |\n| 2 | 135 | +5 | 5 | 4 | + | +4 |\n| 3 | 128 | −2 | 2 | 2 | − | −2 |\n| 4 | 141 | +11 | 11 | 7 | + | +7 |\n| 5 | 131 | +1 | 1 | 1 | + | +1 |\n| 6 | 126 | −4 | 4 | 3 | − | −3 |\n| 7 | 146 | +16 | 16 | 8 | + | +8 |\n| 8 | 139 | +9 | 9 | 6 | + | +6 |\n\n**Comprobación:** $\\sum$ rangos = $1+2+3+4+5+6+7+8 = 36 = \\frac{8 \\cdot 9}{2}$ ✓\n\n**Cálculo de $W^+$ y $W^-$:**\n\n$W^+ = 4 + 7 + 1 + 8 + 6 = 26$ (rangos con signo positivo)\n\n$W^- = 5 + 2 + 3 = 10$ (valores absolutos de rangos con signo negativo)\n\n**Control:** $W^+ + W^- = 26 + 10 = 36 = \\frac{8 \\cdot 9}{2}$ ✓\n\n**Media y varianza bajo $H_0$:**\n\n$\\E[W^+] = \\frac{8 \\cdot 9}{4} = \\frac{72}{4} = 18$\n\n$\\Var(W^+) = \\frac{8 \\cdot 9 \\cdot 17}{24} = \\frac{1224}{24} = 51$\n\n**Estadístico $Z$ y P-valor:**\n$$Z = \\frac{26 - 18}{\\sqrt{51}} = \\frac{8}{7.141} = 1.120, \\quad P = 2 \\times P(Z > 1.12) = 2 \\times 0.1314 = 0.263$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cálculo manual en R\nDi <- x - theta0\nabsDi <- abs(Di)\nrangos <- rank(absDi)\nWplus <- sum(rangos[Di > 0])\nWminus <- sum(rangos[Di < 0])\nE_W <- length(x) * (length(x)+1) / 4\nVar_W <- length(x) * (length(x)+1) * (2*length(x)+1) / 24\nZ_manual <- (Wplus - E_W) / sqrt(Var_W)\nP_manual <- 2 * pnorm(-abs(Z_manual))\ncat(sprintf(\"W+ = %.0f | E[W+] = %.0f | Var(W+) = %.0f\", Wplus, E_W, Var_W),\n    sprintf(\"\\nZ = %.3f | P = %.4f\", Z_manual, P_manual),\n    \"\\n--- Verificación con wilcox.test ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nW+ = 26 | E[W+] = 18 | Var(W+) = 51 \nZ = 1.120 | P = 0.2626 \n--- Verificación con wilcox.test ---\n```\n\n\n:::\n\n```{.r .cell-code}\nwt <- wilcox.test(x, mu = theta0, exact = FALSE)\ncat(sprintf(\"V = %.0f | P = %.4f\", wt$statistic, wt$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nV = 26 | P = 0.2936\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n**Interpretación:** $P = 0.263 > 0.05$ → **No rechazamos $H_0$.** No hay evidencia suficiente para afirmar que la mediana de flexión de rodilla difiera de 130°. La diferencia observada es compatible con el azar.\n:::\n\n## Test de Wilcoxon Signed-Rank pareado\n\n::: {.callout-note}\n**Extensión natural del test para una muestra.** Cuando tenemos **datos pareados** (antes/después), trabajamos con las diferencias $D_i = X_{i,\\text{después}} - X_{i,\\text{antes}}$ y aplicamos exactamente el mismo procedimiento sobre los $D_i$.\n:::\n\n**Ejemplo — EVA-dolor pre/post fisioterapia ($n=6$):**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npre  <- c(7, 8, 6, 9, 7, 8)\npost <- c(4, 5, 3, 6, 5, 4)\nd <- post - pre\ncat(\"Diferencias:\", d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDiferencias: -3 -3 -3 -3 -2 -4\n```\n\n\n:::\n:::\n\n\n| Paciente | Antes | Después | $D_i$ | $|D_i|$ | Rango | Signo | Rango signado |\n|:--------:|:-----:|:-------:|:-----:|:------:|:-----:|:-----:|:-------------:|\n| 1 | 7 | 4 | −3 | 3 | 5 | − | −5 |\n| 2 | 8 | 5 | −3 | 3 | 6 |  | −6 |\n| 3 | 6 | 3 | −3 | 3 | 4 | − | −4 |\n| 4 | 9 | 6 | −3 | 3 | 3 | − | −3 |\n| 5 | 7 | 5 | −2 | 2 | 1.5 | − | −1.5 |\n| 6 | 8 | 4 | −4 | 4 | 7 | − | −7 |\n\n**Nota:** Empate en $|D| = 2$ (pacientes 3 y 5 con mismo $|D|$): rangos promedio. Empate triple en $|D| = 3$ (pacientes 1, 2, 4): rangos 4, 5, 6 → promedio 5.\n\n**$W^+ = 0$** (ninguna diferencia positiva — todos los pacientes mejoraron). **$W^- = 1.5 + 3 + 4 + 5 + 6 + 7 = 26.5$**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verificación con R\nwt_paired <- wilcox.test(post, pre, paired = TRUE, exact = FALSE)\ncat(sprintf(\"W+ = %.1f | P = %.6f\", wt_paired$statistic, wt_paired$p.value),\n    \"\\nTodos los pacientes mejoraron → P < 0.05 (efecto significativo)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nW+ = 0.0 | P = 0.031033 \nTodos los pacientes mejoraron → P < 0.05 (efecto significativo)\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n**Intuición:** Si el tratamiento no tuviera efecto, esperariamos que ~mitad de las diferencias fueran positivas y ~mitad negativas, con $W^+ \\approx W^- \\approx n(n+1)/4$. Que TODAS las diferencias sean del mismo signo es extremadamente improbable bajo $H_0$ → $P$ muy pequeño.\n:::\n\n\n## Ejercicio: Rangos y Outliers\n\n*¿Por qué usar rangos en lugar de los valores originales protege contra outliers?*\n\n## Mann-Whitney $U$ — Cálculo paso a paso\n\n**Contexto:** Comparamos dos grupos **independientes**. $H_0$: las dos poblaciones tienen la misma distribución. $H_1$: las distribuciones difieren.\n\n$$H_0: \\theta_1 = \\theta_2 \\quad \\text{vs.} \\quad H_1: \\theta_1 \\neq \\theta_2$$\n\n::: {.incremental}\n\n**Paso 1 — Combinar y ordenar:** Juntamos las $N = n_1 + n_2$ observaciones y asignamos rangos de 1 a $N$.\n\n**Paso 2 — Sumas de rangos por grupo:**\n$$R_1 = \\sum_{i \\in \\text{Grupo 1}} \\operatorname{rank}(X_i), \\qquad R_2 = \\sum_{j \\in \\text{Grupo 2}} \\operatorname{rank}(X_j)$$\n\n**Paso 3 — El estadístico $U$:**\n$$U_1 = R_1 - \\frac{n_1(n_1+1)}{2}, \\qquad U_2 = R_2 - \\frac{n_2(n_2+1)}{2}$$\n$$U = \\min(U_1, U_2)$$\n\n**Propiedad:** $U_1 + U_2 = n_1 n_2$. Si $U$ es pequeño → un grupo tiende a rangos más altos.\n\n:::\n\n*(Para $n_1, n_2 \\geq 8$, $U$ se aproxima a una Normal con $\\E[U] = \\frac{n_1 n_2}{2}$ y $\\Var(U) = \\frac{n_1 n_2 (n_1+n_2+1)}{12}$. R lo calcula automáticamente.)*\n\n*Si $U$ es muy pequeño, ¿qué nos dice eso sobre los dos grupos?*\n\n## Mann-Whitney $U$ — Ejemplo de cálculo manual\n\n::: {.example-box}\n**Contexto clínico:** Comparamos la ganancia de ROM (en grados) tras 4 semanas de tratamiento en dos grupos independientes:\n\n- **Grupo A** (ejercicio terapéutico, $n_1=5$): 55, 62, 48, 70, 52\n- **Grupo B** (punción seca + ejercicio, $n_2=6$): 72, 68, 75, 80, 65, 78\n:::\n\n**Paso 1 — Ordenar todos los datos conjuntamente y asignar rangos:**\n\n| Valor | 48 | 52 | 55 | 62 | 65 | 68 | 70 | 72 | 75 | 78 | 80 |\n|:-----:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|\n| Grupo | A | A | A | A | B | B | A | B | B | B | B |\n| Rango | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 |\n\n**Paso 2 — Sumas de rangos:** $R_A = 1+2+3+4+7 = 17$, $R_B = 5+6+8+9+10+11 = 49$\n\nControl: $R_A + R_B = 17 + 49 = 66 = \\frac{11 \\cdot 12}{2}$ ✓\n\n**Paso 3 — Estadísticos $U$:**\n$$U_A = 17 - \\frac{5 \\cdot 6}{2} = 17 - 15 = 2$$\n$$U_B = 49 - \\frac{6 \\cdot 7}{2} = 49 - 21 = 28$$\n$$U = \\min(2, 28) = 2$$\n\n**Paso 4 — Media, varianza, $Z$ y P-valor:**\n$$\\E[U] = \\frac{5 \\cdot 6}{2} = 15, \\quad \\Var(U) = \\frac{5 \\cdot 6 \\cdot 12}{12} = 30$$\n$$Z = \\frac{2 - 15}{\\sqrt{30}} = \\frac{-13}{5.477} = -2.374$$\n$$P = 2 \\times \\Phi(-2.374) = 2 \\times 0.0088 = 0.018$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cálculo manual en R\ngrupoA <- c(55, 62, 48, 70, 52)\ngrupoB <- c(72, 68, 75, 80, 65, 78)\ntodos <- c(grupoA, grupoB)\nrangos <- rank(todos)\nR_A <- sum(rangos[1:5])\nR_B <- sum(rangos[6:11])\nU_A <- R_A - 5*6/2\nU_B <- R_B - 6*7/2\nU <- min(U_A, U_B)\nE_U <- 5*6/2\nVar_U <- 5*6*12/12\nZ_U <- (U - E_U) / sqrt(Var_U)\nP_U <- 2 * pnorm(-abs(Z_U))\ncat(sprintf(\"R_A=%.0f | R_B=%.0f | U_A=%.0f | U_B=%.0f | U=%.0f\", R_A,R_B,U_A,U_B,U),\n    sprintf(\"\\nE[U]=%.0f | Var(U)=%.0f | Z=%.3f | P=%.4f\", E_U, Var_U, Z_U, P_U),\n    \"\\n--- Verificación con wilcox.test ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR_A=17 | R_B=49 | U_A=2 | U_B=28 | U=2 \nE[U]=15 | Var(U)=30 | Z=-2.373 | P=0.0176 \n--- Verificación con wilcox.test ---\n```\n\n\n:::\n\n```{.r .cell-code}\nwt_mw <- wilcox.test(grupoA, grupoB, exact = FALSE)\ncat(sprintf(\"W = %.0f | P = %.4f\", wt_mw$statistic, wt_mw$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nW = 2 | P = 0.0225\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n**Interpretación:** $P = 0.018 < 0.05$ → **Rechazamos $H_0$.** La punción seca + ejercicio produce ganancias de ROM significativamente mayores que el ejercicio terapéutico solo. El grupo B tiende a ocupar los rangos más altos (suma de rangos 49 vs 17), lo que indica sistemáticamente mejores resultados.\n:::\n\n## Tests de rangos — Implementación en R y BioEstatR\n\n| Test paramétrico | No paramétrico | R base | BioEstatR |\n|:----------------|:----------------------|:------|:----------|\n| t-test una muestra | Wilcoxon signed-rank | `wilcox.test(x, mu=...)` | - |\n| t-test independientes | Mann-Whitney $U$ | `wilcox.test(x, y)` | `testwx(m=x, m1=y, par=FALSE)` |\n| t-test pareado | Wilcoxon paired | `wilcox.test(x, y, paired=TRUE)` | `testwx(m=x, m1=y, par=TRUE)` |\n\n**Verificación de los ejemplos con R base:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ejemplo signed-rank (una muestra) — datos de ROM\nx <- c(122, 135, 128, 141, 131, 126, 146, 139)\ncat(\"=== Wilcoxon signed-rank (una muestra) ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Wilcoxon signed-rank (una muestra) ===\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(x, mu = 130, exact = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  x\nV = 26, p-value = 0.2936\nalternative hypothesis: true location is not equal to 130\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ejemplo Mann-Whitney (dos muestras independientes)\ngrupoA <- c(55, 62, 48, 70, 52)\ngrupoB <- c(72, 68, 75, 80, 65, 78)\ncat(\"\\n=== Mann-Whitney U ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Mann-Whitney U ===\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(grupoA, grupoB, exact = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  grupoA and grupoB\nW = 2, p-value = 0.02248\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n**¿Y los empates? ¿Y la corrección por continuidad?** `wilcox.test()` en R lo gestiona todo automáticamente: asigna rangos promedio cuando hay empates, corrige la varianza, y aplica corrección por continuidad para muestras pequenas. Tú solo necesitas interpretar el P-valor.\n\n**¿Y si tengo 3 o más grupos?** El test de **Kruskal-Wallis** (`kruskal.test()`) generaliza el Mann-Whitney para $k \\geq 3$ grupos independientes. Es la alternativa no paramétrica al ANOVA.\n:::\n\n## McNemar no paramétrico: Diferencias de proporciones apareadas— BioEstatR\n\n**`testmcnemar` — salida completa e interpretación:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(BioEstatR)\n# Datos del ejemplo de terapias (n=166)\ntestmcnemar(n = c(38, 15, 31, 82))\n\n# Salida tipica:\n# Test de McNemar para proporciones apareadas\n# χ² = 4.89, gl = 1, P = 0.027\n# Diferencia: -9.5% (IC 95%: -17.4% a -1.7%)\n# Conclusión: Terapia B significativamente superior\n```\n:::\n\n\n::: {.callout-tip}\n**Interpretación de la salida de `testmcnemar`:**\n- $\\chi^2$ y P-valor: decisión del test\n- Diferencia con IC 95%: magnitud del efecto (si IC no contiene 0 → significativo)\n- Tamaño muestral: $n$ necesario para detectar diferencia $\\delta$ con potencia deseada\n:::\n\n---\n\n# Más Allá del Test: Potencia y Tamaño del Efecto {.center}\n\n## Tamaño muestral para potencia deseada\n\n**Diferencia de medias** (por grupo):\n\n$$n \\approx \\frac{2(z_{1-\\alpha/2} + z_{1-\\beta})^2 \\cdot s^2}{\\delta^2}$$\n\n**Diferencia de proporciones:**\n\n$$n \\approx \\frac{(z_{1-\\alpha/2} + z_{1-\\beta})^2 \\cdot [p_1(1-p_1) + p_2(1-p_2)]}{\\delta^2}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndelta<-5; s<-12; z_a<-qnorm(0.975); z_b<-qnorm(0.80)\nn<-ceiling(2*(z_a+z_b)^2*s^2/delta^2)\ncat(\"n por grupo =\", n, \"→ n total =\", 2*n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn por grupo = 91 → n total = 182\n```\n\n\n:::\n\n```{.r .cell-code}\n# BioEstatR: nm(d = 5, s = 12, potencia = 0.80)        # medias\n# BioEstatR: np(x = c(30,18), n = c(50,50), d = 0.05)  # proporciones\n```\n:::\n\n\n## Derivación de la fórmula de tamaño muestral para potencia\n\n**Punto de partida:** Recordemos el gráfico de errores Tipo I y II (visto anteriormente). Bajo $H_0$, el estadístico $t$ se distribuye alrededor de 0. Bajo $H_1$ (efecto real $\\delta$), la distribución se **desplaza** hacia la derecha. La potencia $1-\\beta$ es el área bajo la curva desplazada que cae en la región de rechazo.\n\n::: {.callout-note}\n**Para detectar una diferencia $\\delta$ con potencia $1-\\beta$ y nivel $\\alpha$:**\n\n$$n \\approx \\frac{2(z_{1-\\alpha/2} + z_{1-\\beta})^2 \\cdot s^2}{\\delta^2}$$\n\ndonde $z_{1-\\alpha/2}$ y $z_{1-\\beta}$ son los cuantiles de la Normal estandar.\n:::\n\n**¿Qué nos dice esta fórmula?** $n$ aumenta cuando: $\\downarrow\\delta$ (buscas diferencias pequeñas), $\\uparrow s$ (los datos son más variables), $\\uparrow 1-\\beta$ (quieres más potencia), $\\downarrow\\alpha$ (eres más exigente).\n\n## Derivación de $n$ — Paso a paso y ejemplo numérico\n\n**Paso 1 — El estadístico bajo $H_1$:** $t = \\frac{\\bar{x}_1 - \\bar{x}_2}{s\\sqrt{2/n}} \\approx N\\left(\\frac{\\delta}{s\\sqrt{2/n}}, 1\\right)$\n\n**Paso 2 — Condición de potencia:** $P(\\text{rechazar } H_0 \\mid H_1 \\text{ cierta}) = 1-\\beta$\n\n**Paso 3 — Despejar $n$:** $z_{1-\\beta} = \\frac{\\delta}{s\\sqrt{2/n}} - z_{1-\\alpha/2} \\;\\Rightarrow\\; \\sqrt{n} = \\frac{(z_{1-\\alpha/2} + z_{1-\\beta})s\\sqrt{2}}{\\delta}$\n\nElevando al cuadrado: $n = \\frac{2(z_{1-\\alpha/2} + z_{1-\\beta})^2 s^2}{\\delta^2}$\n\n**Ejemplo numérico — Flexión de hombro:** $\\delta=5°$, $s=12°$, $\\alpha=0.05$, $1-\\beta=0.80$:\n\n$n = \\frac{2(1.96 + 0.842)^2 \\cdot 144}{25} = \\frac{2 \\cdot 7.85 \\cdot 144}{25} = \\frac{2260.6}{25} = 90.4 \\to 91$ por grupo\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndelta<-5; s<-12; z_a<-qnorm(0.975); z_b<-qnorm(0.80)\nn<-ceiling(2*(z_a+z_b)^2*s^2/delta^2)\ncat(\"n =\", n, \"por grupo (total =\", 2*n, \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 91 por grupo (total = 182 )\n```\n\n\n:::\n:::\n\n\n## Ejemplo detallado — Proteína α-klotho y edad\n\n::: {.example-box}\n**Contexto:** Se compara la concentración de proteína α-Klotho (pg/mL) entre pacientes jóvenes y ancianos.\n\n- **Jóvenes:** $n_1=20$, $\\bar{x}_1=450$, $s_1=89$\n- **Ancianos:** $n_2=16$, $\\bar{x}_2=380$, $s_2=96$\n:::\n\n**Paso 1 — Hipótesis:** $H_0: \\mu_1 = \\mu_2$ vs $H_1: \\mu_1 \\neq \\mu_2$\n\n**Paso 2 — ¿Varianzas iguales?** Test F:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulamos datos con las estadísticas dadas\nset.seed(42)\njovenes <- rnorm(20, 450, 89)\nancianos <- rnorm(16, 380, 96)\nvar.test(jovenes, ancianos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  jovenes and ancianos\nF = 1.2642, num df = 19, denom df = 15, p-value = 0.6521\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.4558825 3.3085061\nsample estimates:\nratio of variances \n          1.264179 \n```\n\n\n:::\n:::\n\n\n**Paso 3 — Test t (Student, si F no significativo):**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Student (varianzas iguales)\nt.test(jovenes, ancianos, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  jovenes and ancianos\nt = 2.5585, df = 34, p-value = 0.01514\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n  19.64736 171.39102\nsample estimates:\nmean of x mean of y \n 467.0809  371.5617 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Welch (por seguridad, siempre recomendado)\nt.test(jovenes, ancianos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  jovenes and ancianos\nt = 2.5929, df = 33.573, p-value = 0.01399\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n  20.61776 170.42062\nsample estimates:\nmean of x mean of y \n 467.0809  371.5617 \n```\n\n\n:::\n:::\n\n\n**Paso 4 — Interpretación:** La diferencia de ~70 pg/mL es significativa (P < 0.05). El IC 95% para $\\mu_1 - \\mu_2$ no contiene 0.\n\n## Tamaño del efecto — D de cohen y omega Cuadrado\n\n::: {.formula-box}\n**d de Cohen:** $d_c = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_p}$, donde $s_p = \\sqrt{\\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1+n_2-2}}$\n\n**Omega cuadrado:** $\\omega^2 = \\frac{t^2 - 1}{t^2 + n_1 + n_2 - 1}$\n:::\n\n| d de Cohen | Interpretación | Ejemplo clínico |\n|:---:|:---|:---|\n| $|d| < 0.2$ | **Negligible** | Sin diferencia práctica |\n| $0.2 \\leq |d| < 0.5$ | **Pequeño** | Diferencia detectable pero modesta |\n| $0.5 \\leq |d| < 0.8$ | **Mediano** | Diferencia clínicamente relevante |\n| $|d| \\geq 0.8$ | **Grande** | Diferencia muy importante |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx1 <- 450; x2 <- 380; s1 <- 89; s2 <- 96; n1 <- 20; n2 <- 16\nsp <- sqrt(((n1-1)*s1^2 + (n2-1)*s2^2) / (n1+n2-2))\ndc <- (x1 - x2) / sp\nt_val <- (x1 - x2) / (sp * sqrt(1/n1 + 1/n2))\nomega2 <- (t_val^2 - 1) / (t_val^2 + n1 + n2 - 1)\ncat(\"s_p =\", round(sp,1), \"\\nd de Cohen =\", round(dc,2),\n    \"→\", ifelse(abs(dc)>=0.8,\"GRANDE\",ifelse(abs(dc)>=0.5,\"MEDIANO\",\"PEQUEÑO\")),\n    \"\\nOmega² =\", round(omega2,3), \"→\", round(omega2*100,1), \"% varianza explicada\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ns_p = 92.2 \nd de Cohen = 0.76 → MEDIANO \nOmega² = 0.103 → 10.3 % varianza explicada\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n**Para el estudiante:** El P-valor dice si hay diferencia, pero **no cuán grande es**. El tamaño del efecto (d de Cohen) complementa al P-valor. Siempre reporta ambos [@cohen1988].\n:::\n\n## Diagrama de decisión — ¿qué test usar?\n\n::: {.decision-tree}\n**¿Qué tipo de variable?**\n\n→ **Continua (ROM, fuerza, dolor):**\n  → ¿Cuántas muestras?\n    → **1 muestra:** ¿Normal? → Sí: `t.test(x, mu=...)` / No: `wilcox.test(x, mu=...)`\n    → **2 muestras independientes:** ¿Normal? → Sí: ¿Varianzas iguales?\n      → Sí: `t.test(x, y, var.equal=TRUE)` (Student)\n       No: `t.test(x, y)` (Welch)\n      → No normal: `wilcox.test(x, y)` (Mann-Whitney)\n     **2 muestras pareadas:** ¿Normal de las diferencias? → Sí: `t.test(x, y, paired=TRUE)` / No: `wilcox.test(x, y, paired=TRUE)`\n\n→ **Categórica (mejoría sí/no, tipo de lesión):**\n  → ¿Cuántas muestras?\n    → **1 proporción:** `prop.test(x, n, p=p0)`\n    → **2 proporciones independientes:** `prop.test(c(x1,x2), c(n1,n2))` o χ² (Tema 5)\n    → **2 proporciones pareadas:** `mcnemar.test()` (McNemar)\n:::\n\n## Diagrama visual — Arbol de decisión\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar = c(2, 1, 3, 1), bg = \"white\")\nlayout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE), heights = c(1, 3))\n\n# ── PANEL SUPERIOR: Pregunta raíz ──\npar(mar = c(0, 0, 0, 0))\nplot(NA, xlim = c(0, 10), ylim = c(0, 1.5), axes = FALSE, xlab = \"\", ylab = \"\")\nrect(2.5, 0.5, 7.5, 1.3, col = \"#2c3e50\", border = NA, lwd = 0)\ntext(5, 0.9, \"¿Qué tipo de variable?\", font = 2, cex = 1.5, col = \"white\")\narrows(5, 0.5, 5, 0.15, lwd = 3, col = \"#2c3e50\", length = 0.1)\n\n# ── PANEL IZQUIERDO: Variables Continuas ──\npar(mar = c(0, 1, 0, 1))\nplot(NA, xlim = c(0, 10), ylim = c(0, 10), axes = FALSE, xlab = \"\", ylab = \"\")\n# Title\nrect(1, 9, 9, 9.8, col = \"#2980b9\", border = NA)\ntext(5, 9.4, \"Variable CONTINUA\", font = 2, cex = 1, col = \"white\")\ntext(5, 8.7, \"ROM, fuerza, dolor, EVA, grados...\", cex = 0.7, col = \"#555\")\n\n# 3 columns\ncol_x <- c(2, 5, 8)  # centers of 3 columns\n\nfor (i in 1:3) {\n  # Arrow from title to column\n  segments(col_x[i], 8.7, col_x[i], 8, lwd = 2, col = \"#2980b9\")\n  arrows(col_x[i], 8, col_x[i], 7.85, lwd = 0, col = \"#2980b9\", length = 0.08)\n}\n\n# Column 1: 1 muestra\nrect(col_x[1]-1.3, 6.8, col_x[1]+1.3, 7.8, col = \"#ecf0f1\", border = \"#2980b9\", lwd = 2)\ntext(col_x[1], 7.3, \"1 muestra\", font = 2, cex = 0.9, col = \"#2c3e50\")\n# Arrow down\nsegments(col_x[1], 6.8, col_x[1], 6, lwd = 1.5, col = \"#2c3e50\")\n# Condition: ¿Normal?\nrect(col_x[1]-1.3, 5, col_x[1]+1.3, 6, col = \"#e8f8f5\", border = \"#1abc9c\", lwd = 1.5)\ntext(col_x[1], 5.5, \"¿Normal?\", font = 2, cex = 0.75, col = \"#1abc9c\")\n# Branches Sí/No\narrows(col_x[1]-0.8, 5, col_x[1]-0.8, 3.5, lwd = 1.5, col = \"#27ae60\", length = 0.1)\narrows(col_x[1]+0.8, 5, col_x[1]+0.8, 3.5, lwd = 1.5, col = \"#e67e22\", length = 0.1)\ntext(col_x[1]-1.1, 4.3, \"Sí\", cex = 0.6, col = \"#27ae60\", font = 2)\ntext(col_x[1]+0.5, 4.3, \"No\", cex = 0.6, col = \"#e67e22\", font = 2)\n# Test boxes\nrect(col_x[1]-1.8, 1.5, col_x[1], 3.2, col = \"#27ae60\", border = NA)\ntext(col_x[1]-0.9, 2.35, \"t.test\\n(x, mu=...)\", font = 2, cex = 0.7, col = \"white\")\nrect(col_x[1]+0.1, 1.5, col_x[1]+1.8, 3.2, col = \"#e67e22\", border = NA)\ntext(col_x[1]+0.95, 2.35, \"wilcox.test\\n(x, mu=...)\", font = 2, cex = 0.7, col = \"white\")\n\n# Column 2: 2 muestras independientes\nrect(col_x[2]-1.7, 6.8, col_x[2]+1.7, 7.8, col = \"#ecf0f1\", border = \"#2980b9\", lwd = 2)\ntext(col_x[2], 7.3, \"2 muestras indep.\", font = 2, cex = 0.9, col = \"#2c3e50\")\nsegments(col_x[2], 6.8, col_x[2], 6, lwd = 1.5, col = \"#2c3e50\")\nrect(col_x[2]-1.7, 5, col_x[2]+1.7, 6, col = \"#e8f8f5\", border = \"#1abc9c\", lwd = 1.5)\ntext(col_x[2], 5.5, \"¿Normal?\", font = 2, cex = 0.75, col = \"#1abc9c\")\n# Sí branch → ¿varianzas?\narrows(col_x[2]-1, 5, col_x[2]-1, 3.5, lwd = 1.5, col = \"#27ae60\", length = 0.1)\ntext(col_x[2]-1.3, 4.3, \"Sí\", cex = 0.6, col = \"#27ae60\", font = 2)\nrect(col_x[2]-2.3, 2.3, col_x[2]-0.9, 3.5, col = \"#fef9e7\", border = \"#f39c12\", lwd = 1.2)\ntext(col_x[2]-1.6, 2.9, \"¿σ² igual?\", font = 2, cex = 0.55, col = \"#e67e22\")\narrows(col_x[2]-2.2, 2.3, col_x[2]-2.8, 1, lwd = 1.2, col = \"#27ae60\", length = 0.08)\narrows(col_x[2]-1, 2.3, col_x[2]-0.3, 1, lwd = 1.2, col = \"#e74c3c\", length = 0.08)\nrect(col_x[2]-3.5, 0, col_x[2]-2.2, 1, col = \"#27ae60\", border = NA)\ntext(col_x[2]-2.85, 0.5, \"Student\", font = 2, cex = 0.55, col = \"white\")\nrect(col_x[2]-1.2, 0, col_x[2]+0.2, 1, col = \"#2980b9\", border = NA)\ntext(col_x[2]-0.5, 0.5, \"Welch\", font = 2, cex = 0.55, col = \"white\")\n# No branch → Mann-Whitney\narrows(col_x[2]+1, 5, col_x[2]+1, 3.5, lwd = 1.5, col = \"#e74c3c\", length = 0.1)\ntext(col_x[2]+1.4, 4.3, \"No\", cex = 0.6, col = \"#e74c3c\", font = 2)\nrect(col_x[2]+0.1, 1.5, col_x[2]+2.7, 3.2, col = \"#e74c3c\", border = NA)\ntext(col_x[2]+1.4, 2.35, \"wilcox.test\\n(x, y)\", font = 2, cex = 0.7, col = \"white\")\n\n# Column 3: 2 muestras pareadas\nrect(col_x[3]-1.5, 6.8, col_x[3]+1.5, 7.8, col = \"#ecf0f1\", border = \"#2980b9\", lwd = 2)\ntext(col_x[3], 7.3, \"2 muestras par.\", font = 2, cex = 0.9, col = \"#2c3e50\")\nsegments(col_x[3], 6.8, col_x[3], 6, lwd = 1.5, col = \"#2c3e50\")\nrect(col_x[3]-1.5, 5, col_x[3]+1.5, 6, col = \"#e8f8f5\", border = \"#1abc9c\", lwd = 1.5)\ntext(col_x[3], 5.5, \"¿Dif. Normal?\", font = 2, cex = 0.75, col = \"#1abc9c\")\narrows(col_x[3]-0.8, 5, col_x[3]-0.8, 3.5, lwd = 1.5, col = \"#27ae60\", length = 0.1)\narrows(col_x[3]+0.8, 5, col_x[3]+0.8, 3.5, lwd = 1.5, col = \"#e67e22\", length = 0.1)\ntext(col_x[3]-1.1, 4.3, \"Sí\", cex = 0.6, col = \"#27ae60\", font = 2)\ntext(col_x[3]+0.5, 4.3, \"No\", cex = 0.6, col = \"#e67e22\", font = 2)\nrect(col_x[3]-2, 1.5, col_x[3], 3.2, col = \"#27ae60\", border = NA)\ntext(col_x[3]-1, 2.35, \"t.test\\npaired=TRUE\", font = 2, cex = 0.7, col = \"white\")\nrect(col_x[3]+0.1, 1.5, col_x[3]+2, 3.2, col = \"#e67e22\", border = NA)\ntext(col_x[3]+1.05, 2.35, \"wilcox.test\\npaired=TRUE\", font = 2, cex = 0.7, col = \"white\")\n\n# ── PANEL DERECHO: Variables Categóricas ──\npar(mar = c(0, 1, 0, 1))\nplot(NA, xlim = c(0, 10), ylim = c(0, 10), axes = FALSE, xlab = \"\", ylab = \"\")\n# Title\nrect(1, 9, 9, 9.8, col = \"#8e44ad\", border = NA)\ntext(5, 9.4, \"Variable CATEGÓRICA\", font = 2, cex = 1, col = \"white\")\ntext(5, 8.7, \"Mejoría (Sí/No), tipo de lesión, grupo...\", cex = 0.7, col = \"#555\")\n\n# 3 columns\nfor (i in 1:3) {\n  segments(col_x[i], 8.7, col_x[i], 8, lwd = 2, col = \"#8e44ad\")\n  arrows(col_x[i], 8, col_x[i], 7.85, lwd = 0, col = \"#8e44ad\", length = 0.08)\n}\n\n# Column 1: 1 proporción\nrect(col_x[1]-1.3, 6.5, col_x[1]+1.3, 7.8, col = \"#ecf0f1\", border = \"#8e44ad\", lwd = 2)\ntext(col_x[1], 7.15, \"1 proporción\", font = 2, cex = 0.85, col = \"#2c3e50\")\nsegments(col_x[1], 6.5, col_x[1], 5, lwd = 2, col = \"#27ae60\")\nrect(col_x[1]-1.5, 2.5, col_x[1]+1.5, 5, col = \"#27ae60\", border = NA)\ntext(col_x[1], 3.75, \"prop.test\\n(x, n, p=...)\", font = 2, cex = 0.8, col = \"white\")\n\n# Column 2: 2 proporciones independientes\nrect(col_x[2]-1.7, 6.5, col_x[2]+1.7, 7.8, col = \"#ecf0f1\", border = \"#8e44ad\", lwd = 2)\ntext(col_x[2], 7.15, \"2 prop. indep.\", font = 2, cex = 0.85, col = \"#2c3e50\")\nsegments(col_x[2], 6.5, col_x[2], 5, lwd = 2, col = \"#27ae60\")\nrect(col_x[2]-1.7, 3, col_x[2]+1.7, 5, col = \"#27ae60\", border = NA)\ntext(col_x[2], 4, \"prop.test()\", font = 2, cex = 0.8, col = \"white\")\nrect(col_x[2]-1.7, 1, col_x[2]+1.7, 2.8, col = \"#3498db\", border = NA)\ntext(col_x[2], 1.9, \"o χ² (Tema 5)\", font = 2, cex = 0.7, col = \"white\")\n\n# Column 3: 2 proporciones pareadas\nrect(col_x[3]-1.5, 6.5, col_x[3]+1.5, 7.8, col = \"#ecf0f1\", border = \"#8e44ad\", lwd = 2)\ntext(col_x[3], 7.15, \"2 prop. par.\", font = 2, cex = 0.85, col = \"#2c3e50\")\nsegments(col_x[3], 6.5, col_x[3], 5, lwd = 2, col = \"#27ae60\")\nrect(col_x[3]-1.5, 2.5, col_x[3]+1.5, 5, col = \"#27ae60\", border = NA)\ntext(col_x[3], 3.75, \"mcnemar.test()\", font = 2, cex = 0.8, col = \"white\")\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-34-1.png){width=864}\n:::\n:::\n\n\n\n## Paramétricos vs no paramétricos — Comparativa\n\n| Criterio | Paramétricos | No Paramétricos |\n|:---------|:------------|:----------------|\n| **Supuestos** | Normalidad + homocedasticidad | Mínimos (solo continuidad) |\n| **Escala** | Intervalo o razón | Ordinal o superior |\n| **Potencia** | Mayor (si supuestos se cumplen) | Menor (~95% del paramétrico) |\n| **Estadístico** | Usa valores originales ($\\bar{x}$, $s$) | Usa **rangos** |\n| **IC** | Basados en $t$-Student | Basados en medianas (Hodges-Lehmann) |\n| **Muestras pequeñas** | Sensible a no normalidad | Robusto |\n| **Ejemplo (2 ind.)** | t-test de Student/Welch | Mann-Whitney U |\n| **Ejemplo (pareado)** | t-test pareado | Wilcoxon signed-rank |\n\n::: {.callout-important}\n**Regla práctica:** Si $n \\geq 30$ por grupo y datos sin outliers extremos → paramétrico. Si $n < 15$ y normalidad dudosa → no paramétrico. Entre 15 y 30, verificar con Shapiro-Wilk.\n\n**¿Quieres entender la matemática detrás de estos tests?** Repasa las diapositivas anteriores: derivación del estadístico $W^+$ de Wilcoxon, el estadístico $U$ de Mann-Whitney, y los ejemplos de cálculo manual paso a paso con datos de fisioterapia.\n:::\n\n## Precauciones al leer p-valores en la literatura clínica\n\n::: {.callout-warning}\n**Tres trampas frecuentes al interpretar P-valores en artículos de fisioterapia:**\n:::\n\n| Trampa | Problema | Cómo protegerte |\n|:-------|:---------|:----------------|\n| **Comparaciones múltiples** | Si un estudio compara 20 outcomes, ~1 saldrá significativo ($P<0.05$) solo por azar | Busca correcciones (Bonferroni, Holm). Desconfía de \"outcomes exploratorios\" |\n| **Muestras enormes** | Con $n>1000$, diferencias **clínicamente irrelevantes** (1° de ROM) pueden dar $P<0.001$ | Mira siempre el tamaño del efecto (d de Cohen) y el IC 95%, no solo el P-valor |\n| **Muestras pequeñas** | Con $n=10$, un efecto **clínicamente importante** puede dar $P>0.05$ | \"No significativo\" ≠ \"no hay efecto\". Comprueba la potencia del estudio |\n\n**Regla de oro para tu TFG/TFM:** Reporta siempre los 4 elementos: (1) P-valor exacto, (2) IC 95% del efecto, (3) tamaño del efecto (d de Cohen), (4) tu juicio sobre la **relevancia clínica** de la diferencia observada [@greenland2016].\n\n## Declaración asa sobre p-valores [@wasserstein2016]\n\n::: {.callout-warning}\n**La American Statistical Association (2016) publicó 6 principios sobre el uso correcto del P-valor:**\n:::\n\n1. **El P-valor indica cuán incompatibles son los datos con un modelo estadístico** (generalmente $H_0$)\n2. **El P-valor NO mide** la probabilidad de que $H_0$ sea verdadera, ni la probabilidad de que los datos se produzcan solo por azar\n3. **Las conclusiones científicas** no deben basarse solo en si un P-valor supera un umbral\n4. **La inferencia correcta** requiere considerar el diseño del estudio, la calidad de las mediciones, y la plausibilidad de los supuestos\n5. **El P-valor NO mide** el tamaño del efecto ni la importancia clínica del resultado\n6. **Por sí solo, el P-valor no es una buena medida** de la evidencia sobre un modelo\n\n**Buena práctica en fisioterapia:** Reportar **siempre**: (1) P-valor exacto, (2) IC 95% para el efecto, (3) tamaño del efecto (d de Cohen), y (4) juicio sobre la **relevancia clínica** de la diferencia observada [@greenland2016].\n\n---\n\n# Resumen {.center}\n\n::: {.incremental}\n\n1. **$H_0$:** igualdad. **$H_1$:** diferencia. $\\alpha$ fijado, $\\beta$ desconocido\n\n2. **P-valor:** `2*pt(-abs(t), df)` bilateral. **Nunca** para $\\chi^2$ o F\n\n3. **Una muestra:** `testt(m, s, n, m0)` para media, `testt(x, n, p0)` para proporción\n\n4. **Dos muestras independientes:** `t.test(x, y)` (Welch) o `t.test(x, y, var.equal=TRUE)` (Student)\n\n5. **Pareado:** `testt(m, m1, par=TRUE)`. `testp(n=c(n11,n12,n21,n22))` para proporciones\n\n6. **No paramétrico:** `testwx(m, m1)` para Wilcoxon/Mann-Whitney\n\n7. **Tamaño muestral:** `nm()` para medias, `np()` para proporciones. $n \\propto 1/\\delta^2$\n\n:::\n\n::: {.exercise}\n**Ejercicio Clínico — Contraste de Hipótesis en Fisioterapia**\n\nUn estudio compara dos tratamientos para lumbalgia crónica: ejercicio terapéutico (grupo A, n=25) y punción seca + ejercicio (grupo B, n=28). La EVA a las 4 semanas fue:\n\n- Grupo A: $\\bar{x}_A = 4.8$, $s_A = 2.1$\n- Grupo B: $\\bar{x}_B = 3.2$, $s_B = 1.9$\n\n1. Formula $H_0$ y $H_1$. ¿Qué test usarías? Usa `testt()` de BioEstatR para realizarlo.\n2. Interpreta el P-valor. ¿Es significativo a $\\alpha = 0.05$?\n3. ¿Qué error (Tipo I o Tipo II) cometerías si la diferencia real fuera nula y rechazas $H_0$?\n:::\n\n## Diagrama de decisión — Ejercicio clínico paso a paso\n\n**Escenario:** Dos tratamientos para lumbalgia crónica. EVA a las 4 semanas. Grupo A ($n_A=25$) vs Grupo B ($n_B=28$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar = c(0, 0, 0, 0))\nplot(NA, xlim = c(0, 12), ylim = c(0, 14), axes = FALSE, xlab = \"\", ylab = \"\")\n\n# ── Paso 1 ──\nrect(4, 13, 8, 14, col = \"#2c3e50\", border = NA, lwd = 0)\ntext(6, 13.5, \"PASO 1: ¿Tipo de variable?\", font = 2, cex = 1.1, col = \"white\")\ntext(6, 12.5, \"EVA-dolor → Variable continua (escala 0-10)\", cex = 0.85, col = \"#2c3e50\")\nsegments(6, 12.5, 6, 11.5, lwd = 2.5, col = \"#2c3e50\")\n\n# ── Paso 2 ──\nrect(4, 10.5, 8, 11.5, col = \"#34495e\", border = NA)\ntext(6, 11, \"PASO 2: ¿Cuántas muestras?\", font = 2, cex = 1.1, col = \"white\")\ntext(6, 10, \"Dos muestras independientes\\n(Grupo A ≠ Grupo B, pacientes distintos)\", cex = 0.85, col = \"#34495e\")\nsegments(6, 10, 6, 9, lwd = 2.5, col = \"#34495e\")\n\n# ── Paso 3 ── Decisión: ¿Normalidad?\nrect(4, 8, 8, 9, col = \"#e8f8f5\", border = \"#1abc9c\", lwd = 2.5)\ntext(6, 8.5, \"PASO 3: ¿Se cumple Normalidad?\\n(Shapiro-Wilk en cada grupo)\", font = 2, cex = 0.9, col = \"#1abc9c\")\n\n# Ramas desde Paso 3\nsegments(4, 8.5, 1.5, 6, lwd = 2.2, col = \"#1abc9c\")\nsegments(8, 8.5, 10.5, 6, lwd = 2.2, col = \"#e74c3c\")\n\n# Rama SÍ: Normalidad\nrect(0.5, 5, 2.5, 6, col = \"#d5f5e3\", border = \"#27ae60\", lwd = 2)\ntext(1.5, 5.7, \"SÍ\\n(Shapiro P > 0.05)\", font = 2, cex = 0.75, col = \"#27ae60\")\ntext(1.5, 5.2, \"Test paramétrico\", cex = 0.7)\n\nsegments(1.5, 5, 1.5, 3.2, lwd = 2, col = \"#27ae60\")\n\n# Sub-rama: ¿varianzas iguales?\nrect(0.5, 2.2, 2.5, 3.2, col = \"#fef9e7\", border = \"#f39c12\", lwd = 2)\ntext(1.5, 2.9, \"¿σ² iguales?\\nTest F\", font = 2, cex = 0.7, col = \"#e67e22\")\n\nsegments(0.5, 2.7, -0.2, 1.2, lwd = 1.8, col = \"#27ae60\")\nsegments(2.5, 2.7, 3.2, 1.2, lwd = 1.8, col = \"#e74c3c\")\n\ntext(-0.3, 1.7, \"SÍ\", font = 2, cex = 0.65, col = \"#27ae60\")\nrect(-1.2, 0.2, 0.6, 1.2, col = \"#27ae60\", border = NA)\ntext(-0.3, 0.7, \"t-Student\\n(var.equal=TRUE)\", font = 2, cex = 0.65, col = \"white\")\n\ntext(3.0, 1.7, \"NO\", font = 2, cex = 0.65, col = \"#e74c3c\")\nrect(2.4, 0.2, 4.2, 1.2, col = \"#2980b9\", border = NA)\ntext(3.3, 0.7, \"t-Welch\\n(por defecto en R)\", font = 2, cex = 0.65, col = \"white\")\n\n# Rama NO: No Normalidad\nrect(9.5, 5, 11.5, 6, col = \"#fadbd8\", border = \"#e74c3c\", lwd = 2)\ntext(10.5, 5.7, \"NO\\n(Shapiro P ≤ 0.05)\", font = 2, cex = 0.75, col = \"#e74c3c\")\ntext(10.5, 5.2, \"Test no paramétrico\", cex = 0.7)\n\nsegments(10.5, 5, 10.5, 3.2, lwd = 2, col = \"#e74c3c\")\n\nrect(9, 2.2, 12, 3.2, col = \"#e74c3c\", border = NA)\ntext(10.5, 2.7, \"Mann-Whitney U\\n(wilcox.test)\", font = 2, cex = 0.75, col = \"white\")\n\n# ── Paso 4 ── Resultado\nrect(3.8, 12.6, 8.2, 13.8, col = NA, border = \"#2c3e50\", lwd = 2.5, lty = 2)\ntext(6, 13.2, \"RESULTADO DEL EJERCICIO:\", cex = 0.7, font = 2, col = \"#2c3e50\")\n\n# ── Resumen para este caso\nrect(5, 0.5, 9, 2, col = \"#f7f9fc\", border = \"#2c3e50\", lwd = 2)\ntext(7, 1.6, \"Para este ejercicio:\", font = 2, cex = 0.8, col = \"#2c3e50\")\ntext(7, 1.1, \"n_A=25, n_B=28 → Muestras moderadas.\\nSi Shapiro P > 0.05 → Welch (por seguridad).\\nSi Shapiro P ≤ 0.05 → Mann-Whitney U.\", cex = 0.65)\n\n# Leyenda\nlegend(\"bottomleft\", c(\"Decisión\", \"Condición\", \"Test final\"),\n       fill = c(\"#e8f8f5\", \"#fef9e7\", \"#27ae60\"),\n       border = c(\"#1abc9c\", \"#f39c12\", NA), cex = 0.55, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](T04_Test_Hipotesis_files/figure-revealjs/unnamed-chunk-35-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-tip}\n**Para este caso concreto:** Con $n_A=25$ y $n_B=28$, el **Teorema Central del Límite** nos protege parcialmente. Si la normalidad es dudosa pero $n$ es moderado, **Welch es una opción razonable**. Si los datos son claramente asimétricos o hay outliers → **Mann-Whitney** sin dudar.\n:::\n\n## Referencias\n\n::: {.reference-box}\n- [@bioestatr2026] — Femia, P. & Luque-Fernández, M. A. (2026). *BioEstatR: Biostatistics Routines in R*. R package. Universidad de Granada.\n- [@luque2026] — Luque-Fernández, M. A. (2026). *Matemáticas para la Estadística Médica con R*. Universidad de Granada.\n- [@student1908] — Student (Gosset, W. S.) (1908). The probable error of a mean. *Biometrika*, 6(1), 1–25.\n- [@neyman1933] — Neyman, J. & Pearson, E. S. (1933). On the problem of the most efficient tests. *Phil. Trans. R. Soc. A*, 231, 289–337.\n- [@fisher1925] — Fisher, R. A. (1925). *Statistical Methods for Research Workers*. Oliver & Boyd.\n- [@fisher1935] — Fisher, R. A. (1935). *The Design of Experiments*. Oliver & Boyd.\n- [@welch1947] — Welch, B. L. (1947). The generalization of Student's problem. *Biometrika*, 34(1/2), 28–35.\n- [@wilcoxon1945] — Wilcoxon, F. (1945). Individual comparisons by ranking methods. *Biometrics Bulletin*, 1(6), 80–83.\n- [@mann1947] — Mann, H. B. & Whitney, D. R. (1947). On a test of whether one of two random variables is stochastically larger. *Ann. Math. Stat.*, 18(1), 50–60.\n- [@wilks1938] — Wilks, S. S. (1938). The large-sample distribution of the likelihood ratio. *Ann. Math. Stat.*, 9(1), 60–62.\n- [@cohen1988] — Cohen, J. (1988). *Statistical Power Analysis for the Behavioral Sciences*. Lawrence Erlbaum.\n- [@wasserstein2016] --- Wasserstein, R. L. & Lazar, N. A. (2016). The ASA's statement on p-values. *The American Statistician*, 70(2), 129–133.\n- [@greenland2016] — Greenland, S. et al. (2016). Statistical tests, P values, confidence intervals, and power. *Eur. J. Epidemiol.*, 31(4), 337–350.\n:::\n",
    "supporting": [
      "T04_Test_Hipotesis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}